// ---------------------------------------------------------------------------
// AUTO-GENERATED CONTENT: everything below was generated by Claude Sonnet 5
// (Anthropic), an LLM coding assistant, under end-to-end development
// supervision - it was generated as prompted, code was not adjusted or
// written. Review before relying on it.
// ---------------------------------------------------------------------------
#pragma once
#include "../structs/Records.hlsl"
#include "../structs/Globals.hlsl"

#define CULL_THREADS 64

// Reads the object buffer (no actual culling logic here - this is a
// diagram skeleton) and emits one mesh-launch record per thread group for
// RenderMeshNode to consume.
[Shader("node")]
[NodeLaunch("broadcasting")]
[NodeDispatchGrid(1, 1, 1)]
[NumThreads(CULL_THREADS, 1, 1)]
void CullNode(
    uint dtid : SV_DispatchThreadID,

    DispatchNodeInputRecord<DispatchRecord> inputRecord,

    [MaxRecords(64)]
    [NodeID("RenderMeshNode")]
    NodeOutput<MeshInputRecord> meshOutput
)
{
    uint count, stride;
    objects.GetDimensions(count, stride);

    ThreadNodeOutputRecords<MeshInputRecord> mesh = meshOutput.GetThreadNodeOutputRecords(1);
    mesh.OutputComplete();
}
