// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// `hlsl-workgraph-diagram puml-render [pUmlFile] [options]`
//
// Renders a .puml file to .png + .svg via a PlantUML server (public by
// default, or --server for a local/self-hosted one) - the last, optional
// step; "build-puml" always writes a valid .puml regardless of whether this
// runs. Split out from build-puml so a .puml can be regenerated and
// re-rendered independently, and so this is the only command that ever
// makes a network call.
//
// --scale lives here, not on build-puml: it's inserted into the .puml text
// on the fly, right before encoding it for the server (see withScale()
// below) - the .puml file on disk is never rewritten, so the same
// build-puml output can be re-rendered at a different scale without
// regenerating it.
// ---------------------------------------------------------------------------

const fs = require('fs');
const path = require('path');

const { parseArgs, VERBOSE_SPEC } = require('../common/cli-args');
const { createLogger } = require('../common/logger');
const { renderWithPlantumlServer } = require('./plantuml-server');

function printHelp() {
    console.log(`Usage: hlsl-workgraph-diagram puml-render [pUmlFile] [options]

Renders pUmlFile to <pUmlFile without .puml>.png and .svg via a PlantUML
server.

Arguments:
  pUmlFile   .puml file to render. Default: work-graph.puml, in the current
             working directory.

Options:
  --scale <multiplier>   Diagram scale, inserted into the .puml text as
                          PlantUML's own "scale <n>" directive right before
                          rendering (the .puml file on disk is untouched).
                          Raises the rendered .png's pixel resolution
                          proportionally; .svg is vector, so this mainly
                          affects its declared width/height. Default: 2.
  --server <url>          PlantUML server base URL.
                           Default: https://www.plantuml.com/plantuml
  --verbose, -v           Print the exact request URLs, retry attempts, and
                          bytes written, instead of just the summary line.
  --help, -h, -?          Show this help text and exit.
`);
}

// Inserts (or replaces) a "scale <n>" line right after "@startuml" -
// deliberately the plain multiplier form ("scale 2"), never PlantUML's
// "scale N%" percentage syntax, which was confirmed to silently break
// diagram-type autodetection on at least one real PlantUML server version
// (see the root README's Rendering notes).
function withScale(pumlText, scale) {
    const lines = pumlText.split('\n');
    const startIdx = lines.findIndex((l) => l.trim().startsWith('@startuml'));
    if (startIdx === -1) return pumlText; // not a recognizable .puml - leave it alone
    let insertAt = startIdx + 1;
    if (lines[insertAt] && /^\s*scale\s+/i.test(lines[insertAt])) lines.splice(insertAt, 1);
    lines.splice(insertAt, 0, `scale ${scale}`);
    return lines.join('\n');
}

async function run(argv) {
    const { values, positionals, help } = parseArgs(argv, [
        { name: 'scale', flag: '--scale', type: 'number', default: 2 },
        { name: 'server', flag: '--server', type: 'string', default: 'https://www.plantuml.com/plantuml' },
        VERBOSE_SPEC,
    ]);
    if (help) {
        printHelp();
        return;
    }
    const log = createLogger(values.verbose);

    const inArg = positionals[0] || 'work-graph.puml';
    const inFile = path.resolve(/\.puml$/i.test(inArg) ? inArg : `${inArg}.puml`);
    const server = values.server.replace(/\/+$/, '');
    const outBase = inFile.replace(/\.puml$/i, '');

    const scale = Number.isFinite(values.scale) && values.scale > 0 ? values.scale : 2;
    if (values.scale !== scale) {
        log.info(`Warning: ignoring invalid --scale value (${values.scale}); using ${scale} instead.`);
    }

    const puml = withScale(fs.readFileSync(inFile, 'utf8'), scale);
    try {
        await renderWithPlantumlServer(puml, outBase, server, log);
        log.info(`Rendered ${outBase}.png and ${outBase}.svg via ${server}`);
    } catch (err) {
        if (err.isWriteError) {
            // The server request succeeded; writing the result to disk failed
            // locally (e.g. the existing output file is open elsewhere).
            log.info(`Warning: ${err.message}`);
        } else {
            log.info(
                `Warning: PlantUML server rendering failed (${err.message}). ` +
                    'The .puml file itself is unaffected - this is a rendering-service limitation, not a syntax ' +
                    'error. For a large/detailed diagram, the public PlantUML server has been observed to fail past ' +
                    'a certain accumulated complexity (see the root README\'s Rendering notes); try re-running ' +
                    '"build-puml" with --short and/or --no-edge-label to reduce it, or point --server at a ' +
                    'self-hosted PlantUML instance.'
            );
        }
        process.exitCode = 1;
    }
}

module.exports = { run, printHelp };
