// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM generated by iteratively
// prompt-review cycling the result. None of the code or any of the
// documentation was written by hand. REVIEW THE CODE AND ITS BEHAVIOR BEFORE
// RELYING ON IT.
// ---------------------------------------------------------------------------
'use strict';

// Renders with a local plantuml.jar (needs java, and Graphviz for most diagram
// types) - nothing leaves the machine, and there is no server size limit
// beyond PLANTUML_LIMIT_SIZE, raised here. PlantUML names its outputs after the
// @start line's diagram name, so it renders into a temp dir and renames.

const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFileSync } = require('child_process');

function renderWithLocalJar(pumlText, outBase, jar, log) {
    const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'hlsl-workgraph-render-'));
    const src = path.join(tmp, 'diagram.puml');
    fs.writeFileSync(src, pumlText, 'utf8');
    for (const fmt of ['svg', 'png']) {
        const outDir = path.join(tmp, fmt);
        const args = ['-DPLANTUML_LIMIT_SIZE=16384', '-jar', jar, `-t${fmt}`, '-o', outDir, src];
        log.verbose(`+ java ${args.join(' ')}`);
        execFileSync('java', args, { stdio: ['ignore', 'ignore', 'inherit'] });
        const produced = fs.readdirSync(outDir).filter((f) => f.endsWith(`.${fmt}`));
        if (produced.length !== 1) throw new Error(`expected one .${fmt} from PlantUML, got ${produced.length}`);
        fs.copyFileSync(path.join(outDir, produced[0]), `${outBase}.${fmt}`);
    }
    fs.rmSync(tmp, { recursive: true, force: true });
    // PlantUML draws a syntax error INTO the image instead of failing.
    if (/syntax error/i.test(fs.readFileSync(`${outBase}.svg`, 'utf8'))) {
        const err = new Error(`PlantUML reported a syntax error (see ${outBase}.svg)`);
        err.isSyntaxError = true;
        throw err;
    }
}

module.exports = { renderWithLocalJar };
