// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// PlantUML server rendering (PNG + SVG), using PlantUML's own text-encoding
// scheme (UTF-8 -> raw deflate -> custom base64-ish alphabet) so the diagram
// can be requested via a simple GET, no server-side session/upload needed.
// ---------------------------------------------------------------------------

const fs = require('fs');
const zlib = require('zlib');
const http = require('http');
const https = require('https');

function plantumlEncode6bit(b) {
    if (b < 10) return String.fromCharCode(48 + b);
    b -= 10;
    if (b < 26) return String.fromCharCode(65 + b);
    b -= 26;
    if (b < 26) return String.fromCharCode(97 + b);
    b -= 26;
    if (b === 0) return '-';
    if (b === 1) return '_';
    return '?';
}

function plantumlAppend3Bytes(b1, b2, b3) {
    const c1 = b1 >> 2;
    const c2 = ((b1 & 0x3) << 4) | (b2 >> 4);
    const c3 = ((b2 & 0xf) << 2) | (b3 >> 6);
    const c4 = b3 & 0x3f;
    return (
        plantumlEncode6bit(c1 & 0x3f) +
        plantumlEncode6bit(c2 & 0x3f) +
        plantumlEncode6bit(c3 & 0x3f) +
        plantumlEncode6bit(c4 & 0x3f)
    );
}

function plantumlEncode(text) {
    const deflated = zlib.deflateRawSync(Buffer.from(text, 'utf8'), { level: 9 });
    let r = '';
    for (let i = 0; i < deflated.length; i += 3) {
        if (i + 2 < deflated.length) r += plantumlAppend3Bytes(deflated[i], deflated[i + 1], deflated[i + 2]);
        else if (i + 1 < deflated.length) r += plantumlAppend3Bytes(deflated[i], deflated[i + 1], 0);
        else r += plantumlAppend3Bytes(deflated[i], 0, 0);
    }
    return r;
}

function fetchBinary(url, log) {
    if (log) log.verbose(`GET ${url}`);
    return new Promise((resolve, reject) => {
        const mod = url.startsWith('https:') ? https : http;
        mod
            .get(url, (res) => {
                if (res.statusCode !== 200) {
                    res.resume();
                    reject(new Error(`HTTP ${res.statusCode} for ${url}`));
                    return;
                }
                const chunks = [];
                res.on('data', (d) => chunks.push(d));
                res.on('end', () => {
                    const body = Buffer.concat(chunks);
                    const contentType = res.headers['content-type'] || '';
                    // The public PlantUML server has been observed to occasionally
                    // return an empty 200 "text/plain" response instead of an image
                    // for a diagram it fails to render server-side (seen specifically
                    // for a richly-formatted node label combined with a long doc
                    // comment - see generate-workgraph-diagram.md's Known limitations)
                    // - and Cloudflare then caches that empty response at the edge for
                    // up to 30 days (Cache-Control: public, max-age=2592000). The
                    // *identical* request has repeatedly been observed to succeed
                    // moments later, so this is treated as retryable rather than fatal.
                    if (!contentType.startsWith('image/') || body.length === 0) {
                        reject(new Error(`non-image response (content-type: ${contentType || 'none'}, ${body.length} bytes) for ${url}`));
                        return;
                    }
                    resolve(body);
                });
            })
            .on('error', reject);
    });
}

// Reads a PNG's pixel dimensions straight out of its IHDR chunk (always the
// first chunk, at a fixed offset - no need for a real PNG parser): 8-byte
// signature, then a 4-byte chunk length, 4-byte "IHDR" tag, then width and
// height as big-endian uint32s.
function readPngDimensions(buf) {
    if (buf.length < 24 || buf.toString('ascii', 12, 16) !== 'IHDR') return null;
    return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
}

// Reads the width/height PlantUML puts on the root <svg> element (in px).
function readSvgDimensions(buf) {
    const text = buf.toString('utf8', 0, Math.min(buf.length, 2000));
    const m = text.match(/<svg[^>]*\swidth="(\d+)px"\s+height="(\d+)px"/);
    return m ? { width: parseInt(m[1], 10), height: parseInt(m[2], 10) } : null;
}

function delay(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
}

async function fetchBinaryWithRetry(url, attempts, backoffMs, log) {
    let lastErr;
    for (let i = 0; i < attempts; i++) {
        try {
            return await fetchBinary(url, log);
        } catch (err) {
            lastErr = err;
            if (i < attempts - 1) {
                if (log) log.verbose(`  retrying (${i + 2}/${attempts}) after: ${err.message}`);
                await delay(backoffMs);
            }
        }
    }
    throw lastErr;
}

// Writes a rendered output file, tagging failures as write errors (as
// opposed to fetch/server errors) so callers can report them accurately -
// e.g. "UNKNOWN: unknown error, open '...png'" on Windows when the existing
// file is held open by another program (an image viewer, VS Code preview,
// etc.) is a local filesystem problem, not a PlantUML server one.
function writeOutputFile(filePath, data, log) {
    try {
        fs.writeFileSync(filePath, data);
    } catch (err) {
        const wrapped = new Error(
            `could not write ${filePath} (${err.message}) - it may be open in another program ` +
                '(an image/SVG viewer, editor, etc.); close it and re-run puml-render.'
        );
        wrapped.isWriteError = true;
        throw wrapped;
    }
    log.verbose(`Wrote ${filePath} (${data.length} bytes)`);
}

async function renderWithPlantumlServer(pumlText, outBase, serverBase, logger) {
    const log = logger || require('../common/logger').createLogger(false);
    const encoded = plantumlEncode(pumlText);
    const [png, svg] = await Promise.all([
        fetchBinaryWithRetry(`${serverBase}/png/${encoded}`, 3, 1500, log),
        fetchBinaryWithRetry(`${serverBase}/svg/${encoded}`, 3, 1500, log),
    ]);
    writeOutputFile(`${outBase}.png`, png, log);
    writeOutputFile(`${outBase}.svg`, svg, log);

    // Most PlantUML servers cap PNG output at a fixed pixel limit per
    // dimension (PLANTUML_LIMIT_SIZE, commonly 4096) and silently crop
    // anything past it rather than erroring - confirmed against the real
    // MasterThesis diagram at --scale 2 (see generate-workgraph-diagram.md's
    // Known limitations). The .svg has no such limit (vector), so comparing
    // its declared size against the actual PNG pixel size - both already in
    // hand, no extra request - catches this without guessing at a specific
    // limit value.
    // A tolerance well above the few-pixel rounding slack normally seen
    // between the PNG rasterizer's and the SVG's declared size (observed up
    // to ~2px on diagrams that were not cropped), but far below any crop
    // that would actually matter (a size limit kicking in cuts off hundreds
    // of pixels at minimum) - so this only fires for genuine cropping.
    const CROP_TOLERANCE_PX = 16;
    const pngDims = readPngDimensions(png);
    const svgDims = readSvgDimensions(svg);
    if (
        pngDims &&
        svgDims &&
        (pngDims.width < svgDims.width - CROP_TOLERANCE_PX || pngDims.height < svgDims.height - CROP_TOLERANCE_PX)
    ) {
        log.info(
            `Warning: the rendered .png (${pngDims.width}x${pngDims.height}) is smaller than the diagram's ` +
                `actual size (${svgDims.width}x${svgDims.height}, per the .svg) - it looks like the PlantUML ` +
                'server cropped it against its own pixel-size limit (commonly PLANTUML_LIMIT_SIZE=4096) ' +
                'rather than erroring. The .svg does not have this limit and is the complete diagram. To get ' +
                'a complete .png too: lower --scale, or point --server at a self-hosted PlantUML instance ' +
                'started with -DPLANTUML_LIMIT_SIZE=<n> (or the PLANTUML_LIMIT_SIZE env var) set higher.'
        );
    }
}

module.exports = {
    plantumlEncode6bit,
    plantumlAppend3Bytes,
    plantumlEncode,
    fetchBinary,
    readPngDimensions,
    readSvgDimensions,
    delay,
    fetchBinaryWithRetry,
    renderWithPlantumlServer,
};
