// ---------------------------------------------------------------------------
// AUTO-GENERATED CONTENT: everything below was generated by Claude Sonnet 5
// (Anthropic), an LLM coding assistant, under end-to-end development
// supervision - it was generated as prompted, code was not adjusted or
// written. Review before relying on it.
// ---------------------------------------------------------------------------
// Include guard, not #pragma once: this file is #included via differently
// spelled relative paths from nodes-compute/ and nodes-mesh/
// ("nodes-compute/../structs/Records.hlsl" vs
// "nodes-mesh/../structs/Records.hlsl") and dxc's #pragma once tracking
// doesn't dedupe those as the same file - same finding as
// experimental/hlsl/structs/Records.hlsl, see experimental/README.md.
// This is a harness-local copy for compiling examples/mesh-culling; the
// real example under examples/ is left untouched.
#ifndef HARNESS_MESH_CULLING_STRUCTS_RECORDS_HLSL
#define HARNESS_MESH_CULLING_STRUCTS_RECORDS_HLSL

// EntryNode -> CullNode
struct DispatchRecord
{
    uint objectCount;
};

// CullNode -> RenderMeshNode. DispatchGrid is picked at runtime, up to the
// ceiling declared by RenderMeshNode's [NodeMaxDispatchGrid].
struct MeshInputRecord
{
    uint3 DispatchGrid : SV_DispatchGrid;
    uint objectIndex;
};

#endif
