// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM generated by iteratively
// prompt-review cycling the result. None of the code or any of the
// documentation was written by hand. REVIEW THE CODE AND ITS BEHAVIOR BEFORE
// RELYING ON IT.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// `hlsl-workgraph-diagram pipeline <config.json> [outDir] [options]`
//
// Runs the whole tool over a list of dispatch definitions (docs/pipeline.md):
// compile once per distinct #define set, cut each dispatch's subgraph from its
// entry, and write per dispatch an IR, a graph diagram and a records diagram,
// then a frame diagram over all dispatches in the declared order and one
// validation report. The definitions are the only thing the tool cannot infer:
// which entry each DispatchGraph starts at, with which entry record and defines.
// ---------------------------------------------------------------------------

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const { parseArgs } = require('../common/cli-args');
const { writeIrFile } = require('../common/ir');
const { compileToDisassembly } = require('../parse-dxil/run-dxc');
const { makeResolver } = require('../parse-dxil/disassembly');
const { buildIr } = require('../parse-dxil/to-ir');
const { subsetIr } = require('../common/ir-subset');

const CLI = path.resolve(__dirname, '..', '..', 'generate-workgraph-diagram.js');

function printHelp() {
    console.log(`Usage: hlsl-workgraph-diagram pipeline <config.json> [outDir] [options]

Runs parse-dxil, build-puml, build-records and validate over a list of
dispatch definitions (see docs/pipeline.md for the config format). Writes into
outDir (default: <config name>-out next to the config):
  NN-<name>.ir.json / .graph.puml / .records.puml   one set per dispatch
  frame.plan.json / frame.puml                      all dispatches, in order
  validation.txt / validation.json

Options:
  --render            Also render every .puml to .svg/.png (puml-render).
  --jar <file>        Render locally with this plantuml.jar (implies --render).
  --server <url>      Render via this PlantUML server (implies --render).
  --help, -h, -?      Show this help text and exit.
`);
}

const node = (args, opts = {}) => execFileSync(process.execPath, [CLI, ...args], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'inherit'], ...opts });

function run(argv) {
    const { values, positionals, help } = parseArgs(argv, [
        { name: 'render', flag: '--render', type: 'boolean', default: false },
        { name: 'jar', flag: '--jar', type: 'string', default: null },
        { name: 'server', flag: '--server', type: 'string', default: null },
    ]);
    if (help || !positionals[0]) {
        printHelp();
        return;
    }
    const configFile = path.resolve(positionals[0]);
    const base = path.dirname(configFile);
    const config = JSON.parse(fs.readFileSync(configFile, 'utf8'));
    const outDir = path.resolve(positionals[1] || path.join(base, `${path.basename(configFile, '.json')}-out`));
    fs.mkdirSync(outDir, { recursive: true });
    const compile = config.compile || {};
    const diagram = config.diagram || {};
    if (!config.source) throw new Error(`${configFile}: "source" (the HLSL file to compile) is required`);
    if (!Array.isArray(config.dispatches) || !config.dispatches.length) throw new Error(`${configFile}: "dispatches" must be a non-empty array`);

    // One compile per distinct define set.
    const irByKey = new Map();
    const fullIrFile = new Map();
    const irFor = (defines) => {
        const key = JSON.stringify([...defines].sort());
        if (irByKey.has(key)) return { ir: irByKey.get(key), file: fullIrFile.get(key) };
        const { dis, dxcExe, dxcVersion } = compileToDisassembly(path.resolve(base, config.source), {
            dxcPath: compile.dxc ? path.resolve(base, compile.dxc.replace(/^~(?=\/)/, require('os').homedir())) : null,
            dxcVersion: compile.dxcVersion || null,
            defines,
            profile: compile.profile || 'lib_6_8',
            extraArgs: compile.dxcArgs || [],
            logger: { info: () => {}, verbose: () => {} },
        });
        const ir = buildIr(dis, makeResolver(dis.rawMap), { entryFile: path.resolve(base, config.source), defines, profile: compile.profile, extraArgs: compile.dxcArgs || [], dxcExe, dxcVersion });
        const file = path.join(outDir, `compile-${irByKey.size + 1}.ir.json`);
        writeIrFile(file, ir);
        irByKey.set(key, ir);
        fullIrFile.set(key, file);
        console.log(`compiled ${config.source} with [${defines.join(' ') || 'no defines'}] -> ${path.basename(file)} (${ir.nodes.length} nodes)`);
        return { ir, file };
    };

    const graphFlags = [
        ...(diagram.lineType ? ['--line-type', diagram.lineType] : []),
        ...(diagram.short ? ['--short'] : []),
        ...(diagram.nodeComments === false ? ['--no-node-comments'] : []),
        ...(diagram.globalFields ? ['--global-fields'] : []),
        ...(diagram.edgeRecordSize ? ['--edge-record-size'] : []),
    ];
    const pumls = [];
    const planDispatches = [];
    config.dispatches.forEach((d, i) => {
        if (!d.name || !d.entry) throw new Error(`${configFile}: dispatch ${i} needs "name" and "entry"`);
        const defines = [...(compile.defines || []), ...(d.defines || [])];
        const { ir } = irFor(defines);
        if (!ir.nodes.some((n) => n.id === d.entry)) throw new Error(`dispatch "${d.name}": entry node ${d.entry} not found in the compiled graph`);
        const stem = `${String(i + 1).padStart(2, '0')}-${d.name.replace(/[^\w.-]+/g, '_')}`;
        const sub = subsetIr(ir, d.entry);
        sub.dispatch = { name: d.name, entry: d.entry, entryRecord: d.entryRecord || null, defines: d.defines || [] };
        writeIrFile(path.join(outDir, `${stem}.ir.json`), sub);
        node(['build-puml', path.join(outDir, `${stem}.ir.json`), path.join(outDir, `${stem}.graph.puml`), ...graphFlags]);
        node(['build-records', path.join(outDir, `${stem}.ir.json`), path.join(outDir, `${stem}.records.puml`), ...(diagram.lineType ? ['--line-type', diagram.lineType] : []), ...(diagram.recordComments === false ? ['--no-comments'] : [])]);
        pumls.push(`${stem}.graph.puml`, `${stem}.records.puml`);
        planDispatches.push({ id: d.name, label: d.name, entry: d.entry, entryRecord: d.entryRecord || undefined, defines: d.defines && d.defines.length ? d.defines : undefined, ir: `${stem}.ir.json` });
        console.log(`dispatch ${i + 1} "${d.name}": entry ${d.entry}, ${sub.nodes.length} nodes -> ${stem}.*`);
    });

    const plan = { title: `Dispatch definitions (${path.basename(configFile)}, in order)`, dispatches: planDispatches };
    fs.writeFileSync(path.join(outDir, 'frame.plan.json'), JSON.stringify(plan, null, 2) + '\n');
    const firstFull = fullIrFile.values().next().value;
    const frameArgs = [firstFull, '--dispatches', path.join(outDir, 'frame.plan.json'), ...graphFlags, ...(diagram.hideGlobals || []).flatMap((g) => ['--hide-global', g])];
    node(['build-puml', frameArgs[0], path.join(outDir, 'frame.puml'), ...frameArgs.slice(1)]);
    pumls.push('frame.puml');
    // Optional extra renderings of the frame, one per edge-routing style (later --line-type wins).
    for (const lt of diagram.frameLineTypes || []) {
        node(['build-puml', frameArgs[0], path.join(outDir, `frame-${lt}.puml`), ...frameArgs.slice(1), '--line-type', lt]);
        pumls.push(`frame-${lt}.puml`);
    }

    // Per compile: graph-wide checks; then the frame: per-dispatch and cross-dispatch checks in declared order.
    let text = '';
    const all = [];
    const validate = (args, title) => {
        const jsonFile = path.join(outDir, '.validation-part.json');
        let out;
        try { out = node(['validate', ...args, '--json', jsonFile]); } catch (e) { out = e.stdout || ''; }
        text += `== ${title}\n${out}\n`;
        if (fs.existsSync(jsonFile)) { all.push(...JSON.parse(fs.readFileSync(jsonFile, 'utf8')).map((r) => ({ ...r, scope: title }))); fs.unlinkSync(jsonFile); }
    };
    for (const [key, file] of fullIrFile) validate([file], `compile ${path.basename(file)} (defines ${key})`);
    validate([firstFull, '--dispatches', path.join(outDir, 'frame.plan.json'), ...(config.inventory ? ['--inventory', path.resolve(base, config.inventory)] : [])], 'frame');
    fs.writeFileSync(path.join(outDir, 'validation.txt'), text);
    fs.writeFileSync(path.join(outDir, 'validation.json'), JSON.stringify(all, null, 2) + '\n');
    const count = (s) => all.filter((r) => r.status === s).length;
    console.log(`validation: ${count('PASS')} pass, ${count('WARN')} warn, ${count('FAIL')} fail, ${count('INFO')} info -> validation.txt`);

    if (values.render || values.jar || values.server) {
        for (const p of pumls) {
            node(['puml-render', path.join(outDir, p), ...(values.jar ? ['--jar', values.jar] : []), ...(values.server ? ['--server', values.server] : []), '--scale', '1']);
        }
        console.log(`rendered ${pumls.length} diagram(s)`);
    }
    if (count('FAIL')) process.exitCode = 1;
}

module.exports = { run, printHelp };
