// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM generated by iteratively
// prompt-review cycling the result. None of the code or any of the
// documentation was written by hand. REVIEW THE CODE AND ITS BEHAVIOR BEFORE
// RELYING ON IT.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// `hlsl-workgraph-diagram validate <ir.json> [options]`
//
// Static checks over the IR (and, with --dispatches, over a multi-dispatch
// frame), printed as PASS/WARN/FAIL lines. Exit code 1 on any FAIL. Limits
// are the Work Graphs spec's "Node limits" section; DXC checks none of the
// output limits - only CreateStateObject does, at runtime.
// ---------------------------------------------------------------------------

const fs = require('fs');
const path = require('path');

const { parseArgs } = require('../common/cli-args');
const { readIrFile } = require('../common/ir');
const { loadPlan, analysePlan, buildEdges } = require('../common/dispatch-plan');

const MAX_DEPTH = 32; // D3D12_WORK_GRAPHS_MAX_NODE_DEPTH

function printHelp() {
    console.log(`Usage: hlsl-workgraph-diagram validate [inJsonFile] [options]

Checks the work-graph IR against the Work Graphs spec's node limits and for
internal consistency; with --dispatches, also checks the frame's dispatch
sequence (reachability, cross-dispatch UAV hazards, plan rules) and, with
--inventory, compares against a runtime [WorkGraph] node inventory.

Options:
  --dispatches <plan.json>   Dispatch plan (see docs/dispatch-plan.md).
  --inventory <file>         Text containing the app's "[WorkGraph]" startup
                             lines (program / node / entrypoint listing).
  --annotations <file.json>  Record-field annotations (build-records): check
                             every entry names a real field and buffer.
  --json <file>              Also write the results as JSON.
  --help, -h, -?             Show this help text and exit.

Exit code: 1 if any check FAILs, else 0 (WARN does not fail).
`);
}

function run(argv) {
    const { values, positionals, help } = parseArgs(argv, [
        { name: 'dispatches', flag: '--dispatches', type: 'string', default: null },
        { name: 'inventory', flag: '--inventory', type: 'string', default: null },
        { name: 'json', flag: '--json', type: 'string', default: null },
        { name: 'annotations', flag: '--annotations', type: 'string', default: null },
    ]);
    if (help) {
        printHelp();
        return;
    }
    const inFile = path.resolve(positionals[0] || 'work-graph.ir.json');
    const ir = readIrFile(inFile);
    const results = [];
    const report = (status, check, message) => results.push({ status, check, message });

    const nodes = ir.nodes || [];
    const nodesById = new Map(nodes.map((n) => [n.id, n]));
    const edges = buildEdges(nodes);

    checkEdges(nodes, nodesById, edges, report);
    if (ir.recordTypes) checkRecordTypes(ir, values.annotations ? JSON.parse(fs.readFileSync(path.resolve(values.annotations), 'utf8')) : null, report);
    checkNodeLimits(nodes, report);

    let plan = null;
    if (values.dispatches) {
        plan = loadPlan(path.resolve(values.dispatches));
        checkPlan(plan, ir, report);
    }
    if (values.inventory) checkInventory(path.resolve(values.inventory), nodes, plan, report);

    for (const r of results) console.log(`${r.status.padEnd(4)}  ${r.check.padEnd(24)} ${r.message}`);
    const count = (s) => results.filter((r) => r.status === s).length;
    console.log(`\n${count('PASS')} pass, ${count('WARN')} warn, ${count('FAIL')} fail, ${count('INFO')} info`);
    if (values.json) fs.writeFileSync(path.resolve(values.json), JSON.stringify(results, null, 2));
    if (count('FAIL')) process.exitCode = 1;
}

function checkEdges(nodes, nodesById, edges, report) {
    for (const e of edges) {
        const target = nodesById.get(e.to);
        const name = `${e.from} -> ${e.to}`;
        if (!target) {
            report('FAIL', 'edge-target', `${name}: target node does not exist`);
            continue;
        }
        const input = target.inputs[0];
        if (!input) {
            report('FAIL', 'edge-target', `${name}: target has no input record`);
            continue;
        }
        if (e.recordType !== input.recordType) {
            report('FAIL', 'edge-record-type', `${name}: produces ${e.recordType}, consumer takes ${input.recordType}`);
        } else if (e.recordSizeBytes != null && input.recordSizeBytes != null && e.recordSizeBytes !== input.recordSizeBytes) {
            report('FAIL', 'edge-record-size', `${name}: ${e.recordSizeBytes} B produced vs ${input.recordSizeBytes} B consumed`);
        } else {
            report('PASS', 'edge-record-type', `${name}: ${e.recordType}${e.recordSizeBytes != null ? ` (${e.recordSizeBytes} B)` : ''}`);
        }
        if (e.dead) report('WARN', 'dead-edge', `${name}: every allocation site allocates the constant 0 - declared but never carries a record`);
    }
    // A node nothing targets and that is not an entry can never run.
    const targeted = new Set(edges.map((e) => e.to));
    for (const n of nodes) {
        if (!n.isEntry && !targeted.has(n.id)) report('FAIL', 'orphan-node', `${n.id}: not an entry and no producer targets it`);
        if (n.launchMode === 'mesh' && n.outputs.length) report('FAIL', 'mesh-leaf', `${n.id}: mesh node declares node outputs`);
    }
}

// Record layouts: debug info and node metadata are independent views of the same struct, so they must agree.
function checkRecordTypes(ir, annotations, report) {
    for (const [name, t] of Object.entries(ir.recordTypes)) {
        const d = t.dxil;
        if (d && d.recordSizeBytes != null) {
            report(d.recordSizeBytes === t.sizeBytes ? 'PASS' : 'FAIL', 'record-layout-size', `${name}: debug info ${t.sizeBytes} B, DXIL record ${d.recordSizeBytes} B`);
        }
        const dg = d && d.dispatchGridField;
        const src = t.fields.filter((f) => f.sourceSemantic === 'SV_DispatchGrid');
        if (dg || src.length) {
            const f = dg && t.fields.find((x) => x.offsetBytes === dg.offsetBytes);
            const componentBytes = /16$/.test(dg ? dg.componentType : '') ? 2 : 4;
            const ok = dg && f && src.length === 1 && src[0] === f && f.sizeBytes === dg.count * componentBytes;
            report(ok ? 'PASS' : 'FAIL', 'sv-dispatchgrid',
                `${name}: metadata ${dg ? `+${dg.offsetBytes} ${dg.componentType} x${dg.count}` : 'none'}, source ${src.map((x) => x.name).join(', ') || 'none'}`);
        }
    }
    if (!annotations) return;
    const globals = new Set((ir.globals || []).map((g) => g.name));
    for (const [key, a] of Object.entries(annotations)) {
        const [type, field] = key.split('.');
        const t = ir.recordTypes[type];
        if (!t || !t.fields.some((f) => f.name === field)) report('FAIL', 'record-annotation', `${key}: no such record field`);
        else if (a.target && !globals.has(a.target)) report('FAIL', 'record-annotation', `${key}: target ${a.target} is not a resource in the IR`);
        else report('PASS', 'record-annotation', `${key}: ${a.kind}${a.target ? ` -> ${a.target}` : ''}`);
    }
}

function checkNodeLimits(nodes, report) {
    for (const n of nodes) {
        const outs = n.outputs.filter((o) => !(o.recordKind || '').startsWith('Empty'));
        const maxRecords = outs.reduce((a, o) => a + (o.maxRecords?.resolved ?? NaN), 0);
        const outBytes = outs.reduce((a, o) => a + (o.maxRecords?.resolved ?? NaN) * (o.recordSizeBytes ?? NaN), 0);
        const shared = n.groupSharedBytes ?? null;
        if (!outs.length) continue;
        if (Number.isNaN(maxRecords) || Number.isNaN(outBytes)) {
            report('WARN', 'node-output-limits', `${n.id}: MaxRecords or record size unresolved, limits not checked`);
            continue;
        }
        const fails = [];
        if (n.launchMode === 'thread') {
            if (maxRecords > 8) fails.push(`MaxRecords ${maxRecords} > 8`);
            if (outBytes > 128) fails.push(`MaxOutputSize ${outBytes} B > 128 B`);
        } else {
            if (maxRecords > 256) fails.push(`MaxRecords ${maxRecords} > 256`);
            if (outBytes > 32768) fails.push(`MaxOutputSize ${outBytes} B > 32768 B`);
            if (shared != null && outBytes + shared + 8 * maxRecords > 49152) {
                fails.push(`MaxOutputSize + SharedMemorySize + 8*MaxRecords = ${outBytes + shared + 8 * maxRecords} B > 48 KB`);
            }
        }
        if (shared != null && shared > 32768) fails.push(`SharedMemorySize ${shared} B > 32 KB`);
        const summary = `${n.launchMode}: MaxRecords ${maxRecords}, MaxOutputSize ${outBytes} B${shared != null ? `, groupshared ${shared} B` : ''}`;
        if (fails.length) report('FAIL', 'node-output-limits', `${n.id}: ${fails.join('; ')} (${summary})`);
        else report('PASS', 'node-output-limits', `${n.id}: ${summary}`);
    }
}

function checkPlan(plan, ir, report) {
    const analysis = analysePlan(plan, ir.nodes || []);
    const { nodesById, dispatches } = analysis;
    const globalsByName = new Map((ir.globals || []).map((g) => [g.name, g]));

    for (const d of dispatches) {
        const entry = nodesById.get(d.entry);
        if (!entry) report('FAIL', 'dispatch-entry', `${d.id}: entry ${d.entry} is not a node`);
        else if (!entry.isEntry) report('FAIL', 'dispatch-entry', `${d.id}: entry ${d.entry} lacks [NodeIsProgramEntry]`);
        else report('PASS', 'dispatch-entry', `${d.id}: ${d.entry} is a program entry`);
        const maxDepth = Math.max(...d.analysis.depth.values());
        report(maxDepth < MAX_DEPTH ? 'PASS' : 'FAIL', 'graph-depth', `${d.id}: longest chain ${maxDepth + 1} node(s) (limit ${MAX_DEPTH})`);
        report('INFO', 'dispatch-nodes', `${d.id}: ${[...d.analysis.liveIds].sort().join(', ')}${d.analysis.deadIds.size ? `; never launched: ${[...d.analysis.deadIds].sort().join(', ')}` : ''}`);
    }

    // Every graph entry must be dispatched by the plan, and every node reached by some dispatch.
    const planned = new Set(plan.dispatches.map((d) => d.entry));
    for (const n of ir.nodes) {
        if (n.isEntry && !planned.has(n.id)) report('WARN', 'undispatched-entry', `${n.id}: program entry that no dispatch in the plan starts at`);
    }
    const reached = new Set(dispatches.flatMap((d) => d.analysis.nodeIds));
    const unreached = ir.nodes.filter((n) => !reached.has(n.id)).map((n) => n.id);
    report(unreached.length ? 'FAIL' : 'PASS', 'reachability', unreached.length ? `never part of any dispatch: ${unreached.join(', ')}` : `all ${ir.nodes.length} nodes are part of some dispatch`);

    // Dispatches with different entries should not share nodes: a shared node runs in both.
    for (let i = 0; i < dispatches.length; i++) {
        for (let j = i + 1; j < dispatches.length; j++) {
            if (dispatches[i].entry === dispatches[j].entry) continue;
            const shared = dispatches[i].analysis.nodeIds.filter((id) => dispatches[j].analysis.nodeIds.includes(id));
            if (shared.length) report('WARN', 'shared-subgraph', `${dispatches[i].id} and ${dispatches[j].id} both run ${shared.join(', ')}`);
        }
    }

    if (!ir.nodes.some((n) => n.globalAccess)) {
        report('WARN', 'uav-hazards', 'IR has no globalAccess (parse-source, or an older parse-dxil): cross-dispatch data flow not checked');
    } else {
        checkUavFlow(plan, dispatches, globalsByName, report);
        checkAttachmentFlows(plan, dispatches, report);
        checkRules(plan, dispatches, nodesById, globalsByName, report);
    }
}

// Within a frame, dispatches are ordered and separated by a global UAV barrier.
// A plain read must be preceded by a write/atomic in an EARLIER dispatch (or the
// resource must be initialised at frame start); a plain read and a plain write of
// the same UAV inside ONE dispatch is a producer/consumer pair that needs
// globallycoherent + Barrier(DEVICE_SCOPE) - flagged, not proven wrong.
function checkUavFlow(plan, dispatches, globalsByName, report) {
    const initialised = new Set((plan.frameStart && plan.frameStart.initialisedResources) || []);
    const uavs = [...globalsByName.values()].filter((g) => g.resourceClass === 'UAV').map((g) => g.name);
    for (const res of uavs) {
        const producedBefore = [];
        for (const d of dispatches) {
            const a = d.access[res];
            if (!a) continue;
            const producers = [...a.writers, ...a.atomics];
            if (a.readers.length) {
                const readersOnly = a.readers.filter((r) => !producers.includes(r));
                if (a.writers.length && readersOnly.length) {
                    report('WARN', 'same-dispatch-raw', `${res} in ${d.id}: read by ${readersOnly.join(', ')} and written by ${a.writers.join(', ')} in the same dispatch (needs globallycoherent + device-scope barrier)`);
                }
                const atomicOnly = a.atomics.filter((w) => !readersOnly.includes(w));
                if (readersOnly.length && atomicOnly.length) {
                    // Only safe if the read and the atomics touch disjoint elements - not provable from access kinds.
                    report('INFO', 'same-dispatch-atomic', `${res} in ${d.id}: plain read by ${readersOnly.join(', ')} while ${[...new Set(atomicOnly)].join(', ')} update it atomically - check the elements are disjoint`);
                }
                conditionalOnly(res, d, dispatches, producedBefore, initialised, report);
                const src = producedBefore.length ? producedBefore.join('; ') : initialised.has(res) ? 'frame-start initialisation' : null;
                if (src) report('PASS', 'cross-dispatch-flow', `${res}: read in ${d.id} by ${[...new Set(a.readers)].join(', ')} <- produced by ${src}`);
                else if (!producers.length) report('WARN', 'read-before-write', `${res}: read in ${d.id} by ${a.readers.join(', ')}, but no earlier dispatch writes it`);
            }
            if (producers.length) producedBefore.push(`${d.id}:${[...new Set(producers)].join(',')}`);
        }
    }
}

// A reader whose every earlier producer sits in a CONDITIONAL dispatch reads whatever the resource holds
// when those dispatches are skipped: fine if it is initialised at frame start, a hazard otherwise.
function conditionalOnly(res, d, dispatches, producedBefore, initialised, report) {
    if (!producedBefore.length) return;
    const producerIds = producedBefore.map((p) => p.split(':')[0]);
    const allConditional = producerIds.every((id) => dispatches.find((x) => x.id === id)?.conditional);
    if (!allConditional) return;
    if (initialised.has(res)) {
        report('INFO', 'conditional-producer', `${res}: read in ${d.id}, produced only by conditional ${producerIds.join(', ')}; falls back to its frame-start initialisation when skipped`);
    } else {
        report('WARN', 'conditional-producer', `${res}: read in ${d.id}, produced only by conditional ${producerIds.join(', ')} and not initialised at frame start - stale when skipped`);
    }
}

function checkAttachmentFlows(plan, dispatches, report) {
    const initialised = new Set((plan.frameStart && plan.frameStart.initialisedResources) || []);
    const order = dispatches.map((d) => d.id);
    for (const f of plan.attachmentFlows || []) {
        const producedBefore = [];
        for (const d of dispatches) {
            const consumer = (f.consumers || []).find((c) => c.dispatch === d.id);
            if (consumer) {
                const dead = (consumer.nodes || []).filter((id) => !d.analysis.liveIds.has(id));
                if (dead.length) report('FAIL', 'attachment-flow', `${f.resource}: consumer node(s) ${dead.join(', ')} not live in ${d.id}`);
                if (producedBefore.length) {
                    report('PASS', 'attachment-flow', `${f.resource}: sampled in ${d.id} by ${consumer.nodes.join(', ')} <- produced by ${producedBefore.join('; ')}`);
                    conditionalOnly(f.resource, d, dispatches, producedBefore, initialised, report);
                } else if (!initialised.has(f.resource)) {
                    report('WARN', 'attachment-flow', `${f.resource}: consumed in ${d.id} before any producer`);
                }
            }
            const producer = (f.producers || []).find((p) => p.dispatch === d.id);
            if (producer) {
                const live = (producer.nodes || []).filter((id) => d.analysis.liveIds.has(id));
                if (!live.length) report('FAIL', 'attachment-flow', `${f.resource}: no live producer node in ${d.id}`);
                else producedBefore.push(`${d.id}:${live.join(',')}`);
            }
        }
        for (const x of [...(f.producers || []), ...(f.consumers || [])]) {
            if (!order.includes(x.dispatch)) report('FAIL', 'attachment-flow', `${f.resource}: dispatch ${x.dispatch} not in the plan`);
        }
    }
}

function checkRules(plan, dispatches, nodesById, globalsByName, report) {
    for (const rule of plan.rules || []) {
        const violations = [];
        for (const d of dispatches) {
            if (rule.dispatches && !rule.dispatches.includes(d.id)) continue;
            for (const id of d.analysis.liveIds) {
                const n = nodesById.get(id);
                if (rule.launchModes && !rule.launchModes.includes(n.launchMode)) continue;
                for (const [res, label] of Object.entries(n.globalAccess || {})) {
                    const g = globalsByName.get(res);
                    if (!g || !rule.forbidRead || g.space !== rule.forbidRead.space) continue;
                    if (/read|atomic/.test(label)) violations.push(`${d.id}:${id} reads ${res} (space${g.space})`);
                }
            }
        }
        if (violations.length) report('FAIL', `rule:${rule.id}`, violations.join('; '));
        else report('PASS', `rule:${rule.id}`, rule.description || '');
    }
}

// The app's startup inventory: per program, the node list and entrypoint list
// the runtime actually built. Expected = IR nodes + that program's renamed copies.
function checkInventory(file, nodes, plan, report) {
    const text = fs.readFileSync(file, 'utf8');
    const programs = [];
    let cur = null;
    for (const line of text.split(/\r?\n/)) {
        let m;
        if ((m = line.match(/\[WorkGraph\] program (\d+) \("([^"]+)".*?(\d+) nodes, (\d+) entrypoints/))) {
            cur = { index: Number(m[1]), name: m[2], nodes: [], entrypoints: [], declaredNodes: Number(m[3]), declaredEntries: Number(m[4]) };
            programs.push(cur);
        } else if (cur && (m = line.match(/\[WorkGraph\]\s+node\s+\d+: (\w+)\[(\d+)\]/))) cur.nodes.push(m[1]);
        else if (cur && (m = line.match(/\[WorkGraph\]\s+entrypoint\s+\d+: (\w+)\[(\d+)\]/))) cur.entrypoints.push(m[1]);
    }
    if (!programs.length) {
        report('FAIL', 'inventory', `${file}: no [WorkGraph] program lines found`);
        return;
    }
    const irIds = new Set(nodes.map((n) => n.id));
    const irEntries = nodes.filter((n) => n.isEntry).map((n) => n.id);
    for (const p of programs) {
        const planProgram = plan && Object.entries(plan.programs || {}).find(([, v]) => v.stateObjectName === p.name);
        const renamed = planProgram ? planProgram[1].renamedCopies || [] : [];
        const label = `program ${p.index} "${p.name}"${planProgram ? ` (${planProgram[0]})` : ''}`;
        const expected = new Set([...irIds, ...renamed]);
        const missing = [...expected].filter((id) => !p.nodes.includes(id));
        const extra = p.nodes.filter((id) => !expected.has(id));
        if (missing.length || extra.length) {
            report('FAIL', 'inventory-nodes', `${label}: missing ${missing.join(', ') || '-'}; unexpected ${extra.join(', ') || '-'}`);
        } else {
            report('PASS', 'inventory-nodes', `${label}: ${p.nodes.length} runtime nodes = ${irIds.size} IR nodes + ${renamed.length} renamed copies`);
        }
        const expectedEntries = new Set([...irEntries, ...renamed]);
        const eMissing = [...expectedEntries].filter((id) => !p.entrypoints.includes(id));
        const eExtra = p.entrypoints.filter((id) => !expectedEntries.has(id));
        report(eMissing.length || eExtra.length ? 'FAIL' : 'PASS', 'inventory-entrypoints',
            eMissing.length || eExtra.length
                ? `${label}: missing ${eMissing.join(', ') || '-'}; unexpected ${eExtra.join(', ') || '-'}`
                : `${label}: entrypoints ${p.entrypoints.join(', ')}`);
        if (plan && planProgram) {
            for (const d of plan.dispatches.filter((x) => x.program === planProgram[0])) {
                report(p.entrypoints.includes(d.entry) ? 'PASS' : 'FAIL', 'inventory-dispatch', `${d.id}: entry ${d.entry} ${p.entrypoints.includes(d.entry) ? 'is' : 'is NOT'} an entrypoint of ${label}`);
            }
        }
    }
}

module.exports = { run, printHelp };
