// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM generated by iteratively
// prompt-review cycling the result. None of the code or any of the
// documentation was written by hand. REVIEW THE CODE AND ITS BEHAVIOR BEFORE
// RELYING ON IT.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// Multi-dispatch view (build-puml --dispatches plan.json): one package per
// DispatchGraph call, holding a copy of the subgraph reachable from that
// dispatch's entrypoint, plus one box per UAV with the write/atomic/read
// edges that carry data BETWEEN dispatches - the dependency record edges
// cannot show once generation and rasterisation are separate dispatches.
// Every node is replicated per dispatch, so aliases are "<dispatchId>__<id>".
// ---------------------------------------------------------------------------

const { pumlEscape } = require('../common/text-utils');
const { THEMES } = require('../common/themes');
const { launchStereotype, classifyGrid, buildLabel, edgeRecordCountBraces } = require('./node-label');
const { globalBoxLabel, sanitizeAlias } = require('./global-boxes');
const { renderPreamble, renderGlobalTable, provenanceLines, recordTypeSpanFor } = require('./document');

const entryRecordText = (r) => (typeof r === 'object' ? Object.entries(r).map(([k, v]) => `${k} = ${v}`).join(', ') : String(r));

// What each pinned entry-record field reaches in this dispatch (from the DXIL dataflow).
function impactLines(d) {
    const imp = d.entryRecordImpact;
    if (!imp) return [];
    return Object.entries(imp.fields).map(([f, x]) => {
        const parts = [];
        if (x.controls.length) parts.push(`branches in ${x.controls.join(', ')}`);
        if (x.counts.length) parts.push(`counts of ${x.counts.join(', ')}`);
        if (x.indexes.length) parts.push(`indexes ${x.indexes.join(', ')}`);
        if (x.copiedTo.length) parts.push(`copied to ${x.copiedTo.join(', ')}`);
        return `<size:9><i>${pumlEscape(f)} → ${pumlEscape(parts.join('; ') || 'no effect found')}</i></size>`;
    });
}

const nodeAlias = (dispatchId, id) => `${sanitizeAlias(dispatchId)}__${sanitizeAlias(id)}`;
const resourceAlias = (name) => `res_${sanitizeAlias(name)}`;

// Colours for the three access kinds on resource edges - fixed rather than
// themed: they must stay distinguishable from the record edges in both themes.
const ACCESS_COLOURS = { write: '#C0392B', atomic: '#D68910', read: '#2471A3', attachment: '#7D3C98' };

function renderDispatchPlantUml(ir, plan, planAnalysis, opts, provenance = {}) {
    const theme = opts.dark ? THEMES.dark : THEMES.light;
    const globals = ir.globals || [];
    const globalsByName = new Map(globals.map((g) => [g.name, g]));
    const hidden = new Set([...((plan.diagram && plan.diagram.hideResources) || []), ...(opts.hideGlobals || [])]);
    const { nodesById, dispatches } = planAnalysis;

    // UAVs drawn as boxes: every one some live node of some dispatch touches.
    const boxed = globals.filter(
        (g) => g.resourceClass === 'UAV' && !hidden.has(g.name) && dispatches.some((d) => d.access[g.name])
    );
    const boxedNames = new Set(boxed.map((g) => g.name));

    const lines = ['@startuml WorkGraphDispatches'];
    lines.push(...renderPreamble(theme, opts));
    lines.push('skinparam rectangle {');
    lines.push(`    BackgroundColor<<dead>> ${theme.external}`);
    lines.push('    BorderStyle<<dead>> dotted');
    lines.push('    FontColor<<dead>> #888888');
    lines.push('}');
    lines.push('skinparam database {');
    lines.push(`    BackgroundColor ${theme.globalBg}`);
    lines.push(`    BorderColor ${theme.globalBorder}`);
    lines.push('}');
    lines.push('skinparam PackageFontSize 15');
    lines.push('');

    for (const d of dispatches) {
        const program = (plan.programs && plan.programs[d.program]) || {};
        const pixelShaders = program.meshNodePixelShaders || {};
        const title = [
            `<b>${pumlEscape(d.id)}${d.label && d.label !== d.id ? ` · ${pumlEscape(d.label)}` : ''}</b>`,
            `<size:10>${[`entry ${pumlEscape(d.entry)}`, d.program ? `program ${pumlEscape(d.program)}` : null, d.bindings ? pumlEscape(d.bindings) : null].filter(Boolean).join(' · ')}</size>`,
            d.entryRecord ? `<size:10>entry record: ${pumlEscape(entryRecordText(d.entryRecord))}</size>` : null,
            d.defines && d.defines.length ? `<size:10>defines: ${pumlEscape(d.defines.join(' '))}</size>` : null,
            ...impactLines(d),
            d.conditional ? `<size:10><i>${pumlEscape(d.conditional)}</i></size>` : null,
            d.note ? `<size:10>${pumlEscape(d.note)}</size>` : null,
        ]
            .filter(Boolean)
            .join('\\n');
        lines.push(`package "${title}" as D_${sanitizeAlias(d.id)} {`);
        for (const id of d.analysis.nodeIds.sort()) {
            const n = d.nodesById.get(id);
            // Resources drawn as boxes are shown by their edges; keep only the rest (SRVs) in the body.
            const view = {
                ...n,
                depth: d.analysis.depth.get(id),
                // Boxed UAVs stay in the body lists too: the box edges show the flow, the list what the node declares.
                globalsUsed: (n.globalsUsed || []).filter((g) => !hidden.has(g)),
                globalAccess: n.globalAccess ? Object.fromEntries(Object.entries(n.globalAccess).filter(([g]) => !hidden.has(g))) : undefined,
            };
            let label = buildLabel(view, classifyGrid(view, opts.shortGridThreadsCount), theme, globalsByName, opts);
            if (n.launchMode === 'mesh' && Object.prototype.hasOwnProperty.call(pixelShaders, id)) {
                const ps = pixelShaders[id];
                label += `\\n<size:10><b>${ps ? `PS: ${pumlEscape(ps)}` : 'depth-only: no pixel shader'}</b></size>`;
            }
            const stereos = [`<<${launchStereotype(n)}>>`];
            if (id === d.entry) stereos.push('<<entry>>');
            if (d.analysis.deadIds.has(id)) {
                stereos.push('<<dead>>');
                label += '\\n<size:10><i>never launched: every producer allocates 0 records</i></size>';
            } else if (classifyGrid(view, false).kind === 'multi') {
                stereos.push('<<multi>>');
            }
            lines.push(`    rectangle "${label}" as ${nodeAlias(d.id, id)} ${stereos.join(' ')}`);
        }
        lines.push('}');
        lines.push('');
    }

    for (const g of boxed) lines.push(`database "${globalBoxLabel(g, theme)}" as ${resourceAlias(g.name)}`);
    // Plan-declared flows the DXIL of the node library cannot show (render targets written by the rasteriser,
    // sampled by pixel shaders compiled separately) - drawn as their own boxes in a distinct colour.
    const attachmentFlows = plan.attachmentFlows || [];
    for (const f of attachmentFlows) {
        const label = [
            `<b><color:${ACCESS_COLOURS.attachment}>${pumlEscape(f.resource)}</color></b>`,
            f.kind ? `<i><size:9>${pumlEscape(f.kind)}</size></i>` : null,
            f.transition ? `<size:8>${pumlEscape(f.transition)}</size>` : null,
        ]
            .filter(Boolean)
            .join('\\n');
        lines.push(`storage "${label}" as ${resourceAlias(`att_${f.resource}`)}`);
    }
    lines.push('');

    // Record edges, per dispatch.
    for (const d of dispatches) {
        for (const e of d.analysis.edges) {
            const arrow = e.dead ? '-[dotted]->' : '-->';
            lines.push(`${nodeAlias(d.id, e.from)} ${arrow} ${nodeAlias(d.id, e.to)}`);
            if (!opts.edgeLabel) continue;
            const parts = [`<i>${recordTypeSpanFor(e.recordType, theme)}</i>${edgeRecordCountBraces(e.maxRecords)}`];
            // Same edge note as the single-graph view (record type, count, output parameter name);
            // the record's byte size only when asked for.
            if (e.varName) parts.push(`<size:8>${e.varName}</size>`);
            if (opts.edgeRecordSize && e.recordSizeBytes != null) parts.push(`<size:8>${e.recordSizeBytes} B/record</size>`);
            if (e.dead) parts.push('<size:8><b>0 records allocated (dead edge)</b></size>');
            lines.push('note on link');
            for (const p of parts) lines.push(`  ${pumlEscape(p)}`);
            lines.push('end note');
        }
    }
    lines.push('');

    // Resource edges: writers/atomics point INTO the box, readers come OUT of it.
    for (const d of dispatches) {
        for (const [res, a] of Object.entries(d.access)) {
            if (!boxedNames.has(res)) continue;
            const alias = resourceAlias(res);
            for (const id of new Set(a.writers)) lines.push(`${nodeAlias(d.id, id)} -[${ACCESS_COLOURS.write},dashed]-> ${alias} : write`);
            for (const id of new Set(a.atomics)) lines.push(`${nodeAlias(d.id, id)} -[${ACCESS_COLOURS.atomic},dashed]-> ${alias} : atomic`);
            for (const id of new Set(a.readers)) {
                lines.push(`${alias} -[${ACCESS_COLOURS.read},dashed]-> ${nodeAlias(d.id, id)} : read`);
            }
        }
    }

    for (const f of attachmentFlows) {
        const alias = resourceAlias(`att_${f.resource}`);
        const colour = ACCESS_COLOURS.attachment;
        const live = (dId, id) => dispatches.some((d) => d.id === dId && d.analysis.liveIds.has(id));
        for (const p of f.producers || []) {
            for (const id of (p.nodes || []).filter((id) => live(p.dispatch, id))) {
                lines.push(`${nodeAlias(p.dispatch, id)} -[${colour},bold]-> ${alias} : ${pumlEscape(p.how || 'writes')}`);
            }
        }
        for (const c of f.consumers || []) {
            for (const id of (c.nodes || []).filter((id) => live(c.dispatch, id))) {
                lines.push(`${alias} -[${colour},bold]-> ${nodeAlias(c.dispatch, id)} : ${pumlEscape(c.how || 'reads')}`);
            }
        }
    }

    const pad = (s) => `  ${s}  `;
    lines.push('');
    lines.push('legend right');
    // Same global resource table as the single-graph view; "used" = used by a node of some dispatch.
    const usedBy = new Map();
    for (const d of dispatches) for (const id of d.analysis.nodeIds) for (const g of d.nodesById.get(id).globalsUsed || []) usedBy.set(g, [...(usedBy.get(g) || []), id]);
    lines.push(...renderGlobalTable(globals, usedBy, theme));
    lines.push(`  <b>${pumlEscape(plan.title || 'Dispatch sequence')}</b>`);
    // Only the columns some dispatch actually has (an inferred plan knows no program or bindings).
    const cols = [['#', (d) => d.id], ['Dispatch', (d) => d.label || ''], ['Entry', (d) => d.entry]];
    if (dispatches.some((d) => d.program)) cols.push(['Program', (d) => d.program || '-']);
    if (dispatches.some((d) => d.bindings)) cols.push(['Bindings', (d) => d.bindings || '-']);
    cols.push(['Nodes (live/dead)', (d) => `${d.analysis.nodeIds.length - d.analysis.deadIds.size}/${d.analysis.deadIds.size}`]);
    lines.push(`  |${cols.map(([h]) => pad(h)).join('|')}|`);
    for (const d of dispatches) lines.push(`  |${cols.map(([, f]) => pad(pumlEscape(String(f(d))))).join('|')}|`);
    // Provenance: everything outside the node boxes and their edges that came from the plan file.
    if (plan.auto) lines.push('  Dispatches inferred: one per [NodeIsProgramEntry] node; their order is host code and unknown here');
    else {
        // Name exactly the plan fields this frame used; everything else in the diagram is read from the DXIL.
        const has = (k) => dispatches.some((d) => d[k] != null && !(Array.isArray(d[k]) && !d[k].length));
        const supplied = ['dispatch order', 'entry nodes'];
        for (const [k, label] of [['entryRecord', 'entry-record values'], ['defines', 'defines'], ['program', 'programs'], ['bindings', 'bindings'],
            ['conditional', 'conditions'], ['note', 'notes']]) if (has(k)) supplied.push(label);
        if (plan.programs) supplied.push('pixel-shader lines');
        if ((plan.attachmentFlows || []).length) supplied.push('purple flows');
        if (plan.diagram && plan.diagram.hideResources) supplied.push('hidden resources');
        lines.push(`  <i>From the dispatch definitions (not inferred): ${pumlEscape(supplied.join(', '))}. Everything else is read from the DXIL.</i>`);
    }
    if (plan.betweenDispatches) lines.push(`  Between dispatches: ${pumlEscape(plan.betweenDispatches)}`);
    if (plan.frameStart && plan.frameStart.note) lines.push(`  Frame start: ${pumlEscape(plan.frameStart.note)}`);
    lines.push('  ');
    lines.push(`  <color:${ACCESS_COLOURS.write}>dashed red</color> = node writes the UAV · <color:${ACCESS_COLOURS.atomic}>dashed orange</color> = atomic (allocator/counter)`);
    lines.push(`  <color:${ACCESS_COLOURS.read}>dashed blue</color> = node reads the UAV · dotted grey = declared but never launched (0 records allocated)`);
    if (attachmentFlows.length) {
        lines.push(`  <color:${ACCESS_COLOURS.attachment}>bold purple</color> = plan-declared attachment flow (render target / sampled texture), not visible in the node DXIL`);
    }
    lines.push('  Solid arrows = work-graph records inside one dispatch; resource access is read from the compiled DXIL');
    if (plan.diagram && plan.diagram.hideResourcesNote) lines.push(`  Hidden: ${pumlEscape(plan.diagram.hideResourcesNote)}`);
    if (opts.hideGlobals && opts.hideGlobals.length) lines.push(`  Hidden by --hide-global: ${pumlEscape(opts.hideGlobals.join(', '))}`);
    const renamed = Object.entries(plan.programs || {}).filter(([, p]) => p.renamedCopies && p.renamedCopies.length);
    if (renamed.length) {
        lines.push('  Not drawn: per-program renamed mesh-node copies (entrypoints with no producer, never dispatched):');
        for (const [name, p] of renamed) lines.push(`    ${pumlEscape(name)}: ${pumlEscape(p.renamedCopies.join(', '))}`);
    }
    lines.push('  ');
    lines.push(`  |${pad('Color')}|${pad('Launch mode')}|`);
    for (const mode of ['broadcasting', 'coalescing', 'thread', 'mesh']) lines.push(`  |${pad(`<${theme[mode]}>`)}|${pad(mode)}|`);
    lines.push('  Red border = the dispatch\'s entrypoint · dashed border = grid can expand to >1 group');
    for (const s of plan.sources || []) lines.push(`  <size:8><color:${theme.greyOne}>source: ${pumlEscape(s)}</color></size>`);
    for (const l of provenanceLines(theme, provenance)) lines.push(`  ${l}`);
    lines.push('endlegend');
    lines.push('@enduml');
    return lines.join('\n');
}

module.exports = { renderDispatchPlantUml, nodeAlias, resourceAlias };
