// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// PlantUML diagram rendering, from the shared IR (see ../common/ir.js) -
// works identically regardless of which parser produced it. Ported from the
// pre-split tool's src/render/plantuml-document.js; the render-time
// constants table is gone (see node-label.js's header comment for why),
// and every option that used to be a module-level constant read from
// ../options is now an explicit `opts` parameter, since this module no
// longer owns CLI parsing (see ./options.js).
// ---------------------------------------------------------------------------

const { pumlEscape } = require('../common/text-utils');
const { THEMES } = require('../common/themes');
const {
    launchStereotype,
    groupDir,
    classifyGrid,
    buildLabel,
    formatScalarInline,
    scalarTotalSuffix,
    edgeRecordCountBraces,
} = require('./node-label');
const { globalAlias, renderGlobalBox } = require('./global-boxes');

// Renders one node as a rectangle. Nodes whose grid can expand to more than
// one thread group (classifyGrid === 'multi') get a dashed border instead of
// the default solid one, via the <<multi>> stereotype.
function renderNodeBlock(n, indentLevel, theme, globalsByName, opts) {
    const stereo = launchStereotype(n);
    const grid = classifyGrid(n, opts.shortGridThreadsCount);
    const stereotypes = [`<<${stereo}>>`];
    if (n.isEntry) stereotypes.push('<<entry>>');
    if (grid.kind === 'multi') stereotypes.push('<<multi>>');

    const label = buildLabel(n, grid, theme, globalsByName, opts);
    const pad = '    '.repeat(indentLevel);
    return [`${pad}rectangle "${label}" as ${n.id} ${stereotypes.join(' ')}`];
}

function renderPlantUml(nodes, edges, externalIds, globals, opts, provenance = {}) {
    const theme = opts.dark ? THEMES.dark : THEMES.light;
    const globalsByName = new Map(globals.map((g) => [g.name, g]));
    const lines = [];
    lines.push('@startuml WorkGraphDependencies');
    // No "scale" directive here any more - puml-render inserts one on the
    // fly at render time instead (see its --scale option), so the same
    // .puml this writes can be re-rendered at a different scale without
    // regenerating it. See puml-render/index.js's withScale() for the
    // still-accurate reasoning on why it's the plain multiplier form
    // ("scale 2"), never the "scale N%" percentage syntax.
    lines.push('hide empty description');
    if (theme.canvasBg) lines.push(`skinparam BackgroundColor ${theme.canvasBg}`);
    lines.push(`skinparam DefaultFontColor ${theme.fontColor}`);
    lines.push(`skinparam ArrowColor ${theme.arrowColor}`);
    lines.push(`skinparam ArrowFontColor ${theme.arrowFontColor}`);
    lines.push(`skinparam NoteBackgroundColor ${theme.noteBg}`);
    lines.push(`skinparam NoteBorderColor ${theme.noteBorder}`);
    lines.push('skinparam NoteBorderThickness 1');
    lines.push('skinparam NoteFontSize 9');
    lines.push(`skinparam NoteFontColor ${theme.fontColor}`);
    lines.push(`skinparam PackageBorderColor ${theme.packageBorder}`);
    if (theme.packageBg) lines.push(`skinparam PackageBackgroundColor ${theme.packageBg}`);
    lines.push(`skinparam PackageFontColor ${theme.fontColor}`);
    lines.push(`skinparam LegendBorderColor ${theme.legendBorder}`);
    if (theme.legendBg) lines.push(`skinparam LegendBackgroundColor ${theme.legendBg}`);
    lines.push(`skinparam LegendFontColor ${theme.fontColor}`);
    // Smaller than PlantUML's default legend font (~14) - the legend is
    // reference material (color key, global resource table, provenance),
    // not the diagram's main content, so it doesn't need equal visual
    // weight.
    lines.push('skinparam LegendFontSize 11');
    lines.push('skinparam rectangle {');
    lines.push('    RoundCorner 12');
    lines.push(`    BorderColor ${theme.rectBorder}`);
    lines.push(`    BackgroundColor<<broadcasting>> ${theme.broadcasting}`);
    lines.push(`    BackgroundColor<<coalescing>> ${theme.coalescing}`);
    lines.push(`    BackgroundColor<<thread>> ${theme.thread}`);
    lines.push(`    BackgroundColor<<mesh>> ${theme.mesh}`);
    lines.push(`    BackgroundColor<<unknown>> ${theme.unknown}`);
    lines.push(`    BackgroundColor<<external>> ${theme.external}`);
    lines.push(`    BorderColor<<entry>> ${theme.entryBorder}`);
    lines.push('    BorderThickness<<entry>> 3');
    lines.push('    BorderStyle<<external>> dashed');
    lines.push('    BorderStyle<<multi>> dashed');
    lines.push('}');
    if (opts.globalBoxes) {
        lines.push('skinparam database {');
        lines.push(`    BackgroundColor ${theme.globalBg}`);
        lines.push(`    BorderColor ${theme.globalBorder}`);
        lines.push('}');
    }
    lines.push('');

    // Group scanned nodes by their source subdirectory (nodes-compute / nodes-mesh).
    const byGroup = new Map();
    for (const n of nodes) {
        const g = groupDir(n);
        if (!byGroup.has(g)) byGroup.set(g, []);
        byGroup.get(g).push(n);
    }

    // Which node-groups actually reference each global. Always computed
    // (not just under --global-boxes): besides driving box replication
    // below, it's also what the legend's "Used?" column reads.
    const globalUsedByGroups = new Map();
    for (const n of nodes) {
        for (const name of n.globalsUsed || []) {
            const g = groupDir(n);
            if (!globalUsedByGroups.has(name)) globalUsedByGroups.set(name, new Set());
            globalUsedByGroups.get(name).add(g);
        }
    }

    // Global boxes are declared *before* that group's node rectangles (and
    // read via an edge running global -> node, see below) so PlantUML's
    // top-down layout naturally places them above the nodes that read them.
    // Globals nobody reads anywhere get no box at all; every global, used
    // or not, is still listed in the dedicated legend table below.
    for (const [group, groupNodes] of [...byGroup.entries()].sort()) {
        lines.push(`package "${pumlEscape(group)}" {`);
        if (opts.globalBoxes) {
            const globalsInGroup = globals
                .filter((g) => globalUsedByGroups.get(g.name)?.has(group))
                .sort((a, b) => (a.regType || '').localeCompare(b.regType || '') || (a.regSlot || 0) - (b.regSlot || 0));
            for (const g of globalsInGroup) {
                lines.push(...renderGlobalBox(g, globalAlias(g.name, group), 1, theme));
            }
        }
        for (const n of groupNodes.sort((a, b) => a.id.localeCompare(b.id))) {
            lines.push(...renderNodeBlock(n, 1, theme, globalsByName, opts));
        }
        lines.push('}');
        lines.push('');
    }

    if (externalIds.size > 0) {
        lines.push('package "external / unresolved" {');
        for (const id of [...externalIds].sort()) {
            lines.push(`    rectangle "${pumlEscape(id)}\\n(not found in nodes-*)" as ${id} <<external>>`);
        }
        lines.push('}');
        lines.push('');
    }

    // Edge labels are drawn as a bordered "note on link" (rather than an
    // inline ": label") so each one gets a slight box around it. Suppressed
    // entirely (just the bare arrow) under --no-edge-label.
    for (const e of edges) {
        lines.push(`${e.from} --> ${e.to}`);
        if (!opts.edgeLabel) continue;

        const labelParts = [];
        if (e.recordType || (e.recordKind && e.recordKind.startsWith('Empty'))) {
            const countBraces = edgeRecordCountBraces(e.maxRecords);
            labelParts.push(`<i>${recordTypeSpanFor(e.recordType, theme)}</i>${countBraces}`);
        }
        if (e.varName) labelParts.push(`<size:8>${e.varName}</size>`);
        if (e.maxRecordsSharedWith) {
            labelParts.push(`<size:9>shared: ${formatScalarInline(e.maxRecordsSharedWith)}${scalarTotalSuffix(e.maxRecordsSharedWith)}</size>`);
        }

        if (labelParts.length) {
            lines.push('note on link');
            for (const p of labelParts) lines.push(`  ${pumlEscape(p)}`);
            lines.push('end note');
        }
    }

    // Otherwise the same arrow representation as the record-flow edges - a
    // global is effectively an input feeding the node, no different in kind
    // from a producer node's output record - just running from the global
    // box *to* the node that reads it and dashed to still read as visually
    // distinct from a record edge at a glance.
    if (opts.globalBoxes) {
        for (const n of nodes) {
            const group = groupDir(n);
            for (const name of n.globalsUsed || []) {
                lines.push(`${globalAlias(name, group)} -[dashed]-> ${n.id}`);
            }
        }
    }

    // A single legend - PlantUML only keeps one - so the color/launch-mode
    // key, border/edge explanations, and the global resource table all have
    // to live in the same block.
    const pad = (s) => `  ${s}  `;

    lines.push('');
    lines.push('legend right');

    // Global resource table - lists *every* discovered global regardless of
    // whether any node reads it (the only place an unused global shows up
    // at all). A field a generator couldn't fill (see docs/ir-format.md)
    // renders as "?" rather than "undefined".
    if (globals.length > 0) {
        const allGlobalsSorted = [...globals].sort(
            (a, b) => (a.regType || '').localeCompare(b.regType || '') || (a.regSlot || 0) - (b.regSlot || 0)
        );
        lines.push('  Global resources:');
        lines.push(`  |${pad('Identifier')}|${pad('Slot')}|${pad('Kind')}|${pad('Value type')}|${pad('Used?')}|`);
        for (const g of allGlobalsSorted) {
            const used = globalUsedByGroups.get(g.name)?.size ? '✓' : '✗';
            const kind = g.kind ? `${g.rw ? 'RW' : ''}${g.kind}` : g.resourceClass || '?';
            const slot = g.regType != null && g.regSlot != null ? `${g.regType}${g.regSlot}` : '?';
            const identCell = `<b><color:${theme.globalHighlight}>${pumlEscape(g.name)}</color></b>`;
            lines.push(`  |${pad(identCell)}|${pad(slot)}|${pad(pumlEscape(kind))}|${pad(pumlEscape(g.valueType || '-'))}|${pad(used)}|`);
        }
        lines.push('  ');
        lines.push('  Register slot prefixes:');
        lines.push('  t<NR> := SRV (shader resource view) - read-only buffer/texture');
        lines.push('  u<NR> := UAV (unordered access view) - read-write buffer/texture');
        lines.push('  b<NR> := CBV (constant buffer view) - small constant-buffer data');
        lines.push('  s<NR> := sampler state');
        lines.push('  ');
    }

    lines.push(`  |${pad('Color')}|${pad('Launch mode')}|`);
    lines.push(`  |${pad(`<${theme.broadcasting}>`)}|${pad('broadcasting')}|`);
    lines.push(`  |${pad(`<${theme.coalescing}>`)}|${pad('coalescing')}|`);
    lines.push(`  |${pad(`<${theme.thread}>`)}|${pad('thread')}|`);
    lines.push(`  |${pad(`<${theme.mesh}>`)}|${pad('mesh')}|`);
    lines.push(`  |${pad(`<${theme.external}>`)}|${pad('external / unresolved reference')}|`);
    if (opts.globalBoxes) {
        lines.push(`  |${pad(`<${theme.globalBg}>`)}|${pad('global resource (StructuredBuffer/ConstantBuffer/... via register())')}|`);
    }
    lines.push('  Red border = graph entry point (NodeIsProgramEntry)');
    lines.push('  Dashed border = grid can expand to >1 thread group per invocation');
    lines.push('  (NodeMaxDispatchGrid, or NodeDispatchGrid != (1,1,1)); solid border = always');
    lines.push('  exactly one group (NodeDispatchGrid(1,1,1), thread launch, or coalescing)');
    if (opts.globalBoxes) {
        lines.push('  A dashed edge from a global resource box into a node means that node reads it -');
        lines.push('  a global is effectively an input too, just dashed to stay visually distinct from');
        lines.push('  a produced-record edge; each global is replicated once per consuming node-group');
        lines.push('  to keep edges short (see the global resource table above for the full, ungrouped list)');
    }
    for (const l of provenanceLines(theme, provenance)) lines.push(`  ${l}`);
    lines.push('endlegend');

    lines.push('@enduml');
    return lines.join('\n');
}

function recordTypeSpanFor(recordType, theme) {
    const typeText = recordType ? `<<${recordType}>>` : '<<empty>>';
    return `<color:${theme.recordHighlight}>${typeText}</color>`;
}

// One or two small, grey, low-emphasis lines at the very end of the
// legend: which version of this tool, which parsing path produced the IR
// (not the source file/path itself - just "source" or "dxil", so this
// stays short regardless of how deep a project's directory tree is), and
// (parse-dxil only, on its own line so it doesn't stretch the legend
// width) which dxc build compiled it. Reproducibility/provenance info, not
// something the reader needs to look at unless they're asking "where did
// this diagram come from".
function provenanceLines(theme, { packageVersion, generator, dxcVersion }) {
    const pathLabel = generator ? generator.replace(/^parse-/, '') : null;
    const summary = [`hlsl-workgraph-diagram${packageVersion ? ` v${packageVersion}` : ''}`];
    if (pathLabel) summary.push(`${pathLabel} parsing`);
    const lines = [`<size:7><color:${theme.greyOne}>${summary.join(' · ')}</color></size>`];
    if (dxcVersion) lines.push(`<size:7><color:${theme.greyOne}>dxc: ${pumlEscape(dxcVersion)}</color></size>`);
    return lines;
}

module.exports = { renderNodeBlock, renderPlantUml };
