// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

const { pumlEscape } = require('../common/text-utils');

function sanitizeAlias(s) {
    return s.replace(/[^A-Za-z0-9_]/g, '_');
}

function globalAlias(name, group) {
    return `global_${sanitizeAlias(name)}_${sanitizeAlias(group)}`;
}

// Falls back to "?" for anything a given IR generator couldn't fill (e.g.
// parse-dxil's kind/regType/regSlot - see docs/ir-format.md) rather than
// rendering "undefined" or the resourceClass-only fallback silently.
function globalBoxLabel(g, theme) {
    const nameLine = `<b><color:${theme.globalHighlight}>${pumlEscape(g.name)}</color></b>`;
    const kindText = g.kind ? `${g.rw ? 'RW' : ''}${g.kind}` : g.resourceClass || '?';
    const regText = g.regType != null && g.regSlot != null ? `${g.regType}${g.regSlot}${g.space ? `, space${g.space}` : ''}` : '?';
    const detailLine = `<i><size:9>${pumlEscape(kindText)} · ${pumlEscape(regText)}</size></i>`;
    const lines = [nameLine, '', detailLine];
    if (g.valueType) {
        lines.push(`<i><size:9><color:${theme.greyOne}><<${pumlEscape(g.valueType)}>></color></size></i>`);
    }
    return lines.join('\\n');
}

// One `database` (cylinder) shape per global *replica* - see the
// GLOBAL_BOXES_ENABLED block in renderPlantUml() for why globals get
// replicated once per consuming node-group rather than drawn once globally.
function renderGlobalBox(g, alias, indentLevel, theme) {
    const pad = '    '.repeat(indentLevel);
    return [`${pad}database "${globalBoxLabel(g, theme)}" as ${alias}`];
}

module.exports = { sanitizeAlias, globalAlias, globalBoxLabel, renderGlobalBox };
