// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// `hlsl-workgraph-diagram build-puml [inJsonFile] [outPUml] [options]`
//
// Reads the shared work-graph IR (see ../common/ir.js, written by either
// "parse-source" or "parse-dxil") and renders it as a PlantUML diagram -
// the one step that's identical regardless of which parser produced the
// IR. Also where node depth (longest path from a graph entry point) is
// computed - a pure graph algorithm over id + edges, so it belongs here,
// not in either parser (see graph.js).
// ---------------------------------------------------------------------------

const fs = require('fs');
const path = require('path');

const { parseArgs } = require('../common/cli-args');
const { createLogger } = require('../common/logger');
const { readIrFile } = require('../common/ir');
const { computeDepths } = require('./graph');
const { renderPlantUml } = require('./document');
const { SPECS, resolveOpts } = require('./options');

function printHelp() {
    console.log(`Usage: hlsl-workgraph-diagram build-puml [inJsonFile] [outPUml] [options]

Reads the shared work-graph IR JSON (written by "parse-source" or
"parse-dxil") and renders it as a PlantUML (.puml) dependency diagram.
Doesn't render a .png/.svg itself - see "hlsl-workgraph-diagram
puml-render" for that (which is also where --scale lives).

Arguments:
  inJsonFile   IR JSON file to read. Default: work-graph.ir.json, in the
               current working directory.
  outPUml      Path to write the .puml file to. ".puml" is appended
               automatically if not already present.
               Default: work-graph.puml, in the current working directory.

Options:
  --dark / --light                 Diagram color theme. Default: --light.
  --short-record-out-count         Show only the resolved record count in a
                                   node's "Record out:" list (e.g. "(192)")
                                   instead of the full "original (resolved)
                                   = total" form. Falls back to the full
                                   form when the count can't be resolved.
  --short-record-in-count          Same, for "Record in:".
  --short-grid-threads-count       Show only the resolved per-axis values in
                                   Grid:/Threads: instead of "(IDENT (32),
                                   1, 1)".
  --short-meta                     Implies --short-grid-threads-count, and
                                   collapses Depth:/Grid:/Threads: into one
                                   smaller-font line.
  --short                          Shorthand for all four --short-* flags.
  --edge-label / --no-edge-label   Show the record type/variable/count note
                                   on each edge. Default: --edge-label (on).
  --global-boxes / --no-global-boxes
                                   Draw a box per global resource read by
                                   any node, dashed edges into every reader,
                                   replicated once per node-group. Default:
                                   off - the global resource table in the
                                   legend lists every global either way.
  --global-list / --no-global-list Show "Globals used:" in a node's body.
                                   Default: on. Independent of
                                   --global-boxes.
  --record-in-names / --no-record-in-names
                                   Show a record parameter's own variable
                                   name alongside its type in "Record in:".
                                   Default: off. Only populated by
                                   parse-source's IR - see docs/ir-format.md.
  --record-out-names / --no-record-out-names
                                   Same, for "Record out:". Default: off.
  --verbose, -v                    Print each node/edge/global found, and
                                    its computed depth, instead of just the
                                    summary counts.
  --help, -h, -?                   Show this help text and exit.
`);
}

function run(argv) {
    const { values, positionals, help } = parseArgs(argv, SPECS);
    if (help) {
        printHelp();
        return;
    }
    const log = createLogger(values.verbose);

    const inArg = positionals[0] || 'work-graph.ir.json';
    const inFile = path.resolve(/\.json$/i.test(inArg) ? inArg : `${inArg}.json`);
    const outArg = positionals[1] || 'work-graph.puml';
    const outFile = path.resolve(/\.puml$/i.test(outArg) ? outArg : `${outArg}.puml`);

    const opts = resolveOpts(values);

    const ir = readIrFile(inFile);
    const nodes = ir.nodes || [];
    const globals = ir.globals || [];
    log.info(`Loaded ${nodes.length} node(s), ${globals.length} global resource(s) from ${inFile} (generator: ${ir.generator}).`);
    for (const n of nodes) log.verbose(`  node "${n.id}" (${n.functionName}): ${n.launchMode || 'unknown'}, group=${n.group || '(none)'}`);
    for (const g of globals) log.verbose(`  global "${g.name}" (${g.kind || g.resourceClass || '?'}) at ${g.regType || '?'}${g.regSlot != null ? g.regSlot : '?'}`);

    const nodesById = new Map(nodes.map((n) => [n.id, n]));

    // Edges: one per output parameter with a linked target.
    const edges = [];
    for (const n of nodes) {
        for (const out of n.outputs) {
            if (!out.linkedNodeID) continue;
            edges.push({
                from: n.id,
                to: out.linkedNodeID.name,
                varName: out.varName,
                recordType: out.recordType,
                recordKind: out.recordKind,
                maxRecords: out.maxRecords,
                maxRecordsSharedWith: out.maxRecordsSharedWith,
            });
        }
    }
    for (const e of edges) log.verbose(`  edge ${e.from} -> ${e.to}${e.recordType ? ` (${e.recordType})` : ''}`);

    const externalIds = new Set();
    for (const e of edges) {
        if (!nodesById.has(e.to)) externalIds.add(e.to);
    }
    for (const id of externalIds) log.verbose(`  external/unresolved reference: ${id}`);

    const depths = computeDepths(nodes, edges);
    for (const n of nodes) n.depth = depths.has(n.id) ? depths.get(n.id) : null;
    for (const n of nodes) log.verbose(`  depth(${n.id}) = ${n.depth == null ? '?' : n.depth}`);

    log.info(`${edges.length} edge(s), ${externalIds.size} external reference(s).`);

    const provenance = {
        packageVersion: require('../../package.json').version,
        generator: ir.generator,
        dxcVersion: (ir.generatorDetail && ir.generatorDetail.dxcVersion) || null,
    };
    const puml = renderPlantUml(nodes, edges, externalIds, globals, opts, provenance);
    fs.mkdirSync(path.dirname(outFile), { recursive: true });
    fs.writeFileSync(outFile, puml, 'utf8');
    log.info(`Wrote ${outFile}`);
}

module.exports = { run, printHelp };
