// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// Builds a node's rectangle label from the shared IR (see
// ../common/ir.js), not from either parser's own internals - this is the
// one place both parse-source's and parse-dxil's output actually look the
// same, since both already resolved their {resolved, source} value fields
// before writing the IR. Ported from the pre-split tool's
// src/render/node-label.js; the one behavior change is unresolved compound
// expressions (e.g. `intDivRUp(COUNT, 4)`) no longer get per-identifier
// sub-annotation ("COUNT (32)" nested inside the unresolved call) - the IR
// only carries "resolved value, or original text" per whole field, not a
// constants table to re-walk here. The original text is still shown in
// full, just not further annotated token-by-token.
// ---------------------------------------------------------------------------

const { pumlEscape } = require('../common/text-utils');

function launchStereotype(node) {
    return node.launchMode || 'unknown';
}

function groupDir(node) {
    return node.group || 'other';
}

// One axis of a triple field ({resolved, source} arrays) as display text.
function formatTripleAxis(resolved, source, short) {
    if (short) return resolved != null ? String(resolved) : source != null ? source : '?';
    if (source != null) return resolved != null ? `${source} (${resolved})` : `${source} (?)`;
    return resolved != null ? String(resolved) : '?';
}

function formatTriple(field, short) {
    if (!field) return null;
    return field.resolved.map((r, i) => formatTripleAxis(r, field.source[i], short)).join(', ');
}

// Appends " = <value>" for a triple whose axes fully resolve, i.e. the
// actual dispatch/thread-group count once multiplied out - skipped
// whenever at least two of the three axes are a plain literal "1" (the
// product then trivially equals the one remaining axis, already visible),
// or when any axis didn't resolve.
function tripleTotalSuffix(field) {
    if (!field) return '';
    const literalOnes = field.resolved.filter((r, i) => field.source[i] == null && r === 1).length;
    if (literalOnes >= 2) return '';
    if (field.resolved.some((r) => r == null)) return '';
    return ` = ${field.resolved.reduce((a, b) => a * b, 1)}`;
}

// A scalar field's plain display text - the original text with the
// resolved value in parens when there is original text to show, else just
// the resolved number (or "?").
function formatScalarInline(field) {
    if (!field) return '?';
    if (field.source != null) return field.resolved != null ? `${field.source} (${field.resolved})` : `${field.source} (?)`;
    return field.resolved != null ? String(field.resolved) : '?';
}

// A scalar field's "(...)" suffix - full mode shows the original text with
// the resolved value in parens (falling back to "?" if unresolved), short
// mode shows just the resolved number (falling back to the original text,
// then "?").
function scalarBraces(field, short) {
    if (!field) return '';
    if (short) {
        return field.resolved != null ? ` (${field.resolved})` : ` (${field.source != null ? field.source : '?'})`;
    }
    return ` (${formatScalarInline(field)}${scalarTotalSuffix(field)})`;
}

// Skipped when there's no original text to simplify (a bare literal) or
// the expression didn't resolve.
function scalarTotalSuffix(field) {
    if (!field || field.source == null || field.resolved == null) return '';
    return ` = ${field.resolved}`;
}

// Edge labels always show just the resolved count (or "?"), regardless of
// --short-record-*-count - matches the pre-split tool's own edge-label
// behavior (a deliberately terser style than the in-node Record in/out
// lines).
function edgeRecordCountBraces(field) {
    if (!field) return '';
    return field.resolved != null ? ` (${field.resolved})` : ' (?)';
}

// Whether a node's dispatch grid is a fixed, statically-known single thread
// group (kind: 'single'), or can/does expand to more than one thread group
// per invocation (kind: 'multi'). Drives the dashed-border visual.
function classifyGrid(n, shortGridThreads) {
    if (n.maxDispatchGrid) {
        // NodeMaxDispatchGrid means the actual grid is set at runtime via
        // SV_DispatchGrid on the output record - always treat as variable.
        return {
            kind: 'multi',
            text: `Grid: ≤(${formatTriple(n.maxDispatchGrid, shortGridThreads)}) dynamic${tripleTotalSuffix(n.maxDispatchGrid)}`,
        };
    }
    if (n.dispatchGrid) {
        const isFixedOne = n.dispatchGrid.resolved.every((r, i) => n.dispatchGrid.source[i] == null && r === 1);
        if (isFixedOne) return { kind: 'single', text: 'Grid: (1,1,1)' };
        return {
            kind: 'multi',
            text: `Grid: (${formatTriple(n.dispatchGrid, shortGridThreads)})${tripleTotalSuffix(n.dispatchGrid)}`,
        };
    }
    if (n.launchMode === 'thread') return { kind: 'single', text: 'Grid: 1 thread/record' };
    if (n.launchMode === 'coalescing') return { kind: 'single', text: 'Grid: 1 group (coalesced)' };
    return { kind: 'single', text: 'Grid: n/a' };
}

function buildThreadsText(n, shortGridThreads) {
    if (!n.numThreads) return 'Threads: n/a';
    return `Threads: (${formatTriple(n.numThreads, shortGridThreads)})${tripleTotalSuffix(n.numThreads)}`;
}

function recordTypeSpan(recordType, theme) {
    const typeText = recordType ? `<<${recordType}>>` : '<<empty>>';
    return `<color:${theme.recordHighlight}>${typeText}</color>`;
}

function smallItalicLine(text) {
    return `<i><size:10>${text}</size></i>`;
}

function outputRecordCountBraces(field, shortRecordOutCount) {
    return scalarBraces(field, shortRecordOutCount);
}

function inputRecordCountBraces(field, shortRecordInCount) {
    return scalarBraces(field, shortRecordInCount);
}

// The global resources this node's HLSL body references, one line per
// global - just above Record in:/Record out: in the label. A field that a
// given IR generator couldn't fill (see docs/ir-format.md - e.g.
// parse-dxil's regType/regSlot/valueType) renders as "?" rather than
// "undefined" or crashing.
function buildGlobalsUsedLines(n, globalsByName, theme, globalListEnabled) {
    if (!globalListEnabled) return null;
    if (!n.globalsUsed || n.globalsUsed.length === 0) return null;
    const valueLines = n.globalsUsed.map((name) => {
        const g = globalsByName.get(name) || { name };
        const identSpan = `<color:${theme.globalHighlight}>${pumlEscape(g.name)}</color>`;
        const regText = g.regType != null && g.regSlot != null ? `${g.regType}${g.regSlot}` : '?';
        const typeSpan = g.valueType ? ` <color:${theme.greyOne}><<${pumlEscape(g.valueType)}>></color>` : '';
        return smallItalicLine(`  ${identSpan} (${regText})${typeSpan}`);
    });
    return [smallItalicLine('Globals used:'), ...valueLines].join('\\n');
}

function buildInputRecordLine(n, theme, shortRecordInCount, recordInNamesEnabled) {
    const input = n.inputs && n.inputs[0];
    if (!input) return null;

    const canReceiveMultiple = input.recordKind === 'GroupNodeInputRecords' || input.recordKind === 'RWGroupNodeInputRecords';
    let value = '';
    if (recordInNamesEnabled && input.varName) value += `${pumlEscape(input.varName)} `;
    value += recordTypeSpan(input.recordType, theme);
    if (canReceiveMultiple && input.maxRecords) {
        value += inputRecordCountBraces(input.maxRecords, shortRecordInCount);
    }
    return [smallItalicLine('Record in:'), smallItalicLine(`  ${value}`)].join('\\n');
}

// Every record type this node emits, in declaration order - not
// deduplicated by type, since distinct output params can carry distinct
// MaxRecords budgets even for the same record type. Mesh-shader out
// indices/vertices/primitives don't count (excluded from both parsers'
// outputs entirely).
function buildOutputRecordsLines(n, theme, shortRecordOutCount, recordOutNamesEnabled) {
    if (!n.outputs || n.outputs.length === 0) return null;
    const valueLines = n.outputs.map((out) => {
        let value = '';
        if (recordOutNamesEnabled && out.varName) value += `${pumlEscape(out.varName)} `;
        value += recordTypeSpan(out.recordType, theme) + outputRecordCountBraces(out.maxRecords, shortRecordOutCount);
        return smallItalicLine(`  ${value}`);
    });
    return [smallItalicLine('Record out:'), ...valueLines].join('\\n');
}

// Greys out standalone "1" digits (not part of a larger number or
// identifier) to signal an unused/default axis, e.g. in "(64, 1, 1)".
function greyOnes(text, greyColor) {
    return text.replace(/\b1\b/g, `<color:${greyColor}>1</color>`);
}

function buildShortMetaLine(n, grid, theme) {
    const stereo = launchStereotype(n);
    const dropGrid = stereo === 'coalescing' || stereo === 'thread';
    const dropThreads = stereo === 'thread';

    const parts = [`Depth: ${n.depth == null ? '?' : n.depth}`];
    if (!dropGrid) parts.push(greyOnes(pumlEscape(grid.text), theme.greyOne));
    if (!dropThreads) parts.push(greyOnes(pumlEscape(buildThreadsText(n, true)), theme.greyOne));
    return `<i><size:9>${parts.join(' | ')}</size></i>`;
}

function buildLabel(n, grid, theme, globalsByName, opts) {
    const nameLine = `<color:${theme.nodeNameHighlight}>${pumlEscape(n.id)}</color>`;

    let meta;
    if (opts.shortMeta) {
        meta = buildShortMetaLine(n, grid, theme);
    } else {
        const depthLine = `<i><size:10>Depth: ${n.depth == null ? '?' : n.depth}</size></i>`;
        const greyedLines = [grid.text, buildThreadsText(n, opts.shortGridThreadsCount)].map(
            (m) => `<i><size:10>${greyOnes(pumlEscape(m), theme.greyOne)}</size></i>`
        );
        meta = [depthLine, ...greyedLines].join('\\n');
    }
    let label = `${nameLine}\\n\\n${meta}`;

    const recordBlock = [
        buildGlobalsUsedLines(n, globalsByName, theme, opts.globalListEnabled),
        buildInputRecordLine(n, theme, opts.shortRecordInCount, opts.recordInNamesEnabled),
        buildOutputRecordsLines(n, theme, opts.shortRecordOutCount, opts.recordOutNamesEnabled),
    ]
        .filter(Boolean)
        .join('\\n');
    if (recordBlock) {
        label += `\\n\\n${recordBlock}`;
    }

    if (n.comment) {
        const commentText = n.comment
            .split('\n')
            .map((l) => `<size:9>${pumlEscape(l)}</size>`)
            .join('\\n');
        label += `\\n\\n${commentText}`;
    }
    if (n.functionName !== n.id) {
        label += `\\n<size:10>(fn: ${pumlEscape(n.functionName)})</size>`;
    }
    return label;
}

module.exports = {
    launchStereotype,
    groupDir,
    formatTriple,
    tripleTotalSuffix,
    formatScalarInline,
    scalarBraces,
    scalarTotalSuffix,
    classifyGrid,
    buildThreadsText,
    recordTypeSpan,
    edgeRecordCountBraces,
    smallItalicLine,
    outputRecordCountBraces,
    inputRecordCountBraces,
    buildGlobalsUsedLines,
    buildInputRecordLine,
    buildOutputRecordsLines,
    greyOnes,
    buildShortMetaLine,
    buildLabel,
};
