// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// CLI flag definitions for `build-puml` - every rendering-choice flag the
// pre-split tool had *except* --render/--no-render/--server/--scale (those
// moved to puml-render: --scale is inserted into the .puml text on the fly
// at render time now, rather than baked into build-puml's output, so the
// same .puml can be re-rendered at a different scale without regenerating
// it - see puml-render/index.js).

const SPECS = [
    { name: 'dark', flag: '--dark', negFlag: '--light', type: 'boolean', default: false },
    { name: 'shortRecordOutCount', flag: '--short-record-out-count', type: 'boolean', default: false },
    { name: 'shortRecordInCount', flag: '--short-record-in-count', type: 'boolean', default: false },
    { name: 'shortGridThreadsCountFlag', flag: '--short-grid-threads-count', type: 'boolean', default: false },
    { name: 'shortMetaFlag', flag: '--short-meta', type: 'boolean', default: false },
    { name: 'short', flag: '--short', type: 'boolean', default: false },
    { name: 'edgeLabel', flag: '--edge-label', negFlag: '--no-edge-label', type: 'boolean', default: true },
    { name: 'globalBoxes', flag: '--global-boxes', negFlag: '--no-global-boxes', type: 'boolean', default: false },
    { name: 'globalListEnabled', flag: '--global-list', negFlag: '--no-global-list', type: 'boolean', default: true },
    { name: 'recordInNamesEnabled', flag: '--record-in-names', negFlag: '--no-record-in-names', type: 'boolean', default: false },
    { name: 'recordOutNamesEnabled', flag: '--record-out-names', negFlag: '--no-record-out-names', type: 'boolean', default: false },
];

// Resolves the raw parsed flag values into the final opts object
// renderPlantUml()/node-label.js actually consume - --short implies all
// four --short-* flags, --short-meta additionally implies
// --short-grid-threads-count (its combined line is meaningless without the
// short per-axis numbers).
function resolveOpts(values) {
    const shortMeta = values.shortMetaFlag || values.short;
    return {
        dark: values.dark,
        shortMeta,
        shortRecordOutCount: values.shortRecordOutCount || values.short,
        shortRecordInCount: values.shortRecordInCount || values.short,
        shortGridThreadsCount: values.shortGridThreadsCountFlag || shortMeta,
        edgeLabel: values.edgeLabel,
        globalBoxes: values.globalBoxes,
        globalListEnabled: values.globalListEnabled,
        recordInNamesEnabled: values.recordInNamesEnabled,
        recordOutNamesEnabled: values.recordOutNamesEnabled,
    };
}

module.exports = { SPECS, resolveOpts };
