// ---------------------------------------------------------------------------
// AUTO-GENERATED CONTENT: everything below was generated by Claude Sonnet 5
// (Anthropic), an LLM coding assistant, under end-to-end development
// supervision - it was generated as prompted, code was not adjusted or
// written. Review before relying on it.
// ---------------------------------------------------------------------------
#ifndef MESH_CULLING_NODES_MESH_RENDERMESHNODE_HLSL
#define MESH_CULLING_NODES_MESH_RENDERMESHNODE_HLSL
#include "../structs/Records.hlsl"
#include "../structs/VertexTypes.hlsl"

#define RMN_THREADS 32

// Mesh-launch node: rasterizes up to 64 triangles per thread group.
[Shader("node")]
[NodeLaunch("mesh")]
[NodeMaxDispatchGrid(64, 1, 1)]
[NumThreads(RMN_THREADS, 1, 1)]
[OutputTopology("triangle")]
void RenderMeshNode(
    uint gtid : SV_GroupThreadID,

    DispatchNodeInputRecord<MeshInputRecord> inputRecord,

    out indices  uint3  triangles[64],
    out vertices Vertex verts[64]
)
{
}

#endif
