// ---------------------------------------------------------------------------
// AUTO-GENERATED CONTENT: everything below was generated by Claude Sonnet 5
// (Anthropic), an LLM coding assistant, under end-to-end development
// supervision - it was generated as prompted, code was not adjusted or
// written. Review before relying on it.
// ---------------------------------------------------------------------------
// Fixture developed for/used to verify parse-dxil - see docs/ir-format.md.
// ---------------------------------------------------------------------------
#pragma once
#include "../structs/Records.hlsl"
#include "../structs/Globals.hlsl"

// Preprocessor test case #1: a #define referenced from an attribute. A
// regex-only scanner has to separately notice this #define and substitute it
// into [MaxRecords(...)] below; dxc resolves it as part of normal
// compilation, so its output (disassembly/reflection) should already show
// the literal 64.
#define ENTRY_MAX_RECORDS 64

// Preprocessor test case #2: dead code that a real preprocessor removes
// before the compiler ever sees it, but that a naive text/regex scan over
// the raw source would still find (a duplicate [NodeIsProgramEntry] with a
// clashing name, which would be a graph-validity error if it were live).
#if 0
[Shader("node")]
[NodeIsProgramEntry]
[NodeLaunch("broadcasting")]
[NodeDispatchGrid(1, 1, 1)]
[NumThreads(1, 1, 1)]
void EntryNode_OldVersion(
    uint dtid : SV_DispatchThreadID,

    [MaxRecords(1)]
    [NodeID("GenerateNode")]
    NodeOutput<WorkItemRecord> workItemOutput
)
{
    ThreadNodeOutputRecords<WorkItemRecord> items = workItemOutput.GetThreadNodeOutputRecords(1);
    items.OutputComplete();
}
#endif

// Graph entry point: a fixed 1x1x1 broadcasting dispatch that fans out up to
// ENTRY_MAX_RECORDS work items to GenerateNode.
[Shader("node")]
[NodeIsProgramEntry]
[NodeLaunch("broadcasting")]
[NodeDispatchGrid(1, 1, 1)]
[NumThreads(1, 1, 1)]
void EntryNode(
    uint dtid : SV_DispatchThreadID,

    [MaxRecords(ENTRY_MAX_RECORDS)]
    [NodeID("GenerateNode")]
    NodeOutput<WorkItemRecord> workItemOutput
)
{
    // Reads the itemMeta global (see structs/Globals.hlsl) — the fixture's
    // one global-resource-usage test case, mirroring
    // examples/mesh-culling's objects/CullNode pair. The value has to
    // actually flow into kept output state (not just be read and dropped),
    // or dxc's optimizer may eliminate the read entirely along with it.
    uint count, stride;
    itemMeta.GetDimensions(count, stride);

    ThreadNodeOutputRecords<WorkItemRecord> items = workItemOutput.GetThreadNodeOutputRecords(ENTRY_MAX_RECORDS);
    items[0].itemId = count;
    items.OutputComplete();
}
