// ---------------------------------------------------------------------------
// AUTO-GENERATED CONTENT: everything below was generated by Claude Sonnet 5
// (Anthropic), an LLM coding assistant, under end-to-end development
// supervision - it was generated as prompted, code was not adjusted or
// written. Review before relying on it.
// ---------------------------------------------------------------------------
// Fixture developed for/used to verify parse-dxil - see docs/ir-format.md.
// ---------------------------------------------------------------------------
#pragma once
#include "../structs/Records.hlsl"

[Shader("node")]
[NodeLaunch("thread")]
void GenerateNode(
    ThreadNodeInputRecord<WorkItemRecord> inputRecord,

    [MaxRecords(1)]
    [NodeID("CollectNode")]
    NodeOutput<ResultRecord> resultOutput
)
{
    ThreadNodeOutputRecords<ResultRecord> result = resultOutput.GetThreadNodeOutputRecords(1);
    result.OutputComplete();
}
