// ---------------------------------------------------------------------------
// AUTO-GENERATED CONTENT: everything below was generated by Claude Sonnet 5
// (Anthropic), an LLM coding assistant, under end-to-end development
// supervision - it was generated as prompted, code was not adjusted or
// written. Review before relying on it.
// ---------------------------------------------------------------------------
#pragma once
#include "../structs/Records.hlsl"

// Graph entry point: hands a single dispatch record to CullNode.
[Shader("node")]
[NodeIsProgramEntry]
[NodeLaunch("broadcasting")]
[NodeDispatchGrid(1, 1, 1)]
[NumThreads(1, 1, 1)]
void EntryNode(
    uint dtid : SV_DispatchThreadID,

    [MaxRecords(1)]
    [NodeID("CullNode")]
    NodeOutput<DispatchRecord> dispatchOutput
)
{
    ThreadNodeOutputRecords<DispatchRecord> rec = dispatchOutput.GetThreadNodeOutputRecords(1);
    rec.OutputComplete();
}
