// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

const { pumlEscape } = require('../text-utils');
const { resolveExpr, annotateExpr, tripleTotalSuffix, exprTotalSuffix, greyOnes, annotateTripleForDisplay } = require('../constants');
const {
    SHORT_META,
    SHORT_RECORD_OUT_COUNT,
    SHORT_RECORD_IN_COUNT,
    RECORD_IN_NAMES_ENABLED,
    RECORD_OUT_NAMES_ENABLED,
    GLOBAL_LIST_ENABLED,
} = require('../options');

function launchStereotype(node) {
    if (!node.launchMode) return 'unknown';
    return node.launchMode.toLowerCase();
}

function groupDir(node) {
    return node.group || 'other';
}

function compactArgs(s) {
    return s.replace(/\s+/g, ' ').trim();
}

// Whether a node's dispatch grid is a fixed, statically-known single thread
// group (kind: 'single'), or can/does expand to more than one thread group
// per invocation (kind: 'multi'). Drives the dashed-border visual.
function classifyGrid(n, table) {
    if (n.maxDispatchGrid) {
        // NodeMaxDispatchGrid means the actual grid is set at runtime via
        // SV_DispatchGrid on the output record - always treat as variable.
        const raw = compactArgs(n.maxDispatchGrid);
        return {
            kind: 'multi',
            text: `Grid: ≤(${annotateTripleForDisplay(raw, table)}) dynamic${tripleTotalSuffix(raw, table)}`,
        };
    }
    if (n.dispatchGrid) {
        const parts = n.dispatchGrid.split(',').map((p) => p.trim());
        const isFixedOne = parts.length === 3 && parts.every((p) => p === '1');
        if (isFixedOne) return { kind: 'single', text: 'Grid: (1,1,1)' };
        const raw = compactArgs(n.dispatchGrid);
        return {
            kind: 'multi',
            text: `Grid: (${annotateTripleForDisplay(raw, table)})${tripleTotalSuffix(raw, table)}`,
        };
    }
    if (n.launchMode === 'thread') return { kind: 'single', text: 'Grid: 1 thread/record' };
    if (n.launchMode === 'coalescing') return { kind: 'single', text: 'Grid: 1 group (coalesced)' };
    return { kind: 'single', text: 'Grid: n/a' };
}

function buildThreadsText(n, table) {
    if (!n.numThreads) return 'Threads: n/a';
    const raw = compactArgs(n.numThreads);
    return `Threads: (${annotateTripleForDisplay(raw, table)})${tripleTotalSuffix(raw, table)}`;
}

function recordTypeSpan(recordType, theme) {
    const typeText = recordType ? `<<${recordType}>>` : '<<empty>>';
    return `<color:${theme.recordHighlight}>${typeText}</color>`;
}

// The actual computed record count for an edge, e.g. "(192)" for
// "1 * 32 * CUBOID_FACES" - a resolved number rather than the raw formula,
// since this sits right next to the record type rather than on its own line.
// "(?)" when it doesn't fully resolve.
function edgeRecordCountBraces(maxRecordsRaw, table) {
    if (!maxRecordsRaw) return '';
    const resolved = resolveExpr(maxRecordsRaw, table);
    return resolved !== null ? ` (${resolved})` : ' (?)';
}

// PlantUML's creole formatting tags don't carry across an embedded line
// break within one label string - each visual line needs its own complete
// <i><size:...>...</size></i> pair, or the dangling closing tags on a later
// line render as literal text instead of being consumed.
function smallItalicLine(text) {
    return `<i><size:10>${text}</size></i>`;
}

// The "(...)" count shown after a Record in/out entry: normally the full
// formula plus " = <value>" (e.g. "(1 * 32 * CUBOID_FACES (6) = 192)"); in
// short mode, just the resolved number ("(192)"), falling back to the full
// formula (without "=", since it's not resolvable) if it can't be resolved.
function recordCountBraces(maxRecordsRaw, table, shortMode) {
    if (!maxRecordsRaw) return '';
    if (shortMode) {
        const resolved = resolveExpr(maxRecordsRaw, table);
        return resolved !== null ? ` (${resolved})` : ` (${annotateExpr(maxRecordsRaw, table)})`;
    }
    return ` (${annotateExpr(maxRecordsRaw, table)}${exprTotalSuffix(maxRecordsRaw, table)})`;
}

function outputRecordCountBraces(maxRecordsRaw, table) {
    return recordCountBraces(maxRecordsRaw, table, SHORT_RECORD_OUT_COUNT);
}

function inputRecordCountBraces(maxRecordsRaw, table) {
    return recordCountBraces(maxRecordsRaw, table, SHORT_RECORD_IN_COUNT);
}

// The record type that triggers this node ("kicks it off"), i.e. its own
// input record - not to be confused with the records it emits (listed
// separately by buildOutputRecordsLines). Only GroupNodeInputRecords/
// RWGroupNodeInputRecords (coalescing launch) can ever receive more than one
// record per invocation, so the record count is only shown for those.
// The global resources (root descriptors, StructuredBuffers, etc.) this
// node's HLSL body references, one line per global - "just above" Record
// in:/Record out: in the label. Leads with the identifier and register slot
// (colored via globalHighlight, matching that global's own box) since those
// are what actually distinguish one global from another; the value type
// trails in grey guillemets, de-emphasized by color alone (not also nested
// to a smaller <size>) since on its own it's rarely distinctive (several
// globals here share `float3`/`uint3`) - see the PlantUML server crash note
// below for why the size isn't also nested down. Already in slot order
// (globalsBySlot in main() sorts once, n.globalsUsed inherits that order).
//
// A <size:N> nested inside another <size:M> here, combined with enough
// surrounding label complexity (many Record in/out lines plus a doc
// comment), was found to make the public PlantUML server return an empty
// text/plain response instead of an image for that one node - reproducibly,
// but only past a certain accumulated complexity, so it went unnoticed until
// a node with a comment *and* several globals/records collided. Root cause
// unconfirmed (not a local syntax error - the .puml is well-formed HLSL/tag
// nesting), presumably a server-side text-layout bug. Do not reintroduce
// nested <size> tags in a node label without re-testing a real multi-field
// node (e.g. BuildingMassEmitNode, which has both a comment and globals)
// against the actual server - a small isolated repro is not enough to prove
// it's safe, since the bug only shows up at accumulated complexity.
function buildGlobalsUsedLines(n, globalsIndex, theme) {
    if (!GLOBAL_LIST_ENABLED) return null;
    if (!n.globalsUsed || n.globalsUsed.length === 0) return null;
    const valueLines = n.globalsUsed.map((name) => {
        const g = globalsIndex.get(name);
        const identSpan = `<color:${theme.globalHighlight}>${pumlEscape(g.name)}</color>`;
        const regText = `${g.regType}${g.regSlot}`;
        const typeSpan = g.valueType ? ` <color:${theme.greyOne}><<${pumlEscape(g.valueType)}>></color>` : '';
        return smallItalicLine(`  ${identSpan} (${regText})${typeSpan}`);
    });
    return [smallItalicLine('Globals used:'), ...valueLines].join('\\n');
}

function buildInputRecordLine(n, table, theme) {
    const input = n.inputs && n.inputs[0];
    if (!input) return null;

    const canReceiveMultiple = input.recordKind === 'GroupNodeInputRecords' || input.recordKind === 'RWGroupNodeInputRecords';
    let value = '';
    if (RECORD_IN_NAMES_ENABLED && input.varName) value += `${pumlEscape(input.varName)} `;
    value += recordTypeSpan(input.recordType, theme);
    if (canReceiveMultiple && input.maxRecords) {
        value += inputRecordCountBraces(input.maxRecords, table);
    }
    return [smallItalicLine('Record in:'), smallItalicLine(`  ${value}`)].join('\\n');
}

// Every record type this node emits (one line per NodeOutput/EmptyNodeOutput
// parameter, in declaration order - not deduplicated by type, since distinct
// output params can carry distinct MaxRecords budgets even for the same
// record type). Mesh-shader out indices/vertices/primitives don't count
// (those aren't work-graph records), so mesh leaf nodes show no Record out.
function buildOutputRecordsLines(n, table, theme) {
    if (!n.outputs || n.outputs.length === 0) return null;
    const valueLines = n.outputs.map((out) => {
        let value = '';
        if (RECORD_OUT_NAMES_ENABLED && out.varName) value += `${pumlEscape(out.varName)} `;
        value += recordTypeSpan(out.recordType, theme) + outputRecordCountBraces(out.maxRecords, table);
        return smallItalicLine(`  ${value}`);
    });
    return [smallItalicLine('Record out:'), ...valueLines].join('\\n');
}

// --short-meta variant of the depth/grid/threads block: everything on one
// smaller-font line, dropping Grid: for launch modes that can never
// configure it (coalescing is always exactly one group; thread is always
// exactly one thread per record - neither ever carries a NodeDispatchGrid/
// NodeMaxDispatchGrid attribute) and Threads: for thread launch specifically
// (coalescing's NumThreads is real and meaningful, e.g. COMPACTING_THREADS).
function buildShortMetaLine(n, grid, table, theme) {
    const stereo = launchStereotype(n);
    const dropGrid = stereo === 'coalescing' || stereo === 'thread';
    const dropThreads = stereo === 'thread';

    const parts = [`Depth: ${n.depth == null ? '?' : n.depth}`];
    if (!dropGrid) parts.push(greyOnes(pumlEscape(grid.text), theme.greyOne));
    if (!dropThreads) parts.push(greyOnes(pumlEscape(buildThreadsText(n, table)), theme.greyOne));
    return `<i><size:9>${parts.join(' | ')}</size></i>`;
}

// Launch mode is already conveyed by the rectangle's fill color (see the
// <<broadcasting>>/<<coalescing>>/<<thread>>/<<mesh>> skinparams below), so
// the name itself carries no redundant bracketed tag. depth/grid/thread are
// spelled out (shortest-path depth from an entry node first, then grid,
// since those are what actually vary between broadcasting nodes), in a
// smaller italic font with a blank line of margin separating it from the
// name (or, under --short-meta, collapsed into a single even-smaller line -
// see buildShortMetaLine()). Default "1" axes are greyed out. Any doc
// comment written directly above [Shader("node")] in the source follows,
// separated from the thread readout by a blank line, in an even smaller
// font since it's supplementary prose rather than a data readout.
function buildLabel(n, grid, table, theme, globalsIndex) {
    const nameLine = `<color:${theme.nodeNameHighlight}>${pumlEscape(n.id)}</color>`;

    let meta;
    if (SHORT_META) {
        meta = buildShortMetaLine(n, grid, table, theme);
    } else {
        // depth is a real count, never a placeholder "unused axis" default, so
        // it's deliberately excluded from greyOnes() - a depth of 1 is meaningful.
        const depthLine = `<i><size:10>Depth: ${n.depth == null ? '?' : n.depth}</size></i>`;
        const greyedLines = [grid.text, buildThreadsText(n, table)].map(
            (m) => `<i><size:10>${greyOnes(pumlEscape(m), theme.greyOne)}</size></i>`
        );
        meta = [depthLine, ...greyedLines].join('\\n');
    }
    let label = `${nameLine}\\n\\n${meta}`;

    const recordBlock = [
        buildGlobalsUsedLines(n, globalsIndex, theme),
        buildInputRecordLine(n, table, theme),
        buildOutputRecordsLines(n, table, theme),
    ]
        .filter(Boolean)
        .join('\\n');
    if (recordBlock) {
        label += `\\n\\n${recordBlock}`;
    }

    if (n.comment) {
        const commentText = n.comment
            .split('\n')
            .map((l) => `<size:9>${pumlEscape(l)}</size>`)
            .join('\\n');
        label += `\\n\\n${commentText}`;
    }
    if (n.functionName !== n.id) {
        label += `\\n<size:10>(fn: ${pumlEscape(n.functionName)})</size>`;
    }
    return label;
}

module.exports = {
    launchStereotype,
    groupDir,
    compactArgs,
    classifyGrid,
    buildThreadsText,
    recordTypeSpan,
    edgeRecordCountBraces,
    smallItalicLine,
    recordCountBraces,
    outputRecordCountBraces,
    inputRecordCountBraces,
    buildGlobalsUsedLines,
    buildInputRecordLine,
    buildOutputRecordsLines,
    buildShortMetaLine,
    buildLabel,
};
