// ---------------------------------------------------------------------------
// AUTO-GENERATED CONTENT: everything below was generated by Claude Sonnet 5
// (Anthropic), an LLM coding assistant, under end-to-end development
// supervision - it was generated as prompted, code was not adjusted or
// written. Review before relying on it.
// ---------------------------------------------------------------------------
#ifndef SIMPLE_PIPELINE_STRUCTS_RECORDS_HLSL
#define SIMPLE_PIPELINE_STRUCTS_RECORDS_HLSL

// Emitted by EntryNode, one record per unit of work.
struct WorkItemRecord
{
    uint itemId;
};

// Emitted by GenerateNode, gathered by CollectNode.
struct ResultRecord
{
    float value;
};

#endif
