// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// Constant resolution: #define / static const scanned the same way
// parse-source's own constants.js does, but from dxc's dx.source.contents
// debug info (every original, pre-preprocessor source file it embedded -
// already read once for extractLeadingComment()/original-attrs.js, see
// original-attrs.js's header comment) instead of walking the filesystem -
// so a `[MaxRecords(1 * 32 * CUBOID_FACES)]` resolves CUBOID_FACES even
// though parse-dxil never touches the original project tree itself.
//
// Kept as parse-dxil's own copy rather than importing parse-source/
// constants.js, matching this codebase's existing per-parser duplication
// (e.g. NODE_IO_KINDS in dxil-metadata.js) - each parser is meant to stand
// alone. Only the actual resolution algorithm (resolveExpr/
// resolveIdentifier/annotateExpr) is shared, via ../common/expr-resolve.js.
// ---------------------------------------------------------------------------

const { resolveExpr, resolveIdentifier, annotateExpr } = require('../common/expr-resolve');

// Comment stripping just thorough enough for #define/const scanning - block
// and line comments only, no string-literal awareness needed (these
// declarations never contain one).
function stripComments(text) {
    return text.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/.*$/gm, '');
}

// sourceFiles: the Map<path, content> from dxil-metadata.js's
// getSourceFiles() - every file dxc embedded, not just the one containing
// the node function being resolved (a constant can be declared in a
// utilities/ or structs/ file the node's own file merely #includes).
function collectConstants(sourceFiles) {
    const table = new Map();
    for (const content of sourceFiles.values()) {
        const stripped = stripComments(content);

        const defineRe = /^[ \t]*#define[ \t]+([A-Za-z_]\w*)[ \t]+(.+?)[ \t]*$/gm;
        let m;
        while ((m = defineRe.exec(stripped)) !== null) {
            table.set(m[1], m[2].trim());
        }

        const constRe = /static\s+const\s+[\w:<>]+\s+([A-Za-z_]\w*)\s*=\s*([^;]+);/g;
        while ((m = constRe.exec(stripped)) !== null) {
            table.set(m[1], m[2].trim());
        }
    }
    return table;
}

module.exports = { collectConstants, resolveExpr, resolveIdentifier, annotateExpr };
