// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM generated by iteratively
// prompt-review cycling the result. None of the code or any of the
// documentation was written by hand. REVIEW THE CODE AND ITS BEHAVIOR BEFORE
// RELYING ON IT.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// Per-node dataflow over the compiled DXIL function body: which record fields
// a node reads and writes, which resource fields/elements it touches, and
// where each value comes from. A value's "sources" are propagated through
// every SSA instruction (arithmetic, casts, select, phi, extractvalue, dx.op
// math) to a fixed point; memory is tracked per local/groupshared object
// (coarse: one source set per alloca). Source kinds:
//   in:<Type>.<field>      a field of this node's input record
//   buf:<resource>.<field> a field (or [constIndex]) of a resource element
//   sv:<SV_name>.<axis>    a thread/group id system value
//   const:<n>              a literal stored directly
//   local                  something only visible through local memory
// Sinks recorded: resource index operands, resource store values, output
// record field stores, and output allocation counts. Conservative: a source
// reached only through control flow (a branch condition) is not a source.
// ---------------------------------------------------------------------------

const SV_OPS = { 93: 'SV_DispatchThreadID', 94: 'SV_GroupID', 95: 'SV_GroupThreadID', 96: 'SV_GroupIndex' };
const AXES = ['x', 'y', 'z'];
const BUFFER_OPS = {
    rawBufferLoad: { kind: 'read', index: 1, offset: 2 },
    bufferLoad: { kind: 'read', index: 1, offset: 2 },
    rawBufferStore: { kind: 'write', index: 1, offset: 2, values: [3, 4, 5, 6] },
    bufferStore: { kind: 'write', index: 1, offset: 2, values: [3, 4, 5, 6] },
    atomicBinOp: { kind: 'atomic', index: 1, offset: 2, values: [5] }, // index/offset read specially below
    atomicCompareExchange: { kind: 'atomic', index: 1, offset: 2, values: [5] },
};
const ATOMIC_OPS = ['add', 'and', 'or', 'xor', 'imin', 'imax', 'umin', 'umax', 'exchange'];

// Top-level comma split of a call's argument list, e.g. "i32 139, %dx.types.Handle %5, i32 %6".
function splitArgs(s) {
    const out = [];
    let depth = 0, cur = '';
    for (const ch of s) {
        if ('({['.includes(ch)) depth++;
        if (')}]'.includes(ch)) depth--;
        if (ch === ',' && depth === 0) { out.push(cur.trim()); cur = ''; } else cur += ch;
    }
    if (cur.trim()) out.push(cur.trim());
    return out;
}
const refsIn = (s) => [...s.matchAll(/%[\w.$"\\-]+/g)].map((m) => m[0]).filter((r) => !/^%(dx|struct|class|"|hostlayout)/.test(r));
const argValue = (a) => (a ? a.split(/\s+/).pop() : null);
const isConst = (v) => v != null && /^-?\d+$/.test(v);
function constLabel(v) {
    if (/^0x[0-9A-Fa-f]{16}$/.test(v)) {
        const d = Buffer.from(v.slice(2), 'hex').readDoubleBE(0);
        return `const:${Number(d.toPrecision(6))}`;
    }
    if (/^-?[\d.]+e[+-]\d+$/.test(v)) return `const:${Number(Number(v).toPrecision(6))}`;
    return `const:${v}`;
}

// recordLayouts: { Type: {fields:[...]} } (debug info). llvmStructs: Map llvmName -> element count.
function fieldPath(typeName, indices, recordLayouts) {
    const parts = [];
    let t = recordLayouts[typeName];
    for (let i = 0; i < indices.length && t; i++) {
        const f = t.fields[Number(indices[i])];
        if (!f || !isConst(indices[i])) { parts.push(`#${indices[i]}`); break; }
        parts.push(f.name);
        let rest = indices.slice(i + 1);
        // array dimensions, then (for vectors, which LLVM lowers to arrays) one component index
        for (const dim of f.arrayDims || []) {
            if (!rest.length) break;
            parts[parts.length - 1] += `[${isConst(rest[0]) ? rest[0] : '*'}]`;
            rest = rest.slice(1);
            i++;
        }
        if (f.structType) { t = recordLayouts[f.structType]; continue; }
        if (rest.length && /\d$/.test(f.type)) { parts[parts.length - 1] += `.${AXES[Number(rest[0])] || rest[0]}`; i++; }
        break;
    }
    return parts.join('.');
}

// Field of a buffer element at a constant byte offset (rawBufferLoad/Store elementOffset).
function fieldAtOffset(typeName, offset, recordLayouts) {
    const t = recordLayouts[typeName];
    if (!t) return null;
    for (const f of t.fields) {
        if (offset < f.offsetBytes || offset >= f.offsetBytes + f.sizeBytes) continue;
        const inner = offset - f.offsetBytes;
        if (f.structType && !(f.arrayDims || []).length) {
            const sub = fieldAtOffset(f.structType, inner, recordLayouts);
            return sub ? `${f.name}.${sub}` : f.name;
        }
        if ((f.arrayDims || []).length) {
            const elem = f.sizeBytes / f.arrayDims.reduce((a, b) => a * b, 1);
            return `${f.name}[${Math.floor(inner / elem)}]`;
        }
        return f.name;
    }
    return null;
}

function analyseFunction(body, ctx) {
    const { handleGlobal, resourceElementType, recordLayouts, inputTypes, outputTypes, outputTargets } = ctx;
    const lines = body.split('\n').map((l) => l.replace(/,\s*!dbg.*$/, '').replace(/\s*;.*$/, '').trim()).filter(Boolean);

    const src = new Map(); // SSA name -> Set(source)
    const ptr = new Map(); // SSA pointer name -> { kind: 'in'|'out'|'mem', type, idx, output, base, path }
    const recHandle = new Map(); // record handle -> { kind: 'in', index } | { kind: 'out', output }
    const nodeHandleOut = new Map(); // node output handle -> output index
    const mem = new Map(); // memory object -> Set(source)
    const result = { inputs: {}, outputs: {}, resources: {}, allocations: {} };
    const add = (set, items) => { let c = false; for (const x of items) if (!set.has(x)) { set.add(x); c = true; } return c; };
    const sourcesOf = (v) => (isConst(v) ? new Set([`const:${v}`]) : src.get(v) || new Set());
    const resEntry = (r) => (result.resources[r] = result.resources[r] || { read: false, write: false, atomic: false, fields: {}, constIndices: {}, indexedBy: {}, valuesFrom: [], atomicOps: [] });
    const bump = (obj, key, kind) => { (obj[key] = obj[key] || new Set()).add(kind); };

    let changed = true;
    for (let pass = 0; changed && pass < 50; pass++) {
        changed = false;
        for (const line of lines) {
            const def = line.match(/^(%[\w.$"\\-]+)\s*=\s*(.*)$/);
            const lhs = def ? def[1] : null;
            const rhs = def ? def[2] : line;
            const setSrc = (items) => {
                if (!lhs) return;
                if (!src.has(lhs)) src.set(lhs, new Set());
                if (add(src.get(lhs), items)) changed = true;
            };
            let m;
            if ((m = rhs.match(/@dx\.op\.(\w+?)(?:\.[\w.]+)?\((.*)\)\s*$/))) {
                const op = m[1];
                const args = splitArgs(m[2]);
                if (SV_OPS[Number(argValue(args[0]))] && /^(threadId|groupId|threadIdInGroup|flattenedThreadIdInGroup)$/.test(op)) {
                    const axis = op === 'flattenedThreadIdInGroup' ? '' : `.${AXES[Number(argValue(args[1]))] || '?'}`;
                    setSrc([`sv:${SV_OPS[Number(argValue(args[0]))]}${axis}`]);
                } else if (op === 'createNodeOutputHandle') {
                    nodeHandleOut.set(lhs, Number(argValue(args[1])));
                } else if (op === 'annotateNodeHandle' && nodeHandleOut.has(argValue(args[1]))) {
                    nodeHandleOut.set(lhs, nodeHandleOut.get(argValue(args[1])));
                } else if (op === 'createNodeInputRecordHandle') {
                    recHandle.set(lhs, { kind: 'in', index: Number(argValue(args[1])) });
                } else if (op === 'allocateNodeOutputRecords') {
                    const out = nodeHandleOut.get(argValue(args[1]));
                    if (out != null) {
                        recHandle.set(lhs, { kind: 'out', output: out });
                        const a = (result.allocations[out] = result.allocations[out] || new Set());
                        add(a, sourcesOf(argValue(args[2])));
                    }
                } else if (op === 'annotateNodeRecordHandle' && recHandle.has(argValue(args[1]))) {
                    recHandle.set(lhs, recHandle.get(argValue(args[1])));
                } else if (op === 'getNodeRecordPtr' && recHandle.has(argValue(args[1]))) {
                    const h = recHandle.get(argValue(args[1]));
                    ptr.set(lhs, h.kind === 'in' ? { kind: 'in', type: inputTypes[h.index] } : { kind: 'out', type: outputTypes[h.output], output: h.output });
                } else if (BUFFER_OPS[op]) {
                    const spec = BUFFER_OPS[op];
                    const res = handleGlobal.get(argValue(args[1])); // every buffer op takes its handle as argument 1
                    if (!res) continue;
                    const e = resEntry(res);
                    e[spec.kind] = true;
                    const idxArg = op === 'atomicBinOp' ? argValue(args[3]) : argValue(args[spec.index + 1]);
                    const offArg = op === 'atomicBinOp' ? argValue(args[4]) : argValue(args[spec.offset + 1]);
                    const elemType = resourceElementType[res];
                    let field = null;
                    if (isConst(offArg) && recordLayouts[elemType]) field = fieldAtOffset(elemType, Number(offArg), recordLayouts);
                    else if (isConst(idxArg) && !recordLayouts[elemType]) {
                        field = `[${idxArg}]`;
                        bump(e.constIndices, idxArg, spec.kind);
                    }
                    if (!field && recordLayouts[elemType]) field = '(dynamic offset)';
                    if (field) bump(e.fields, field, spec.kind);
                    for (const s of sourcesOf(idxArg)) if (!s.startsWith('const:')) bump(e.indexedBy, s, spec.kind);
                    if (op === 'atomicBinOp') {
                        const code = Number(argValue(args[2]));
                        if (ATOMIC_OPS[code] && !e.atomicOps.includes(ATOMIC_OPS[code])) e.atomicOps.push(ATOMIC_OPS[code]);
                    }
                    if (spec.values) {
                        for (const i of spec.values) for (const s of sourcesOf(argValue(args[i + 1]))) if (!e.valuesFrom.includes(s)) e.valuesFrom.push(s);
                    }
                    if (spec.kind !== 'write') setSrc([`buf:${res}${field ? (field.startsWith('[') ? field : `.${field}`) : ''}`]);
                } else {
                    setSrc([...new Set(refsIn(m[2]).flatMap((r) => [...(src.get(r) || [])]))]);
                }
                continue;
            }
            if ((m = rhs.match(/^getelementptr (?:inbounds )?(.*)$/))) {
                const args = splitArgs(m[1]); // [elementType, "<type>* %base", idx...]
                const base = argValue(args[1]);
                const idx = args.slice(2).map(argValue);
                const b = ptr.get(base);
                if (b && (b.kind === 'in' || b.kind === 'out')) {
                    ptr.set(lhs, { ...b, path: fieldPath(b.type, idx.slice(1), recordLayouts) });
                } else {
                    ptr.set(lhs, { kind: 'mem', base: b && b.kind === 'mem' ? b.base : base });
                }
                continue;
            }
            if ((m = rhs.match(/^alloca /))) {
                ptr.set(lhs, { kind: 'mem', base: lhs });
                continue;
            }
            if ((m = rhs.match(/^load (.*)$/))) {
                const addr = argValue(splitArgs(m[1])[1]); // "load <type>, <type>* %ptr, align N"
                m = [null, addr];
                const p = ptr.get(addr);
                if (p && p.kind === 'in') {
                    (result.inputs[p.type] = result.inputs[p.type] || new Set()).add(p.path);
                    setSrc([`in:${p.type}.${p.path}`]);
                } else if (p && p.kind === 'mem') {
                    setSrc([...(mem.get(p.base) || []), 'local']);
                } else if (m[1].startsWith('@') && !/dx\.types\.Handle|hostlayout|class\./.test(rhs)) {
                    setSrc([...(mem.get(m[1]) || []), 'local']);
                }
                continue;
            }
            if ((m = line.match(/^store (.*)$/))) {
                const sargs = splitArgs(m[1]); // "store <type> <value>, <type>* %ptr, align N"
                m = [null, argValue(sargs[0]), argValue(sargs[1])];
                const val = m[1];
                const p = ptr.get(m[2]) || (m[2].startsWith('@') ? { kind: 'mem', base: m[2] } : null);
                const vs = /^[%]/.test(val) ? sourcesOf(val) : new Set([constLabel(val)]);
                if (p && p.kind === 'out') {
                    const o = (result.outputs[p.output] = result.outputs[p.output] || {});
                    const f = (o[p.path] = o[p.path] || new Set());
                    if (add(f, vs.size ? vs : ['local'])) changed = true;
                } else if (p && p.kind === 'mem') {
                    if (!mem.has(p.base)) mem.set(p.base, new Set());
                    if (add(mem.get(p.base), vs)) changed = true;
                }
                continue;
            }
            if (lhs && /^(add|sub|mul|udiv|sdiv|urem|srem|shl|lshr|ashr|and|or|xor|fadd|fsub|fmul|fdiv|frem|icmp|fcmp|zext|sext|trunc|fptoui|fptosi|uitofp|sitofp|fpext|fptrunc|bitcast|select|phi|extractvalue|insertvalue|extractelement|insertelement|shufflevector|call)\b/.test(rhs)) {
                setSrc([...new Set(refsIn(rhs).flatMap((r) => [...(src.get(r) || [])]))]);
            }
        }
    }

    // Plain JSON; 'local' is dropped wherever a real source is also known.
    const clean = (set) => {
        const arr = [...set].sort();
        return arr.length > 1 ? arr.filter((s) => s !== 'local') : arr;
    };
    const setMap = (o) => Object.fromEntries(Object.entries(o).map(([k, v]) => [k, [...v].sort()]));
    return {
        inputFieldsRead: Object.fromEntries(Object.entries(result.inputs).map(([t, s]) => [t, [...s].sort()])),
        outputFieldsWritten: Object.fromEntries(
            Object.entries(result.outputs).map(([o, fields]) => [o, { target: outputTargets[o], recordType: outputTypes[o], fields: Object.fromEntries(Object.entries(fields).map(([f, s]) => [f, clean(s)])) }])
        ),
        outputAllocationSources: Object.fromEntries(Object.entries(result.allocations).map(([o, s]) => [o, clean(s)])),
        resources: Object.fromEntries(
            Object.entries(result.resources).map(([r, e]) => [r, {
                access: ['read', 'write', 'atomic'].filter((k) => e[k]),
                fields: setMap(e.fields),
                constIndices: setMap(e.constIndices),
                indexedBy: setMap(e.indexedBy),
                valuesFrom: e.valuesFrom.filter((s) => s !== 'local' || e.valuesFrom.length === 1).sort(),
                atomicOps: e.atomicOps,
            }])
        ),
    };
}

// Handle SSA values -> resource name, following load @global -> createHandleForLib -> annotateHandle (and phi/select).
function handleMap(body, resources) {
    const byMangled = new Map();
    for (const r of resources || []) if (r.globalVariable) byMangled.set(r.globalVariable, r.name || r.globalVariable);
    const map = new Map();
    for (let pass = 0; pass < 3; pass++) {
        for (const line of body.split('\n')) {
            const m = line.match(/^\s*(%[\w.$"\\-]+)\s*=\s*(load|call|phi|select)\s+%dx\.types\.Handle\b(.*)$/);
            if (!m) continue;
            const g = m[3].match(/@"([^"]+)"/);
            if (g && byMangled.has(g[1])) { map.set(m[1], byMangled.get(g[1])); continue; }
            for (const r of refsIn(m[3])) if (map.has(r)) { map.set(m[1], map.get(r)); break; }
        }
    }
    return map;
}

module.exports = { analyseFunction, handleMap, fieldPath, fieldAtOffset };
