// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// LLVM metadata text parser: just enough of the grammar dxc's -Fc emits to
// walk `!N = !{...}` tuples and `!N = !DIXxx(key: val, ...)` debug-info
// nodes. Not a general LLVM IR parser - ported from the experimental spike's
// tools/parse-workgraph.js, see experimental/README.md for the full
// verification history behind this approach.
// ---------------------------------------------------------------------------

const fs = require('fs');

function splitTopLevel(s) {
    const parts = [];
    let depth = 0;
    let cur = '';
    let inStr = false;
    for (let i = 0; i < s.length; i++) {
        const c = s[i];
        if (inStr) {
            cur += c;
            if (c === '"') inStr = false;
            continue;
        }
        if (c === '"') {
            inStr = true;
            cur += c;
            continue;
        }
        if (c === '{' || c === '(') depth++;
        if (c === '}' || c === ')') depth--;
        if (c === ',' && depth === 0) {
            parts.push(cur.trim());
            cur = '';
            continue;
        }
        cur += c;
    }
    if (cur.trim().length) parts.push(cur.trim());
    return parts;
}

// LLVM metadata strings escape every special/non-ASCII byte as \XX (hex);
// there's never a literal unescaped `"` inside one, so a plain scan for the
// closing quote is safe.
function decodeLLVMString(inner) {
    const bytes = [];
    for (let i = 0; i < inner.length; i++) {
        if (inner[i] === '\\' && /^[0-9A-Fa-f]{2}/.test(inner.slice(i + 1, i + 3))) {
            bytes.push(parseInt(inner.slice(i + 1, i + 3), 16));
            i += 2;
        } else {
            bytes.push(inner.charCodeAt(i));
        }
    }
    return Buffer.from(bytes).toString('utf8');
}

function parseElement(tok) {
    tok = tok.trim();
    if (tok === 'null') return null;
    if (tok === 'true') return true;
    if (tok === 'false') return false;
    let m;
    if ((m = tok.match(/^!(\d+)$/))) return { $ref: Number(m[1]) };
    if ((m = tok.match(/^i\d+\s+(-?\d+|true|false)$/))) {
        if (m[1] === 'true') return true;
        if (m[1] === 'false') return false;
        return Number(m[1]);
    }
    if ((m = tok.match(/^!"([^"]*)"$/))) return decodeLLVMString(m[1]);
    if ((m = tok.match(/^"([^"]*)"$/))) return decodeLLVMString(m[1]);
    if (/^-?\d+$/.test(tok)) return Number(tok);
    // Global/function references: plain `@Name` for unmangled names (HLSL
    // node function names), or `@"Mangled\01Name@@..."` for anything MSVC
    // name-mangling produced (resource globals - `?`/`@` in the mangled
    // name require LLVM's quoted-identifier syntax), which can itself be
    // wrapped in a `bitcast (... to ...)` constant expression. Search
    // rather than anchor, since bitcast wrapping means the reference isn't
    // necessarily at the start of the token.
    // Deliberately NOT decoded (unlike !"..." string metadata elsewhere):
    // this raw form (e.g. literal `\01?itemMeta@@...`) is exactly what
    // recurs verbatim at each reference site in the disassembly text
    // (declaration, every createHandleForLib call site), which is what
    // findGlobalsUsed() text-matches against - decoding here would break
    // that match for no benefit, since this value is never shown to a user
    // directly (paramKind/recordType/name from debug info cover display).
    if ((m = tok.match(/@"([^"]*)"/))) return { $func: m[1] };
    if ((m = tok.match(/@([\w.$?]+)/))) return { $func: m[1] };
    if (/^[A-Za-z_][\w]*$/.test(tok)) return tok; // bare enum-like identifier (DW_TAG_*, DIFlag* etc.)
    return { $raw: tok };
}

function parseRHS(rhs) {
    rhs = rhs.trim();
    if (rhs.startsWith('distinct ')) rhs = rhs.slice('distinct '.length).trim();
    if (rhs.startsWith('!{') && rhs.endsWith('}')) {
        return { $tuple: splitTopLevel(rhs.slice(2, -1)).map(parseElement) };
    }
    const m = rhs.match(/^!(DI\w+)\((.*)\)$/s);
    if (m) {
        const fields = { $kind: m[1] };
        for (const pair of splitTopLevel(m[2])) {
            const idx = pair.indexOf(':');
            if (idx === -1) continue;
            fields[pair.slice(0, idx).trim()] = parseElement(pair.slice(idx + 1).trim());
        }
        return fields;
    }
    return { $raw: rhs };
}

function loadDisassembly(filePath) {
    const text = fs.readFileSync(filePath, 'utf8');
    const rawMap = new Map();
    const named = new Map();
    for (const line of text.split(/\r?\n/)) {
        let m = line.match(/^!(\d+) = (.*)$/);
        if (m) {
            rawMap.set(Number(m[1]), m[2]);
            continue;
        }
        m = line.match(/^!([A-Za-z][\w.]*) = !\{(.*)\}$/);
        if (m) {
            named.set(
                m[1],
                splitTopLevel(m[2]).map((t) => {
                    const mm = t.match(/^!(\d+)$/);
                    return mm ? Number(mm[1]) : null;
                })
            );
        }
    }
    return { rawMap, named, text };
}

// ---------------------------------------------------------------------------
// Deep resolver: !N refs -> fully resolved values, memoized, with a
// call-stack (not visited-set) cycle guard so legitimately shared/deduped
// nodes (very common in this format) aren't misflagged.
// ---------------------------------------------------------------------------

function makeResolver(rawMap) {
    const cache = new Map();
    const resolving = new Set();

    function resolveDeep(v) {
        if (v === null || typeof v !== 'object') return v;
        if (Array.isArray(v)) return v.map(resolveDeep);
        if ('$ref' in v) return resolveId(v.$ref);
        if ('$tuple' in v) return v.$tuple.map(resolveDeep);
        if ('$kind' in v) {
            const out = { $kind: v.$kind };
            for (const k of Object.keys(v)) if (k !== '$kind') out[k] = resolveDeep(v[k]);
            return out;
        }
        return v; // $func / $raw / already-plain values
    }

    function resolveId(id) {
        if (cache.has(id)) return cache.get(id);
        if (resolving.has(id)) return { $cycle: id };
        if (!rawMap.has(id)) return { $missing: id };
        resolving.add(id);
        const deep = resolveDeep(parseRHS(rawMap.get(id)));
        resolving.delete(id);
        cache.set(id, deep);
        return deep;
    }

    return resolveId;
}

module.exports = {
    splitTopLevel,
    decodeLLVMString,
    parseElement,
    parseRHS,
    loadDisassembly,
    makeResolver,
};
