// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// `hlsl-workgraph-diagram parse-dxil [entryHLSLFile] [outJsonFile]`
//
// Compiles entryHLSLFile with dxc (-T lib_6_8 -Zi -Qembed_debug) and reads
// the work-graph structure back out of the compiled DXIL metadata and debug
// info - resolved #defines, dead-code elimination, and real compile errors
// all come for free from using an actual compiler, at the cost of needing
// dxc.exe itself (see "hlsl-workgraph-diagram setup-dxil"). Writes the same
// shared IR (see ../common/ir.js) parse-source does, for build-puml to
// consume. See docs/ir-format.md for exactly which IR fields this parser
// can't fill yet.
// ---------------------------------------------------------------------------

const path = require('path');

const { parseArgs } = require('../common/cli-args');
const { writeIrFile } = require('../common/ir');
const { compileToDisassembly } = require('./run-dxc');
const { makeResolver } = require('./disassembly');
const { buildIr } = require('./to-ir');

function printHelp() {
    console.log(`Usage: hlsl-workgraph-diagram parse-dxil [entryHLSLFile] [outJsonFile] [options]

Compiles entryHLSLFile with dxc and writes the shared work-graph IR (see
docs/ir-format.md) as JSON to outJsonFile - input for
"hlsl-workgraph-diagram build-puml". Requires a dxc build; run
"hlsl-workgraph-diagram setup-dxil" first if you don't have one, or point
--dxc at your own.

Arguments:
  entryHLSLFile   The single HLSL file to compile - #include everything
                  else it needs (record structs, other node files) itself,
                  same as you'd hand dxc directly.
                  Default: WorkGraph.hlsl in the current working directory.
  outJsonFile     Path to write the IR JSON to. ".json" is appended
                  automatically if not already present.
                  Default: work-graph.ir.json, in the current working
                  directory.

Options:
  --define KEY=VALUE   Preprocessor define, passed to dxc as -D KEY=VALUE.
                        Repeatable.
  --entry NAME          Restrict the compile to this node's export (dxc
                        -exports NAME). Repeatable. Default: every
                        [Shader("node")] function dxc finds in the file.
  --dxc <path>          Path to a dxc.exe to use directly, instead of one
                        "setup-dxil" installed.
  --dxc-version <mesh|stable|experimental|version>
                        Use the dxc version "setup-dxil" installed under
                        this name/version (see "hlsl-workgraph-diagram
                        setup-dxil list"). Ignored if --dxc is also given.
  --keep-intermediate <dir>
                        Keep the compiled .dxil container and -Fc
                        disassembly in this directory instead of a
                        throwaway temp dir - useful for inspecting what
                        dxc actually produced.
  --help, -h, -?        Show this help text and exit.
`);
}

function run(argv) {
    const { values, positionals, help } = parseArgs(argv, [
        { name: 'define', flag: '--define', type: 'string', default: null, repeatable: true },
        { name: 'entry', flag: '--entry', type: 'string', default: null, repeatable: true },
        { name: 'dxc', flag: '--dxc', type: 'string', default: null },
        { name: 'dxcVersion', flag: '--dxc-version', type: 'string', default: null },
        { name: 'keepIntermediate', flag: '--keep-intermediate', type: 'string', default: null },
    ]);
    if (help) {
        printHelp();
        return;
    }

    // --define/--entry are repeatable, but the shared parser only keeps the
    // last value per flag - re-scan argv here for the repeatable ones.
    const defines = [];
    const exportNames = [];
    for (let i = 0; i < argv.length; i++) {
        if (argv[i] === '--define') defines.push(argv[++i]);
        else if (argv[i] === '--entry') exportNames.push(argv[++i]);
    }

    const entryFile = path.resolve(positionals[0] || path.join(process.cwd(), 'WorkGraph.hlsl'));
    const outArg = positionals[1] || 'work-graph.ir.json';
    const outFile = path.resolve(/\.json$/i.test(outArg) ? outArg : `${outArg}.json`);

    const { dis, dxcExe, dxcVersion } = compileToDisassembly(entryFile, {
        dxcPath: values.dxc,
        dxcVersion: values.dxcVersion,
        defines,
        exportNames,
        keepIntermediate: values.keepIntermediate ? path.resolve(values.keepIntermediate) : null,
    });
    const resolveId = makeResolver(dis.rawMap);

    const ir = buildIr(dis, resolveId, { entryFile, defines, exportNames, dxcExe, dxcVersion });
    console.error(`Parsed ${ir.nodes.length} node(s), ${ir.globals.length} global resource(s) from the compiled DXIL.`);

    writeIrFile(outFile, ir);
    console.error(`Wrote ${outFile}`);
}

module.exports = { run, printHelp };
