// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// `hlsl-workgraph-diagram parse-dxil [entryHLSLFile] [outJsonFile]`
//
// Compiles entryHLSLFile with dxc (-T lib_6_8 -Zi -Qembed_debug) and reads
// the work-graph structure back out of the compiled DXIL metadata and debug
// info - resolved #defines, dead-code elimination, and real compile errors
// all come for free from using an actual compiler, at the cost of needing
// dxc.exe itself (see "hlsl-workgraph-diagram setup-dxil"). Writes the same
// shared IR (see ../common/ir.js) parse-source does, for build-puml to
// consume. See docs/ir-format.md for exactly which IR fields this parser
// can't fill yet.
//
// --from-disassembly skips the compile step entirely (and so needs no dxc
// at all) - see the root README's "Generating the disassembly yourself"
// section for the exact dxc invocation to produce one by hand, e.g. on a
// machine this tool doesn't control, or with a dxc build/flags of your own.
// ---------------------------------------------------------------------------

const path = require('path');

const { parseArgs, VERBOSE_SPEC } = require('../common/cli-args');
const { createLogger } = require('../common/logger');
const { writeIrFile } = require('../common/ir');
const { compileToDisassembly } = require('./run-dxc');
const { loadDisassembly, makeResolver } = require('./disassembly');
const { buildIr } = require('./to-ir');

function printHelp() {
    console.log(`Usage: hlsl-workgraph-diagram parse-dxil [entryHLSLFile] [outJsonFile] [options]

Compiles entryHLSLFile with dxc and writes the shared work-graph IR (see
docs/ir-format.md) as JSON to outJsonFile - input for
"hlsl-workgraph-diagram build-puml". Requires a dxc build; run
"hlsl-workgraph-diagram setup-dxil" first if you don't have one, point --dxc/
--dxc-version at your own, or skip compiling entirely with
--from-disassembly (see the root README's "Generating the disassembly
yourself" section).

Arguments:
  entryHLSLFile   The single HLSL file to compile - #include everything
                  else it needs (record structs, other node files) itself,
                  same as you'd hand dxc directly. Ignored (but still
                  accepted, for the file's own text) if --from-disassembly
                  is given.
                  Default: WorkGraph.hlsl in the current working directory.
  outJsonFile     Path to write the IR JSON to. ".json" is appended
                  automatically if not already present.
                  Default: work-graph.ir.json, in the current working
                  directory.

Options:
  --define KEY=VALUE   Preprocessor define, passed to dxc as -D KEY=VALUE.
                        Repeatable.
  --entry NAME          Restrict the compile to this node's export (dxc
                        -exports NAME). Repeatable. Default: every
                        [Shader("node")] function dxc finds in the file.
  --dxc <path>          Path to a dxc.exe to use directly, instead of one
                        "setup-dxil" installed.
  --dxc-version <mesh|stable|experimental|version>
                        Use the dxc version "setup-dxil" installed under
                        this name/version (see "hlsl-workgraph-diagram
                        setup-dxil list"). Ignored if --dxc is also given.
  --keep-intermediate   Keep the compiled .dxil container and -Fc
                        disassembly (<stem>.dxil / <stem>.dis.ll) in the
                        current working directory instead of a throwaway
                        temp dir - e.g. to inspect them, or to reuse with
                        --from-disassembly later.
  --from-disassembly <file.dis.ll>
                        Skip locating/invoking dxc entirely and parse this
                        already-compiled -Fc disassembly directly (e.g. one
                        kept via --keep-intermediate, or generated by hand -
                        see the root README). entryHLSLFile/--define/
                        --entry/--dxc/--dxc-version/--keep-intermediate are
                        all ignored when this is given.
  --verbose, -v         Print each node/global found, and (unless
                        --from-disassembly skipped it) the exact dxc
                        command issued.
  --help, -h, -?        Show this help text and exit.
`);
}

function run(argv) {
    const { values, positionals, help } = parseArgs(argv, [
        { name: 'define', flag: '--define', type: 'string', default: null, repeatable: true },
        { name: 'entry', flag: '--entry', type: 'string', default: null, repeatable: true },
        { name: 'dxc', flag: '--dxc', type: 'string', default: null },
        { name: 'dxcVersion', flag: '--dxc-version', type: 'string', default: null },
        { name: 'keepIntermediate', flag: '--keep-intermediate', type: 'boolean', default: false },
        { name: 'fromDisassembly', flag: '--from-disassembly', type: 'string', default: null },
        VERBOSE_SPEC,
    ]);
    if (help) {
        printHelp();
        return;
    }
    const log = createLogger(values.verbose);

    // --define/--entry are repeatable, but the shared parser only keeps the
    // last value per flag - re-scan argv here for the repeatable ones.
    const defines = [];
    const exportNames = [];
    for (let i = 0; i < argv.length; i++) {
        if (argv[i] === '--define') defines.push(argv[++i]);
        else if (argv[i] === '--entry') exportNames.push(argv[++i]);
    }

    // entryHLSLFile is meaningless with --from-disassembly (there's no
    // compile step to feed it to), so the single positional given in that
    // mode is outJsonFile instead - not "entryHLSLFile with outJsonFile
    // defaulted".
    const entryFile = path.resolve(positionals[0] || path.join(process.cwd(), 'WorkGraph.hlsl'));
    const outArg = (values.fromDisassembly ? positionals[0] : positionals[1]) || 'work-graph.ir.json';
    const outFile = path.resolve(/\.json$/i.test(outArg) ? outArg : `${outArg}.json`);

    let dis, dxcExe, dxcVersion;
    if (values.fromDisassembly) {
        const disFile = path.resolve(values.fromDisassembly);
        log.info(`Reading disassembly directly from ${disFile} (skipping dxc).`);
        dis = loadDisassembly(disFile);
        dxcExe = null;
        dxcVersion = null;
    } else {
        log.verbose(`Entry file: ${entryFile}`);
        ({ dis, dxcExe, dxcVersion } = compileToDisassembly(entryFile, {
            dxcPath: values.dxc,
            dxcVersion: values.dxcVersion,
            defines,
            exportNames,
            keepIntermediate: values.keepIntermediate,
            logger: log,
        }));
        log.verbose(`dxc version: ${dxcVersion || '(unknown)'}`);
    }
    const resolveId = makeResolver(dis.rawMap);

    const ir = buildIr(dis, resolveId, {
        entryFile: values.fromDisassembly ? null : entryFile,
        fromDisassembly: values.fromDisassembly ? path.resolve(values.fromDisassembly) : null,
        defines,
        exportNames,
        dxcExe,
        dxcVersion,
    });
    for (const n of ir.nodes) {
        log.verbose(`  found node "${n.id}" (${n.functionName}): ${n.launchMode || 'unknown'} launch, ${n.inputs.length} input(s), ${n.outputs.length} output(s)`);
    }
    for (const g of ir.globals) {
        log.verbose(`  found global "${g.name}" (${g.kind || g.resourceClass}) at ${g.regType || '?'}${g.regSlot != null ? g.regSlot : '?'}`);
    }
    log.info(`Parsed ${ir.nodes.length} node(s), ${ir.globals.length} global resource(s) from the compiled DXIL.`);

    writeIrFile(outFile, ir);
    log.info(`Wrote ${outFile}`);
}

module.exports = { run, printHelp };
