// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// Original (un-evaluated) attribute expressions: dxc's metadata gives only
// the resolved value (e.g. NumThreads(32,1,1)) - not the original
// `[NumThreads(COLLECT_THREADS, 1, 1)]` text with the identifier still
// unexpanded. Recovered from the same dx.source.contents pre-preprocessor
// text dxil-metadata.js's extractLeadingComment() already uses: walk the
// leading `[...]` attribute block above a node function for its own
// attributes (NumThreads/NodeDispatchGrid/NodeMaxDispatchGrid), and the
// parameter list for each I/O parameter's MaxRecords. Pure text extraction
// - no evaluation, the resolved value always comes from the DXIL metadata
// parsed elsewhere.
// ---------------------------------------------------------------------------

const { NODE_IO_KIND_PATTERN } = require('./dxil-metadata');

// Same block extractLeadingComment() walks past without capturing - the
// contiguous `[...]` lines immediately above functionLine (1-based),
// joined with newlines so a multi-line attribute still reads as one block.
function extractLeadingAttributeBlock(fileContent, functionLine) {
    const lines = fileContent.split('\n');
    let i = functionLine - 1 - 1;
    const collected = [];
    while (i >= 0 && /^\s*\[.*\]\s*$/.test(lines[i])) {
        collected.unshift(lines[i]);
        i--;
    }
    return collected.join('\n');
}

// Finds `[AttrName(...)]` in `text` and returns its argument text verbatim
// (not evaluated), or null if the attribute isn't present. Balanced-paren
// rather than a naive non-greedy regex, since an argument can itself
// contain parens (e.g. `32 * (CUBOID_FACES + 1)`).
function extractAttrArgs(text, attrName) {
    const marker = `[${attrName}(`;
    const start = text.indexOf(marker);
    if (start === -1) return null;
    let i = start + marker.length;
    let depth = 1;
    const argStart = i;
    while (i < text.length && depth > 0) {
        if (text[i] === '(') depth++;
        else if (text[i] === ')') depth--;
        i++;
    }
    if (depth !== 0) return null;
    return text.slice(argStart, i - 1).trim();
}

// The function's full parameter-list text, parens included - from the `(`
// on functionLine (the DISubprogram line, which points at `void
// FuncName(`) through its balanced-paren close, however many lines that
// spans. Absolute-offset character scan.
function extractParamListText(fileContent, functionLine) {
    const lines = fileContent.split('\n');
    let offset = 0;
    for (let i = 0; i < functionLine - 1; i++) offset += lines[i].length + 1; // +1 for the '\n' split away
    const funcLineText = lines[functionLine - 1] || '';
    const openRel = funcLineText.indexOf('(');
    if (openRel === -1) return '';
    const openAbs = offset + openRel;
    let depth = 0;
    let i = openAbs;
    for (; i < fileContent.length; i++) {
        const c = fileContent[i];
        if (c === '(') depth++;
        else if (c === ')') {
            depth--;
            if (depth === 0) {
                i++;
                break;
            }
        }
    }
    return fileContent.slice(openAbs, i);
}

// Splits a parameter-list's inner text (outer parens already stripped) by
// top-level commas - tracks `<>`/`[]` depth (template args, attribute
// brackets) alongside `()`, since parameter declarations carry both.
function splitParamsTopLevel(s) {
    const parts = [];
    let depth = 0;
    let cur = '';
    for (let i = 0; i < s.length; i++) {
        const c = s[i];
        if ('([<'.includes(c)) depth++;
        if (')]>'.includes(c)) depth--;
        if (c === ',' && depth === 0) {
            parts.push(cur.trim());
            cur = '';
            continue;
        }
        cur += c;
    }
    if (cur.trim().length) parts.push(cur.trim());
    return parts;
}

// A parameter's own HLSL variable name - the trailing identifier once its
// leading `[Attr(...)]` blocks and its `Kind<Type>` are stripped, e.g.
// `[MaxRecords(64)]\n[NodeID("X")]\nNodeOutput<Foo> workItemOutput` ->
// "workItemOutput". dxc's debug info has no DW_TAG_arg_variable entries for
// node function parameters (only DW_TAG_auto_variable, for locals declared
// inside the body - confirmed against a real compile, see
// docs/ir-format.md), so this is recovered from the same pre-preprocessor
// source text as everything else here, not from debug info. Attribute
// blocks are stripped with a non-nesting `[^\]]*` match, safe for every
// attribute used on a parameter today (MaxRecords/NodeID/
// MaxRecordsSharedWith args never themselves contain a `]`).
function extractParamVarName(chunk) {
    const withoutAttrs = chunk.replace(/\[[^\]]*\]/g, ' ');
    const m = withoutAttrs.match(/([A-Za-z_]\w*)\s*$/);
    return m ? m[1] : null;
}

// Recovers a node's original, unevaluated attribute expressions: its own
// NumThreads/NodeDispatchGrid/NodeMaxDispatchGrid, and each I/O
// parameter's MaxRecords + variable name, in declaration order (so callers
// can zip against props.inputs/outputs the same way the debug-info
// parameter list is).
function extractOriginalAttrs(fileContent, functionLine) {
    const attrBlock = extractLeadingAttributeBlock(fileContent, functionLine);
    const nodeLevel = {
        numThreads: extractAttrArgs(attrBlock, 'NumThreads'),
        dispatchGrid: extractAttrArgs(attrBlock, 'NodeDispatchGrid'),
        maxDispatchGrid: extractAttrArgs(attrBlock, 'NodeMaxDispatchGrid'),
        maxRecursionDepth: extractAttrArgs(attrBlock, 'NodeMaxRecursionDepth'),
    };
    const paramListText = extractParamListText(fileContent, functionLine);
    const inner = paramListText.startsWith('(') && paramListText.endsWith(')') ? paramListText.slice(1, -1) : paramListText;
    const ioParamChunks = splitParamsTopLevel(inner).filter((chunk) => NODE_IO_KIND_PATTERN.test(chunk));
    const ioMaxRecords = ioParamChunks.map((chunk) => extractAttrArgs(chunk, 'MaxRecords'));
    const ioVarNames = ioParamChunks.map(extractParamVarName);
    return { nodeLevel, ioMaxRecords, ioVarNames };
}

module.exports = {
    extractLeadingAttributeBlock,
    extractAttrArgs,
    extractParamListText,
    splitParamsTopLevel,
    extractParamVarName,
    extractOriginalAttrs,
};
