// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM generated by iteratively
// prompt-review cycling the result. None of the code or any of the
// documentation was written by hand. REVIEW THE CODE AND ITS BEHAVIOR BEFORE
// RELYING ON IT.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// Record struct layouts for the IR's `recordTypes`, from three sources in the
// compiled container, each used for what only it knows:
//  - debug info (-Zi): field names, type names, byte offsets/sizes, array
//    counts, nested structs, declaring file/line;
//  - node metadata (NodeRecordType / NodeIOFlags): the SV_DispatchGrid field
//    (offset, component type, count) and record flags - compiler-verified;
//  - the embedded pre-preprocessor source (dx.source.contents): the text of a
//    field's `: SV_*` semantic and its comment, by the debug-info line number.
// Without -Zi only the node-metadata part is available.
// ---------------------------------------------------------------------------

// DXIL ComponentType enum (DxilConstants.h) - the SV_DispatchGrid entry's type.
const COMPONENT_TYPES = { 1: 'bool', 2: 'int16', 3: 'uint16', 4: 'int32', 5: 'uint32', 6: 'int64', 7: 'uint64', 8: 'float16', 9: 'float32', 10: 'float64' };

// NodeIOFlags bits (work-graphs spec, "NodeIOFlags and NodeIOKind encoding").
function decodeIOFlags(raw) {
    if (typeof raw !== 'number') return null;
    return {
        input: !!(raw & 0x1),
        output: !!(raw & 0x2),
        readWrite: !!(raw & 0x4),
        emptyRecord: !!(raw & 0x8),
        nodeArray: !!(raw & 0x10),
        granularity: { 0x20: 'thread', 0x40: 'group', 0x60: 'dispatch' }[raw & 0x60] || null,
        trackRWInputSharing: !!(raw & 0x100),
        globallyCoherent: !!(raw & 0x200),
    };
}

function decodeDispatchGridField(layoutRaw) {
    if (!Array.isArray(layoutRaw)) return null;
    for (let k = 0; k + 1 < layoutRaw.length; k += 2) {
        const v = layoutRaw[k + 1];
        if (layoutRaw[k] === 1 && Array.isArray(v) && v.length >= 3) {
            return { offsetBytes: v[0], componentType: COMPONENT_TYPES[v[1]] || `unknown(${v[1]})`, count: v[2] };
        }
    }
    return null;
}

// Every named struct definition with members, by name. The same name can be
// emitted more than once (per compile unit/usage); definitions are identical,
// so the first complete one wins.
function findStructTypes(rawMap, resolveId) {
    const byName = new Map();
    for (const [id, text] of rawMap) {
        const m = text.match(/^!DICompositeType\(tag: DW_TAG_structure_type, name: "([^"]+)".*elements: !\d+/);
        if (!m || byName.has(m[1])) continue;
        byName.set(m[1], resolveId(id));
    }
    return byName;
}

// Type label for a member's baseType: typedef names win (uint3, float4x4),
// arrays collect their dimensions, structs are reported for nesting.
function describeType(t) {
    const dims = [];
    let cur = t;
    for (let guard = 0; cur && guard < 16; guard++) {
        if (cur.$kind === 'DICompositeType' && cur.tag === 'DW_TAG_array_type') {
            for (const s of cur.elements || []) if (s && s.$kind === 'DISubrange') dims.push(s.count);
            cur = cur.baseType;
            continue;
        }
        if (cur.$kind === 'DIDerivedType' && cur.tag === 'DW_TAG_typedef') return { type: cur.name, dims, struct: null };
        if (cur.$kind === 'DIDerivedType' && /const|volatile/.test(cur.tag || '')) {
            cur = cur.baseType;
            continue;
        }
        if (cur.$kind === 'DIBasicType') return { type: cur.name === 'unsigned int' ? 'uint' : cur.name, dims, struct: null };
        if (cur.$kind === 'DICompositeType' && cur.tag === 'DW_TAG_structure_type') return { type: cur.name, dims, struct: cur.name };
        if (cur.$kind === 'DICompositeType') return { type: cur.name || '?', dims, struct: null };
        break;
    }
    return { type: '?', dims, struct: null };
}

function sourceLine(sourceFiles, normalizePath, file, line) {
    if (!file || !line) return null;
    const content = sourceFiles.get(normalizePath(file));
    return content ? content.split('\n')[line - 1] ?? null : null;
}

// Trailing `// ...` on the field's own line, else the contiguous `//` block right above it.
function fieldComment(sourceFiles, normalizePath, file, line) {
    const own = sourceLine(sourceFiles, normalizePath, file, line);
    if (own == null) return null;
    const trailing = own.match(/;\s*\/\/\s?(.*)$/);
    // A trailing comment belongs to the field only when the line declares just that one field.
    if (trailing) return (own.match(/;/g) || []).length === 1 ? trailing[1].trim() || null : null;
    const above = [];
    for (let l = line - 1; l >= 1; l--) {
        const text = sourceLine(sourceFiles, normalizePath, file, l);
        const m = text && text.match(/^\s*\/\/\s?(.*)$/);
        if (!m) break;
        above.unshift(m[1].trim());
    }
    return above.length ? above.join(' ') : null;
}

function layoutOf(struct, sourceFiles, normalizePath) {
    const file = struct.file && struct.file.filename;
    const fields = [];
    for (const e of struct.elements || []) {
        if (!e || e.$kind !== 'DIDerivedType' || e.tag !== 'DW_TAG_member') continue;
        const t = describeType(e.baseType);
        const memberFile = (e.file && e.file.filename) || file;
        const text = sourceLine(sourceFiles, normalizePath, memberFile, e.line);
        // Anchored on the field's own name: several fields can share one source line (a one-line struct).
        const semantic = text && text.match(new RegExp(`\\b${e.name}\\s*(?:\\[[^\\]]*\\]\\s*)*:\\s*(SV_\\w+)`));
        fields.push({
            name: e.name,
            type: t.type,
            arrayDims: t.dims,
            structType: t.struct,
            offsetBytes: (e.offset || 0) / 8,
            sizeBytes: (e.size || 0) / 8,
            line: e.line || null,
            sourceSemantic: semantic ? semantic[1] : null,
            comment: fieldComment(sourceFiles, normalizePath, memberFile, e.line),
        });
    }
    return { sizeBytes: (struct.size || 0) / 8, alignBytes: (struct.align || 0) / 8, file, line: struct.line || null, fields };
}

// Adds each struct in `names` plus every struct nested inside one, recursively.
function collectLayouts(names, structTypes, sourceFiles, normalizePath) {
    const out = {};
    const queue = [...names];
    while (queue.length) {
        const name = queue.shift();
        if (out[name] || !structTypes.has(name)) continue;
        out[name] = layoutOf(structTypes.get(name), sourceFiles, normalizePath);
        for (const f of out[name].fields) if (f.structType) queue.push(f.structType);
    }
    return out;
}

module.exports = { COMPONENT_TYPES, decodeIOFlags, decodeDispatchGridField, findStructTypes, describeType, collectLayouts };
