// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM generated by iteratively
// prompt-review cycling the result. None of the code or any of the
// documentation was written by hand. REVIEW THE CODE AND ITS BEHAVIOR BEFORE
// RELYING ON IT.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// Per-node resource access classification (read / write / atomic / query),
// from the compiled DXIL function body - what a multi-dispatch view needs to
// draw producer -> consumer edges *through* a UAV, which the record edges
// alone can't show.
//
// A resource reaches a dx.op call through an SSA chain of opaque handles:
//   %a = load %dx.types.Handle, %dx.types.Handle* @"<global>"
//   %b = call %dx.types.Handle @dx.op.createHandleForLib...(i32 160, %dx.types.Handle %a)
//   %c = call %dx.types.Handle @dx.op.annotateHandle(i32 216, %dx.types.Handle %b, ...)
//   ...  @dx.op.rawBufferStore.f32(i32 140, %dx.types.Handle %c, ...)
// Any instruction producing a %dx.types.Handle (load/call/phi/select) inherits
// the globals of every handle it references, so phi/select merges of two
// resources are attributed to both rather than lost.
// ---------------------------------------------------------------------------

// dx.op name (without overload suffix) -> access class. Atomics are their own
// class because they are both a read and a write, and in a work graph they
// are usually allocators/counters rather than payload.
const OP_ACCESS = {
    rawBufferLoad: 'read',
    bufferLoad: 'read',
    textureLoad: 'read',
    sample: 'read',
    sampleLevel: 'read',
    sampleGrad: 'read',
    sampleBias: 'read',
    sampleCmp: 'read',
    sampleCmpLevelZero: 'read',
    sampleCmpLevel: 'read',
    textureGather: 'read',
    textureGatherCmp: 'read',
    cbufferLoad: 'read',
    cbufferLoadLegacy: 'read',
    rawBufferStore: 'write',
    bufferStore: 'write',
    textureStore: 'write',
    textureStoreSample: 'write',
    atomicBinOp: 'atomic',
    atomicCompareExchange: 'atomic',
    bufferUpdateCounter: 'atomic',
    getDimensions: 'query',
};

// Ops that merely forward a handle - not an access in themselves.
const HANDLE_PLUMBING = new Set(['createHandleForLib', 'annotateHandle', 'createHandle', 'createHandleFromBinding', 'createHandleFromHeap']);

const DEF_RE = /^\s*(%[\w.$-]+)\s*=\s*(.*)$/;
const HANDLE_REF_RE = /%dx\.types\.Handle\s+(%[\w.$-]+)/g;
const OP_RE = /@dx\.op\.([A-Za-z0-9]+)/;

// resources: getResources() output ({ globalVariable, name, ... }).
// Returns { [resourceName]: { read, write, atomic, query, other: [opName] } }
// for every resource this function touches.
function findGlobalAccess(body, resources) {
    const byMangled = new Map();
    for (const r of resources || []) if (r.globalVariable) byMangled.set(r.globalVariable, r.name || r.globalVariable);

    const handleGlobals = new Map(); // SSA name -> Set(resource name)
    const access = {};
    const mark = (name, cls, op) => {
        const a = (access[name] = access[name] || { read: false, write: false, atomic: false, query: false, other: [] });
        if (cls) a[cls] = true;
        else if (!a.other.includes(op)) a.other.push(op);
    };
    const referencedGlobals = (text) => {
        const set = new Set();
        let m;
        HANDLE_REF_RE.lastIndex = 0;
        while ((m = HANDLE_REF_RE.exec(text))) {
            for (const g of handleGlobals.get(m[1]) || []) set.add(g);
        }
        return set;
    };

    for (const line of body.split('\n')) {
        const code = line.replace(/,\s*!dbg.*$/, '').replace(/;.*$/, '');
        const def = code.match(DEF_RE);
        const rhs = def ? def[2] : code;

        // A handle-typed definition: record which resources it stands for.
        if (def && /^(load|call|phi|select)\s+%dx\.types\.Handle\b/.test(rhs)) {
            const set = referencedGlobals(rhs);
            for (const m of rhs.matchAll(/@"([^"]+)"/g)) {
                if (byMangled.has(m[1])) set.add(byMangled.get(m[1]));
            }
            if (set.size) handleGlobals.set(def[1], set);
            const op = rhs.match(OP_RE);
            if (!op || HANDLE_PLUMBING.has(op[1])) continue;
        }

        const op = rhs.match(OP_RE);
        if (!op || HANDLE_PLUMBING.has(op[1])) continue;
        const globals = referencedGlobals(rhs);
        if (!globals.size) continue;
        const cls = OP_ACCESS[op[1]] || null;
        for (const g of globals) mark(g, cls, op[1]);
    }
    return access;
}

// Compact form for the IR: "read" | "write" | "read+write" | "atomic" | ...
function accessLabel(a) {
    const parts = [];
    if (a.read) parts.push('read');
    if (a.write) parts.push('write');
    if (a.atomic) parts.push('atomic');
    if (!parts.length && a.query) parts.push('query');
    for (const o of a.other) parts.push(o);
    return parts.join('+');
}

// Output-record allocation per node output (the MetadataIdx of
// createNodeOutputHandle is the index into the node's outputs list):
//   %h = call %dx.types.NodeHandle @dx.op.createNodeOutputHandle(i32 247, i32 <idx>)
//   %a = call %dx.types.NodeHandle @dx.op.annotateNodeHandle(i32 249, %dx.types.NodeHandle %h, ...)
//   ...  @dx.op.allocateNodeOutputRecords(i32 238, %dx.types.NodeHandle %a, i32 <count>, i1 <perThread>)
// Returns { [outputIdx]: { constCounts: number[], dynamicCount: number } }.
// An output whose every allocation is the constant 0 never produces a record,
// whatever its MaxRecords says - the edge exists in the graph but is dead.
function findOutputAllocations(body) {
    const handleOutput = new Map();
    const result = {};
    for (const line of body.split('\n')) {
        const code = line.replace(/,\s*!dbg.*$/, '').replace(/;.*$/, '');
        const def = code.match(DEF_RE);
        const rhs = def ? def[2] : code;
        let m;
        if (def && (m = rhs.match(/@dx\.op\.createNodeOutputHandle\(i32 \d+, i32 (\d+)\)/))) {
            handleOutput.set(def[1], Number(m[1]));
            continue;
        }
        if (def && /^(call|phi|select)\s+%dx\.types\.NodeHandle\b/.test(rhs)) {
            const ref = rhs.match(/%dx\.types\.NodeHandle\s+(%[\w.$-]+)/);
            if (ref && handleOutput.has(ref[1])) handleOutput.set(def[1], handleOutput.get(ref[1]));
            continue;
        }
        if ((m = rhs.match(/@dx\.op\.allocateNodeOutputRecords\(i32 \d+, %dx\.types\.NodeHandle (%[\w.$-]+), i32 ([^,]+),/))) {
            if (!handleOutput.has(m[1])) continue;
            const idx = handleOutput.get(m[1]);
            const r = (result[idx] = result[idx] || { constCounts: [], dynamicCount: 0 });
            if (/^-?\d+$/.test(m[2].trim())) r.constCounts.push(Number(m[2]));
            else r.dynamicCount++;
        }
    }
    return result;
}

// groupshared memory a node's function references, in bytes - the
// SharedMemorySize term of the spec's node output limits. groupshared
// variables are addrspace(3) globals; their LLVM type is sized here directly
// (scalars, vectors, arrays, and named structs from the module's type table).
const SCALAR_BYTES = { i1: 4, i8: 1, i16: 2, i32: 4, i64: 8, half: 2, float: 4, double: 8 };

function makeTypeSizer(disText) {
    const structs = new Map();
    for (const m of disText.matchAll(/^(%[\w."<>,\s$-]+?|%"[^"]+")\s*=\s*type\s*\{(.*)\}\s*$/gm)) {
        structs.set(m[1].trim(), m[2]);
    }
    const splitTop = (s) => {
        const out = [];
        let depth = 0, cur = '';
        for (const ch of s) {
            if ('[{<'.includes(ch)) depth++;
            if (']}>'.includes(ch)) depth--;
            if (ch === ',' && depth === 0) { out.push(cur.trim()); cur = ''; } else cur += ch;
        }
        if (cur.trim()) out.push(cur.trim());
        return out;
    };
    const size = (t) => {
        t = t.trim();
        if (SCALAR_BYTES[t]) return SCALAR_BYTES[t];
        let m;
        if ((m = t.match(/^\[(\d+) x (.*)\]$/))) return Number(m[1]) * size(m[2]);
        if ((m = t.match(/^<(\d+) x (.*)>$/))) return Number(m[1]) * size(m[2]);
        if ((m = t.match(/^\{(.*)\}$/))) return splitTop(m[1]).reduce((a, f) => a + size(f), 0);
        if (structs.has(t)) return splitTop(structs.get(t)).reduce((a, f) => a + size(f), 0);
        return NaN;
    };
    return size;
}

function findGroupSharedBytes(disText, body) {
    const size = makeTypeSizer(disText);
    let total = 0;
    for (const m of disText.matchAll(/^@("[^"]+"|[\w.$]+) = [^\n]*?addrspace\(3\) global (.+?), align \d+/gm)) {
        const name = m[1].replace(/^"|"$/g, '');
        if (body.includes(`@"${name}"`) || body.includes(`@${name}`)) total += size(m[2]);
    }
    return total;
}

module.exports = { OP_ACCESS, findGlobalAccess, accessLabel, findOutputAllocations, findGroupSharedBytes };
