// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// Locates and invokes dxc.exe (child_process, a Node builtin - no
// dependency added) to compile one HLSL file with `-T lib_6_8 -Zi
// -Qembed_debug`, producing the `-Fc` disassembly that disassembly.js
// parses. dxc.exe is a native Windows PE binary with no Linux build at any
// version checked (see experimental/README.md's "Known blocker" section) -
// this runs it directly on Windows, and best-effort through `wine`/`wine64`
// elsewhere if present.
// ---------------------------------------------------------------------------

const fs = require('fs');
const path = require('path');
const os = require('os');
const { execFileSync } = require('child_process');

const { dxcPathForVersion, resolvedAliasVersion } = require('../setup-dxil/paths');
const { NAMED_VARIANTS } = require('../setup-dxil/fetch');

// Plain, non-recursive text scan of just the entry file for the raw string
// `NodeLaunch("mesh")` - the same heuristic setup-dxil's fetch uses to pick
// a dxc build, kept in sync so parse-dxil looks in the same cache slot
// setup-dxil wrote to. Deliberately not #include-aware (a mesh node
// reached only through an #include won't be detected) - see
// experimental/README.md's "Separately:" note on this exact limitation.
function looksLikeMeshGraph(entryFile) {
    try {
        return /NodeLaunch\s*\(\s*"mesh"/.test(fs.readFileSync(entryFile, 'utf8'));
    } catch {
        return false;
    }
}

// Resolves "mesh"/"stable"/"experimental" (via setup-dxil's aliases.json -
// see ../setup-dxil/paths.js) or an exact version string to a dxc.exe path,
// requiring it already be installed (never hits the network itself - that's
// setup-dxil's job).
function resolveDxcVersionRef(versionRef) {
    let version = versionRef;
    if (NAMED_VARIANTS.includes(versionRef)) {
        version = resolvedAliasVersion(versionRef);
        if (!version) {
            throw new Error(`"${versionRef}" hasn't been installed yet - run "hlsl-workgraph-diagram setup-dxil ${versionRef}" first.`);
        }
    }
    const exe = dxcPathForVersion(version);
    if (!fs.existsSync(exe)) {
        throw new Error(`no dxc.exe found for version ${version} (looked at: ${exe}). Run "hlsl-workgraph-diagram setup-dxil ${version}" first.`);
    }
    return exe;
}

function locateDxc({ dxcPath, dxcVersion } = {}, entryFile) {
    if (dxcPath) {
        if (!fs.existsSync(dxcPath)) throw new Error(`--dxc path does not exist: ${dxcPath}`);
        return dxcPath;
    }
    if (dxcVersion) return resolveDxcVersionRef(dxcVersion);
    if (process.env.HLSL_WORKGRAPH_DXC) {
        const p = process.env.HLSL_WORKGRAPH_DXC;
        if (!fs.existsSync(p)) throw new Error(`HLSL_WORKGRAPH_DXC does not exist: ${p}`);
        return p;
    }
    const variant = looksLikeMeshGraph(entryFile) ? 'mesh' : 'stable';
    const version = resolvedAliasVersion(variant);
    if (!version) {
        throw new Error(
            `no dxc found for the "${variant}" build. Run "hlsl-workgraph-diagram setup-dxil ${variant}" first, ` +
                'or pass --dxc <path-to-dxc.exe>, --dxc-version <mesh|stable|experimental|version>, ' +
                'or set the HLSL_WORKGRAPH_DXC environment variable.'
        );
    }
    return dxcPathForVersion(version);
}

function runnerFor(dxcExe) {
    if (process.platform === 'win32' || path.extname(dxcExe).toLowerCase() !== '.exe') {
        return { cmd: dxcExe, prefixArgs: [] };
    }
    // Best-effort non-Windows path: dxc.exe has no native build, so try
    // wine/wine64 if present. Known to crash on some Wine builds against
    // this specific dxc PE's exception-unwind format (see
    // experimental/README.md's "Known blocker" section) - not a bug in
    // this tool, a Wine compatibility gap.
    for (const wine of ['wine64', 'wine']) {
        try {
            execFileSync(wine, ['--version'], { stdio: 'ignore' });
            return { cmd: wine, prefixArgs: [dxcExe] };
        } catch {
            // try the next candidate
        }
    }
    throw new Error(`dxc.exe is a Windows binary and neither wine64 nor wine was found on PATH to run it on ${process.platform}.`);
}

// Best-effort `dxc --version` capture, for the IR's generatorDetail (and
// from there, build-puml's legend provenance line) - works regardless of
// how dxc was located (explicit path, alias, or auto-detected), since it
// just asks the binary itself rather than trusting a cache directory name.
function getDxcVersionString(dxcExe) {
    try {
        const { cmd, prefixArgs } = runnerFor(dxcExe);
        const out = execFileSync(cmd, [...prefixArgs, '--version'], { encoding: 'utf8' });
        return out.split('\n')[0].trim() || null;
    } catch {
        return null;
    }
}

// Compiles entryFile and returns { dis, dxcExe, dxcVersion }, where `dis`
// is the parsed { rawMap, named, text } shape disassembly.js's
// loadDisassembly() produces. `defines`: array of "KEY=VALUE" strings.
// `exportNames`: array of node function names to restrict the compile to
// (dxc `-exports`), or empty for "every node in the file".
// `keepIntermediate`: directory to leave the compiled .dxil/.ll in for
// inspection, or null to use a throwaway temp dir cleaned up after.
function compileToDisassembly(entryFile, { dxcPath, dxcVersion, defines = [], exportNames = [], keepIntermediate = null } = {}) {
    const dxcExe = locateDxc({ dxcPath, dxcVersion }, entryFile);
    const dxcDir = path.dirname(dxcExe);
    const hasValidator = fs.existsSync(path.join(dxcDir, 'dxil.dll'));

    const workDir = keepIntermediate || fs.mkdtempSync(path.join(os.tmpdir(), 'hlsl-workgraph-dxil-'));
    fs.mkdirSync(workDir, { recursive: true });
    const stem = path.basename(entryFile).replace(/\.[^.]+$/, '');
    const dxilOut = path.join(workDir, `${stem}.dxil`);
    const disOut = path.join(workDir, `${stem}.dis.ll`);

    const args = ['-T', 'lib_6_8'];
    for (const name of exportNames) args.push('-exports', name);
    for (const d of defines) args.push('-D', d);
    args.push('-Zi', '-Qembed_debug');
    if (!hasValidator) args.push('-Vd');
    args.push('-Fo', dxilOut, '-Fc', disOut, entryFile);

    const { cmd, prefixArgs } = runnerFor(dxcExe);
    console.error(`+ ${[cmd, ...prefixArgs, ...args].join(' ')}`);
    execFileSync(cmd, [...prefixArgs, ...args], { stdio: 'inherit' });

    const { loadDisassembly } = require('./disassembly');
    const dis = loadDisassembly(disOut);

    if (!keepIntermediate) {
        fs.rmSync(workDir, { recursive: true, force: true });
    }
    return { dis, dxcExe, dxcVersion: getDxcVersionString(dxcExe) };
}

module.exports = { locateDxc, looksLikeMeshGraph, getDxcVersionString, compileToDisassembly };
