// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// Assembles the parsed DXIL metadata + debug info into the shared IR (see
// ../common/ir.js) - the same node/global shape parse-source produces, so
// build-puml never needs to know which parser an IR file came from. See
// docs/ir-format.md for the fields this parser can't fill (documented as
// null, not guessed).
// ---------------------------------------------------------------------------

const {
    decodeProps,
    getSubprogramsByFunctionName,
    getSourceFiles,
    normalizePath,
    extractLeadingComment,
    getResources,
    findGlobalsUsed,
} = require('./dxil-metadata');
const { extractOriginalAttrs } = require('./original-attrs');
const { collectConstants, annotateExpr } = require('./constants');

// A scalar { resolved, source } pair. `resolvedVal` is `undefined` when the
// DXIL metadata never carried this tag at all (attribute absent) -
// `null`/other falsy resolved values (e.g. maxRecursionDepth: 0) must stay
// distinguishable from that, hence the explicit undefined/null check rather
// than a truthiness check. `resolvedVal` itself always comes from the DXIL
// metadata (dxc's own compiled, canonical total) - `table` is only used to
// annotate `originalText`'s own identifiers with their individual values
// (see ../common/expr-resolve.js's annotateExpr), not to recompute the
// total independently.
function buildScalarField(resolvedVal, originalText, table = new Map()) {
    if (resolvedVal === undefined || resolvedVal === null) {
        return originalText != null ? { resolved: null, source: originalText } : null;
    }
    const same = originalText != null && originalText.replace(/\s+/g, '') === String(resolvedVal);
    if (same) return { resolved: resolvedVal, source: null };
    return { resolved: resolvedVal, source: originalText != null ? annotateExpr(originalText, table) : null };
}

// A triple { resolved: [...], source: [...] } pair, splitting the original
// comma-separated attribute text per-axis to match against each resolved
// number.
function buildTripleField(resolvedArr, originalCsv) {
    if (!Array.isArray(resolvedArr)) return null;
    const parts = originalCsv != null ? originalCsv.split(',').map((s) => s.trim()) : [];
    const source = resolvedArr.map((r, i) => {
        const p = parts[i];
        if (p == null) return null;
        return p.replace(/\s+/g, '') === String(r) ? null : p;
    });
    return { resolved: resolvedArr, source };
}

function resourceToIr(r) {
    return {
        name: r.name || r.globalVariable,
        resourceClass: r.resourceClass,
        // rw is derived, not literally read off an "RW" prefix the way
        // parse-source's text scan does: any resource compiled into the
        // UAV class is read-write by construction (that's what makes it a
        // UAV rather than an SRV), so resourceClass === 'UAV' is exactly
        // equivalent for every case this tool models (structured/raw/typed
        // buffers) - see docs/ir-format.md.
        rw: r.resourceClass === 'UAV',
        kind: r.kind,
        valueType: r.valueType,
        regType: r.regType,
        regSlot: r.regSlot,
        space: r.space,
        file: null, // not recoverable from !dx.resources - would need a debug-info cross-reference not yet implemented
    };
}

function buildIr(dis, resolveId, generatorDetail) {
    const subprogramsByName = getSubprogramsByFunctionName(resolveId, dis.named);
    const sourceFiles = getSourceFiles(resolveId, dis.named);
    const resources = getResources(resolveId, dis.named, dis.text);
    const constantsTable = collectConstants(sourceFiles);

    const nodes = [];
    for (const id of dis.named.get('dx.entryPoints') || []) {
        const ep = resolveId(id);
        const funcRef = ep[0];
        if (!funcRef || typeof funcRef !== 'object' || !funcRef.$func) continue; // skip the library-level null placeholder
        const funcName = funcRef.$func;
        const props = decodeProps(ep[4]);
        const debugInfo = subprogramsByName.get(funcName);

        let comment = null;
        let originalAttrs = null;
        if (debugInfo && debugInfo.file && debugInfo.line) {
            const content = sourceFiles.get(normalizePath(debugInfo.file));
            if (content) {
                comment = extractLeadingComment(content, debugInfo.line);
                originalAttrs = extractOriginalAttrs(content, debugInfo.line);
            }
        }
        const nl = originalAttrs ? originalAttrs.nodeLevel : {};

        // Effective graph id: a node's own [NodeID("X")] self-override
        // (DXIL tag 15 on the entry point itself) if present, else its
        // function name - matches parse-source's id convention exactly, so
        // producer -> consumer linkage (via linkedNodeID below) resolves
        // against the same identity space regardless of which parser ran.
        const nodeID = props.nodeID || null;
        const graphId = nodeID && nodeID.name ? nodeID.name : funcName;

        const numInputs = (props.inputs || []).length;
        const toParam = (rec, i, offset) => {
            const debugParam = debugInfo && debugInfo.params[offset + i];
            const originalMaxRecords = originalAttrs ? originalAttrs.ioMaxRecords[offset + i] : null;
            const varName = originalAttrs ? originalAttrs.ioVarNames[offset + i] : null;
            return {
                recordKind: debugParam ? debugParam.paramKind : null,
                recordType: debugParam ? debugParam.recordType : null,
                // Not in dxc's debug info (no DW_TAG_arg_variable for node
                // function params - see docs/ir-format.md) - recovered
                // instead from the same pre-preprocessor source text as
                // MaxRecords, via original-attrs.js's extractParamVarName().
                varName: varName || null,
                linkedNodeID: rec.linkedNodeID || null,
                maxRecords: buildScalarField(rec.maxRecords, originalMaxRecords, constantsTable),
                maxRecordsSharedWith: null, // DXIL tag unverified against a real compile - see docs/ir-format.md
                recordFields: debugParam ? debugParam.recordFields : null,
            };
        };

        nodes.push({
            id: graphId,
            nodeIdIndex: nodeID ? nodeID.index : null,
            functionName: funcName,
            group: deriveGroup(debugInfo && debugInfo.file),
            sourceFile: debugInfo ? debugInfo.file : null,
            sourceLine: debugInfo ? debugInfo.line : null,
            comment,
            isEntry: !!props.isProgramEntry,
            launchMode: props.nodeLaunchType ? props.nodeLaunchType.label : null,
            numThreads: buildTripleField(props.numThreads, nl.numThreads),
            dispatchGrid: buildTripleField(props.dispatchGrid, nl.dispatchGrid),
            maxDispatchGrid: buildTripleField(props.maxDispatchGrid, nl.maxDispatchGrid),
            maxRecursionDepth: buildScalarField(props.maxRecursionDepth, nl.maxRecursionDepth, constantsTable),
            outputTopology: null, // not currently parsed from this metadata - see docs/ir-format.md
            inputs: (props.inputs || []).map((rec, i) => toParam(rec, i, 0)),
            outputs: (props.outputs || []).map((rec, i) => toParam(rec, i, numInputs)),
            meshOutputs: [], // mesh out indices/vertices/primitives excluded, matching parse-source's own documented behavior
            globalsUsed: findGlobalsUsed(dis.text, funcName, resources),
        });
    }

    return {
        generator: 'parse-dxil',
        generatorDetail,
        nodes,
        globals: (resources || []).map(resourceToIr),
    };
}

// Derives a node's source-subdirectory "group" (matching parse-source's
// grouping, used to lay out the diagram into packages) from its debug-info
// file path, since parse-dxil doesn't scan a directory tree the way
// parse-source does - the nearest "nodes-*" path segment, if any.
function deriveGroup(filePath) {
    if (!filePath) return null;
    const m = filePath.replace(/\\/g, '/').match(/(?:^|\/)(nodes-[^/]+)\//);
    return m ? m[1] : null;
}

module.exports = { buildScalarField, buildTripleField, resourceToIr, deriveGroup, buildIr };
