// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// Assembles the parsed DXIL metadata + debug info into the shared IR (see
// ../common/ir.js) - the same node/global shape parse-source produces, so
// build-puml never needs to know which parser an IR file came from. See
// docs/ir-format.md for the fields this parser can't fill (documented as
// null, not guessed).
// ---------------------------------------------------------------------------

const {
    decodeProps,
    getSubprogramsByFunctionName,
    getSourceFiles,
    normalizePath,
    extractLeadingComment,
    getResources,
    findGlobalsUsed,
    findGlobalAccessForFunction,
} = require('./dxil-metadata');
const { accessLabel, findOutputAllocations, findGroupSharedBytes } = require('./resource-access');
const { decodeIOFlags, decodeDispatchGridField, findStructTypes, collectLayouts } = require('./record-layouts');
const { analyseFunction, handleMap } = require('./dataflow');
const { extractFunctionBody } = require('./dxil-metadata');
const { extractOriginalAttrs } = require('./original-attrs');
const { collectConstants, annotateExpr } = require('./constants');

// A scalar { resolved, source } pair. `resolvedVal` is `undefined` when the
// DXIL metadata never carried this tag at all (attribute absent) -
// `null`/other falsy resolved values (e.g. maxRecursionDepth: 0) must stay
// distinguishable from that, hence the explicit undefined/null check rather
// than a truthiness check. `resolvedVal` itself always comes from the DXIL
// metadata (dxc's own compiled, canonical total) - `table` is only used to
// annotate `originalText`'s own identifiers with their individual values
// (see ../common/expr-resolve.js's annotateExpr), not to recompute the
// total independently.
function buildScalarField(resolvedVal, originalText, table = new Map()) {
    if (resolvedVal === undefined || resolvedVal === null) {
        return originalText != null ? { resolved: null, source: originalText } : null;
    }
    const same = originalText != null && originalText.replace(/\s+/g, '') === String(resolvedVal);
    if (same) return { resolved: resolvedVal, source: null };
    return { resolved: resolvedVal, source: originalText != null ? annotateExpr(originalText, table) : null };
}

// A triple { resolved: [...], source: [...] } pair, splitting the original
// comma-separated attribute text per-axis to match against each resolved
// number.
function buildTripleField(resolvedArr, originalCsv) {
    if (!Array.isArray(resolvedArr)) return null;
    const parts = originalCsv != null ? originalCsv.split(',').map((s) => s.trim()) : [];
    const source = resolvedArr.map((r, i) => {
        const p = parts[i];
        if (p == null) return null;
        return p.replace(/\s+/g, '') === String(r) ? null : p;
    });
    return { resolved: resolvedArr, source };
}

function resourceToIr(r) {
    return {
        name: r.name || r.globalVariable,
        resourceClass: r.resourceClass,
        // rw is derived, not literally read off an "RW" prefix the way
        // parse-source's text scan does: any resource compiled into the
        // UAV class is read-write by construction (that's what makes it a
        // UAV rather than an SRV), so resourceClass === 'UAV' is exactly
        // equivalent for every case this tool models (structured/raw/typed
        // buffers) - see docs/ir-format.md.
        rw: r.resourceClass === 'UAV',
        kind: r.kind,
        valueType: r.valueType,
        regType: r.regType,
        regSlot: r.regSlot,
        space: r.space,
        globallyCoherent: r.globallyCoherent ?? null,
        hasCounter: r.hasCounter ?? null,
        rasterizerOrdered: r.rasterizerOrdered ?? null,
        file: null, // not recoverable from !dx.resources - would need a debug-info cross-reference not yet implemented
    };
}

function buildIr(dis, resolveId, generatorDetail) {
    const subprogramsByName = getSubprogramsByFunctionName(resolveId, dis.named);
    const sourceFiles = getSourceFiles(resolveId, dis.named);
    const resources = getResources(resolveId, dis.named, dis.text);
    const constantsTable = collectConstants(sourceFiles);

    const nodes = [];
    for (const id of dis.named.get('dx.entryPoints') || []) {
        const ep = resolveId(id);
        const funcRef = ep[0];
        if (!funcRef || typeof funcRef !== 'object' || !funcRef.$func) continue; // skip the library-level null placeholder
        const funcName = funcRef.$func;
        const props = decodeProps(ep[4]);
        const debugInfo = subprogramsByName.get(funcName);

        let comment = null;
        let originalAttrs = null;
        if (debugInfo && debugInfo.file && debugInfo.line) {
            const content = sourceFiles.get(normalizePath(debugInfo.file));
            if (content) {
                comment = extractLeadingComment(content, debugInfo.line);
                originalAttrs = extractOriginalAttrs(content, debugInfo.line);
            }
        }
        const nl = originalAttrs ? originalAttrs.nodeLevel : {};

        // Effective graph id: a node's own [NodeID("X")] self-override
        // (DXIL tag 15 on the entry point itself) if present, else its
        // function name - matches parse-source's id convention exactly, so
        // producer -> consumer linkage (via linkedNodeID below) resolves
        // against the same identity space regardless of which parser ran.
        const nodeID = props.nodeID || null;
        const graphId = nodeID && nodeID.name ? nodeID.name : funcName;

        const numInputs = (props.inputs || []).length;
        const allocations = findOutputAllocations(extractFunctionBody(dis.text, funcName));
        const toParam = (rec, i, offset, isOutput) => {
            const debugParam = debugInfo && debugInfo.params[offset + i];
            const originalMaxRecords = originalAttrs ? originalAttrs.ioMaxRecords[offset + i] : null;
            const varName = originalAttrs ? originalAttrs.ioVarNames[offset + i] : null;
            return {
                recordKind: debugParam ? debugParam.paramKind : null,
                recordType: debugParam ? debugParam.recordType : null,
                // Not in dxc's debug info (no DW_TAG_arg_variable for node
                // function params - see docs/ir-format.md) - recovered
                // instead from the same pre-preprocessor source text as
                // MaxRecords, via original-attrs.js's extractParamVarName().
                varName: varName || null,
                linkedNodeID: rec.linkedNodeID || null,
                maxRecords: buildScalarField(rec.maxRecords, originalMaxRecords, constantsTable),
                allocation: isOutput ? allocations[i] || { constCounts: [], dynamicCount: 0 } : undefined,
                ioFlags: decodeIOFlags(rec.ioFlagsRaw),
                dispatchGridField: decodeDispatchGridField(rec.recordLayoutRaw),
                recordSizeBytes: typeof rec.recordSizeBytes === 'number' ? rec.recordSizeBytes : null,
                recordAlignment: typeof rec.recordAlignment === 'number' ? rec.recordAlignment : null,
                maxRecordsSharedWith: null, // DXIL tag unverified against a real compile - see docs/ir-format.md
                recordFields: debugParam ? debugParam.recordFields : null,
            };
        };

        nodes.push({
            id: graphId,
            nodeIdIndex: nodeID ? nodeID.index : null,
            functionName: funcName,
            group: deriveGroup(debugInfo && debugInfo.file),
            sourceFile: debugInfo ? debugInfo.file : null,
            sourceLine: debugInfo ? debugInfo.line : null,
            comment,
            isEntry: !!props.isProgramEntry,
            launchMode: props.nodeLaunchType ? props.nodeLaunchType.label : null,
            numThreads: buildTripleField(props.numThreads, nl.numThreads),
            dispatchGrid: buildTripleField(props.dispatchGrid, nl.dispatchGrid),
            maxDispatchGrid: buildTripleField(props.maxDispatchGrid, nl.maxDispatchGrid),
            maxRecursionDepth: buildScalarField(props.maxRecursionDepth, nl.maxRecursionDepth, constantsTable),
            outputTopology: null, // not currently parsed from this metadata - see docs/ir-format.md
            inputs: (props.inputs || []).map((rec, i) => toParam(rec, i, 0)),
            outputs: (props.outputs || []).map((rec, i) => toParam(rec, i, numInputs, true)),
            meshOutputs: [], // mesh out indices/vertices/primitives excluded, matching parse-source's own documented behavior
            globalsUsed: findGlobalsUsed(dis.text, funcName, resources),
            groupSharedBytes: findGroupSharedBytes(dis.text, extractFunctionBody(dis.text, funcName)),
            globalAccess: Object.fromEntries(
                Object.entries(findGlobalAccessForFunction(dis.text, funcName, resources)).map(([k, v]) => [k, accessLabel(v)])
            ),
        });
    }

    const globals = (resources || []).map(resourceToIr);
    const structTypes = findStructTypes(dis.rawMap, resolveId);
    const allLayouts = collectLayouts([...structTypes.keys()], structTypes, sourceFiles, normalizePath);
    const resourceElementType = Object.fromEntries(globals.map((g) => [g.name, g.valueType]));
    for (const n of nodes) {
        const body = extractFunctionBody(dis.text, n.functionName);
        n.dataflow = analyseFunction(body, {
            handleGlobal: handleMap(body, resources),
            resourceElementType,
            recordLayouts: allLayouts,
            inputTypes: n.inputs.map((p) => p.recordType),
            outputTypes: n.outputs.map((p) => p.recordType),
            outputTargets: n.outputs.map((p) => (p.linkedNodeID ? p.linkedNodeID.name : null)),
        });
    }
    return {
        generator: 'parse-dxil',
        generatorDetail,
        nodes,
        globals,
        recordTypes: buildRecordTypes(nodes, globals, dis, resolveId, sourceFiles),
    };
}

// Every struct that crosses a node edge or is a UAV/SRV element type, plus the
// structs nested in them: layout from debug info, and how the graph uses it.
function buildRecordTypes(nodes, globals, dis, resolveId, sourceFiles) {
    const structTypes = findStructTypes(dis.rawMap, resolveId);
    const usage = new Map();
    const use = (name) => {
        if (!usage.has(name)) usage.set(name, { producers: [], consumers: [], cpuEntryInput: [], buffers: [], dxil: null });
        return usage.get(name);
    };
    for (const n of nodes) {
        for (const p of n.inputs) {
            if (!p.recordType) continue;
            const u = use(p.recordType);
            u.consumers.push(n.id);
            if (n.isEntry) u.cpuEntryInput.push(n.id);
            u.dxil = u.dxil || dxilRecordFacts(p);
            if (p.ioFlags) u.dxil.flagsByNode[n.id] = p.ioFlags;
        }
        for (const p of n.outputs) {
            if (!p.recordType) continue;
            const u = use(p.recordType);
            u.producers.push(n.id);
            u.dxil = u.dxil || dxilRecordFacts(p);
        }
    }
    for (const g of globals) {
        if (g.valueType && structTypes.has(g.valueType)) use(g.valueType).buffers.push(g.name);
    }
    const layouts = collectLayouts([...usage.keys()], structTypes, sourceFiles, normalizePath);
    const out = {};
    for (const [name, layout] of Object.entries(layouts)) {
        const u = usage.get(name) || { producers: [], consumers: [], cpuEntryInput: [], buffers: [], dxil: null };
        const roles = [];
        if (u.producers.length || u.consumers.length) roles.push('node-record');
        if (u.cpuEntryInput.length) roles.push('cpu-entry-record');
        if (u.buffers.length) roles.push('buffer-element');
        if (!roles.length) roles.push('nested');
        const dg = u.dxil && u.dxil.dispatchGridField;
        for (const f of layout.fields) {
            f.semantic = dg && f.offsetBytes === dg.offsetBytes ? 'SV_DispatchGrid' : f.sourceSemantic;
        }
        out[name] = { ...layout, roles, usage: { producers: [...new Set(u.producers)], consumers: [...new Set(u.consumers)], buffers: u.buffers }, dxil: u.dxil };
    }
    attachFieldDataflow(out, nodes, globals);
    return out;
}

// Per-field aggregation of every node's dataflow, keyed by the field's top-level
// name (array elements and vector components fold into their field):
//   readBy / writtenBy   node ids (node records) or node ids touching the buffer field
//   sources              where written values come from (in:/buf:/sv:/const:)
//   indexes              resources this field is used to index, directly (by a consumer)
//                        or via: another record field it is copied into
//   sizesOutputs         outputs whose allocation count depends on it
//   flowsTo              record/buffer fields its value is written into
function attachFieldDataflow(types, nodes, globals) {
    const top = (f) => f.replace(/\[[^\]]*\]/g, '').replace(/\.[xyzw]$/, '').split('.')[0];
    const fieldOf = (type, f) => (types[type] ? types[type].fields.find((x) => x.name === top(f)) : null);
    const newDf = () => ({ readBy: [], writtenBy: [], sources: [], indexes: [], sizesOutputs: [], flowsTo: [], controls: [] });
    // Every struct level along a field path ("metaData.vertex.offset" in FloorRecord also touches
    // BuildingMetaData.vertex and ArrayPointer.offset), so nested types get their own dataflow.
    const dfAll = (type, path) => {
        const out = [];
        let t = type;
        const segs = path.replace(/\[[^\]]*\]/g, '').split('.');
        for (const seg of segs) {
            const x = types[t] && types[t].fields.find((f) => f.name === seg);
            if (!x) break;
            out.push((x.dataflow = x.dataflow || newDf()));
            if (!x.structType) break;
            t = x.structType;
        }
        return out;
    };
    const df = (type, f) => dfAll(type, f)[0] || null;
    const push = (arr, v) => { if (!arr.some((a) => JSON.stringify(a) === JSON.stringify(v))) arr.push(v); };
    const parseSource = (s) => {
        let m;
        if ((m = s.match(/^in:(\w+)\.(.+)$/))) return { type: m[1], field: m[2] };
        if ((m = s.match(/^buf:(\w+)\.(.+)$/))) return { resource: m[1], field: m[2] };
        return null;
    };
    const elemType = Object.fromEntries(globals.map((g) => [g.name, g.valueType]));
    for (const n of nodes) {
        const d = n.dataflow;
        if (!d) continue;
        for (const [type, fields] of Object.entries(d.inputFieldsRead)) for (const f of fields) for (const x of dfAll(type, f)) push(x.readBy, n.id);
        for (const w of Object.values(d.outputFieldsWritten)) {
            for (const [f, sources] of Object.entries(w.fields)) {
                const xs = dfAll(w.recordType, f);
                if (!xs.length) continue;
                for (const x of xs) push(x.writtenBy, n.id);
                for (const s of sources) {
                    for (const x of xs) push(x.sources, s);
                    const from = parseSource(s);
                    const target = `${w.recordType}.${top(f)}`;
                    if (from && from.type) { const y = df(from.type, from.field); if (y) push(y.flowsTo, target); }
                    if (from && from.resource) { const y = df(elemType[from.resource], from.field); if (y) push(y.flowsTo, target); }
                }
            }
        }
        for (const [o, sources] of Object.entries(d.outputAllocationSources)) {
            for (const s of sources) {
                const from = parseSource(s);
                const xs = from ? (from.type ? dfAll(from.type, from.field) : dfAll(elemType[from.resource], from.field)) : [];
                for (const x of xs) push(x.sizesOutputs, { node: n.id, output: n.outputs[o] && n.outputs[o].linkedNodeID ? n.outputs[o].linkedNodeID.name : o });
            }
        }
        for (const s of d.controlSources || []) {
            const from = parseSource(s);
            const xs = from ? (from.type ? dfAll(from.type, from.field) : dfAll(elemType[from.resource], from.field)) : [];
            for (const x of xs) push(x.controls, n.id);
        }
        for (const [res, e] of Object.entries(d.resources)) {
            for (const [f, kinds] of Object.entries(e.fields)) {
                for (const x of dfAll(elemType[res], f)) {
                    if (kinds.includes('read') || kinds.includes('atomic')) push(x.readBy, n.id);
                    if (kinds.includes('write') || kinds.includes('atomic')) push(x.writtenBy, n.id);
                }
            }
            for (const s of Object.keys(e.indexedBy)) {
                const from = parseSource(s);
                const xs = from ? (from.type ? dfAll(from.type, from.field) : dfAll(elemType[from.resource], from.field)) : [];
                for (const x of xs) push(x.indexes, { resource: res, node: n.id, via: null });
            }
        }
    }
    // One level of composition: a field copied into a record field that indexes a resource indexes it too.
    for (const [type, t] of Object.entries(types)) {
        for (const f of t.fields) {
            if (!f.dataflow) continue;
            for (const target of f.dataflow.flowsTo) {
                const [tt, tf] = target.split('.');
                const y = fieldOf(tt, tf);
                if (!y || !y.dataflow) continue;
                for (const ix of y.dataflow.indexes.filter((i) => !i.via)) push(f.dataflow.indexes, { resource: ix.resource, node: ix.node, via: target });
            }
        }
    }
}

function dxilRecordFacts(p) {
    return { recordSizeBytes: p.recordSizeBytes, alignment: p.recordAlignment, dispatchGridField: p.dispatchGridField, flagsByNode: {} };
}

// Derives a node's source-subdirectory "group" (matching parse-source's
// grouping, used to lay out the diagram into packages) from its debug-info
// file path, since parse-dxil doesn't scan a directory tree the way
// parse-source does - the nearest "nodes-*" path segment, if any.
function deriveGroup(filePath) {
    if (!filePath) return null;
    const m = filePath.replace(/\\/g, '/').match(/(?:^|\/)(nodes-[^/]+)\//);
    return m ? m[1] : null;
}

module.exports = { buildScalarField, buildTripleField, resourceToIr, deriveGroup, buildIr };
