// ---------------------------------------------------------------------------
// AUTO-GENERATED CONTENT: everything below was generated by Claude Sonnet 5
// (Anthropic), an LLM coding assistant, under end-to-end development
// supervision - it was generated as prompted, code was not adjusted or
// written. Review before relying on it.
// ---------------------------------------------------------------------------
#ifndef SIMPLE_PIPELINE_NODES_COMPUTE_ENTRYNODE_HLSL
#define SIMPLE_PIPELINE_NODES_COMPUTE_ENTRYNODE_HLSL
#include "../structs/Records.hlsl"

// Graph entry point: a fixed 1x1x1 broadcasting dispatch that fans out
// up to 64 work items to GenerateNode.
[Shader("node")]
[NodeIsProgramEntry]
[NodeLaunch("broadcasting")]
[NodeDispatchGrid(1, 1, 1)]
[NumThreads(1, 1, 1)]
void EntryNode(
    uint dtid : SV_DispatchThreadID,

    [MaxRecords(64)]
    [NodeID("GenerateNode")]
    NodeOutput<WorkItemRecord> workItemOutput
)
{
    ThreadNodeOutputRecords<WorkItemRecord> items = workItemOutput.GetThreadNodeOutputRecords(64);
    items.OutputComplete();
}

#endif
