// ---------------------------------------------------------------------------
// AUTO-GENERATED CONTENT: everything below was generated by Claude Sonnet 5
// (Anthropic), an LLM coding assistant, under end-to-end development
// supervision - it was generated as prompted, code was not adjusted or
// written. Review before relying on it.
// ---------------------------------------------------------------------------
#ifndef SIMPLE_PIPELINE_NODES_COMPUTE_GENERATENODE_HLSL
#define SIMPLE_PIPELINE_NODES_COMPUTE_GENERATENODE_HLSL
#include "../structs/Records.hlsl"

// One thread per WorkItemRecord; produces a single ResultRecord for
// CollectNode to gather.
[Shader("node")]
[NodeLaunch("thread")]
void GenerateNode(
    ThreadNodeInputRecord<WorkItemRecord> inputRecord,

    [MaxRecords(1)]
    [NodeID("CollectNode")]
    NodeOutput<ResultRecord> resultOutput
)
{
    ThreadNodeOutputRecords<ResultRecord> result = resultOutput.GetThreadNodeOutputRecords(1);
    result.OutputComplete();
}

#endif
