// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// Attribute-list parsing: a run of [Foo] / [Foo(args)] blocks
// ---------------------------------------------------------------------------

function parseAttributeBlock(block) {
    // block includes the surrounding [ ]
    const inner = block.slice(1, -1).trim();
    const m = inner.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*(\((.*)\))?$/s);
    if (m) {
        return { name: m[1], args: m[3] !== undefined ? m[3].trim() : null };
    }
    return { name: inner, args: null };
}

// Parses a run of [Attr] blocks starting at position `pos` in `src`.
// Returns { attrs, nextPos } where nextPos points just past the last
// attribute block (and any following whitespace).
function parseAttributesAt(src, pos) {
    const attrs = [];
    let i = pos;
    for (;;) {
        while (i < src.length && /\s/.test(src[i])) i++;
        if (src[i] !== '[') break;
        let depth = 0;
        let j = i;
        for (; j < src.length; j++) {
            if (src[j] === '[') depth++;
            else if (src[j] === ']') {
                depth--;
                if (depth === 0) {
                    j++;
                    break;
                }
            }
        }
        attrs.push(parseAttributeBlock(src.slice(i, j)));
        i = j;
    }
    return { attrs, nextPos: i };
}

// Same idea, but the attribute run may appear anywhere at the front of a
// standalone parameter string (used for per-parameter attributes).
function parseLeadingAttributes(str) {
    const { attrs, nextPos } = parseAttributesAt(str, 0);
    return { attrs, rest: str.slice(nextPos).trim() };
}

function findAttr(attrs, name) {
    const lower = name.toLowerCase();
    return attrs.find((a) => a.name.toLowerCase() === lower);
}

module.exports = { parseAttributeBlock, parseAttributesAt, parseLeadingAttributes, findAttr };
