// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// Comment stripping (keeps string literals intact, preserves newlines so
// nothing downstream needs line numbers, but we don't rely on those anyway).
// Also returns a rawIndex[] map so a position in the stripped text can be
// traced back to its exact offset in the original source (used to find the
// doc comment immediately preceding a node's [Shader("node")] attribute).
// ---------------------------------------------------------------------------

function stripComments(src) {
    let out = '';
    const rawIndex = [];
    const push = (ch, idx) => {
        out += ch;
        rawIndex.push(idx);
    };
    let i = 0;
    const n = src.length;
    while (i < n) {
        const c = src[i];
        const c2 = src[i + 1];

        if (c === '"') {
            push(c, i);
            i++;
            while (i < n && src[i] !== '"') {
                if (src[i] === '\\' && i + 1 < n) {
                    push(src[i], i);
                    push(src[i + 1], i + 1);
                    i += 2;
                    continue;
                }
                push(src[i], i);
                i++;
            }
            if (i < n) {
                push(src[i], i);
                i++;
            }
            continue;
        }

        if (c === '/' && c2 === '/') {
            while (i < n && src[i] !== '\n') i++;
            continue;
        }

        if (c === '/' && c2 === '*') {
            i += 2;
            while (i < n && !(src[i] === '*' && src[i + 1] === '/')) {
                if (src[i] === '\n') push('\n', i);
                i++;
            }
            i += 2;
            continue;
        }

        push(c, i);
        i++;
    }
    return { text: out, rawIndex };
}

// ---------------------------------------------------------------------------
// Doc-comment extraction: the comment block (// run or /* */ block)
// immediately preceding a given raw-source position, with no blank line in
// between. Returns null if there isn't one.
// ---------------------------------------------------------------------------

function cleanBlockComment(inner) {
    return inner
        .split('\n')
        .map((l) => l.replace(/^[ \t]*\*[ \t]?/, '').trimEnd())
        .join('\n')
        .trim();
}

function extractPrecedingComment(raw, pos) {
    let end = pos;
    while (end > 0 && (raw[end - 1] === ' ' || raw[end - 1] === '\t')) end--;
    if (end > 0 && raw[end - 1] === '\n') end--;
    else return null; // attribute isn't alone on its own line
    if (end > 0 && raw[end - 1] === '\r') end--;

    if (raw.slice(Math.max(0, end - 2), end) === '*/') {
        const openIdx = raw.lastIndexOf('/*', end - 2);
        if (openIdx === -1) return null;
        return cleanBlockComment(raw.slice(openIdx + 2, end - 2)) || null;
    }

    const collected = [];
    let cursor = end;
    for (;;) {
        const lineStart = raw.lastIndexOf('\n', cursor - 1) + 1;
        const line = raw.slice(lineStart, cursor).replace(/\r$/, '');
        const trimmed = line.trim();
        if (!trimmed.startsWith('//')) break;
        collected.unshift(trimmed.replace(/^\/\/\s?/, ''));
        if (lineStart === 0) break;
        cursor = lineStart - 1;
    }
    return collected.length ? collected.join('\n').trim() : null;
}

module.exports = { stripComments, cleanBlockComment, extractPrecedingComment };
