// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// Constant resolution: #define / static const scanned across the *whole*
// shaders tree (not just nodes-*), so identifiers like CUBOID_FACES or
// MAX_GLYPHS_PER_RENDER_RECORD (declared in utilities/ or structs/) resolve.
//
// Pure resolution only - display formatting (annotated "IDENT (value)"
// text, short-mode, grey-ones, "= total" suffixes) lives in build-puml's
// node-label.js instead, operating on the {resolved, source} pairs to-ir.js
// builds from resolveExpr() below. Keeping resolution here and formatting
// there is what lets parse-dxil's IR (already-resolved by dxc, no table of
// its own) feed the exact same build-puml formatting code.
// ---------------------------------------------------------------------------

const fs = require('fs');
const { listHlslFiles } = require('./discovery');
const { stripComments } = require('./comments');

function collectConstants(rootDir) {
    const table = new Map();
    for (const file of listHlslFiles(rootDir)) {
        const stripped = stripComments(fs.readFileSync(file, 'utf8')).text;

        const defineRe = /^[ \t]*#define[ \t]+([A-Za-z_]\w*)[ \t]+(.+?)[ \t]*$/gm;
        let m;
        while ((m = defineRe.exec(stripped)) !== null) {
            table.set(m[1], m[2].trim());
        }

        const constRe = /static\s+const\s+[\w:<>]+\s+([A-Za-z_]\w*)\s*=\s*([^;]+);/g;
        while ((m = constRe.exec(stripped)) !== null) {
            table.set(m[1], m[2].trim());
        }
    }
    return table;
}

// Resolves an arithmetic expression to a number by iteratively substituting
// known identifiers, then safely evaluating the fully-numeric result.
// Returns null if any identifier stays unresolved or the result isn't a
// finite number.
function resolveExpr(expr, table) {
    let current = expr;
    for (let i = 0; i < 8; i++) {
        let changed = false;
        const next = current.replace(/\b[A-Za-z_]\w*\b/g, (id) => {
            if (table.has(id)) {
                changed = true;
                return `(${table.get(id)})`;
            }
            return id;
        });
        current = next;
        if (!changed) break;
    }

    const withoutHexLiterals = current.replace(/0[xX][0-9a-fA-F]+/g, '0');
    if (/[A-Za-z_]/.test(withoutHexLiterals)) return null; // still unresolved identifiers
    if (!/[0-9]/.test(current)) return null;
    if (!/^[\s0-9+\-*/().xXa-fA-F]+$/.test(current)) return null; // safety whitelist

    try {
        // eslint-disable-next-line no-new-func
        const val = Function(`"use strict"; return (${current});`)();
        return typeof val === 'number' && Number.isFinite(val) ? val : null;
    } catch {
        return null;
    }
}

module.exports = { collectConstants, resolveExpr };
