// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// Constant resolution: #define / static const scanned across the *whole*
// shaders tree (not just nodes-*), so identifiers like CUBOID_FACES or
// MAX_GLYPHS_PER_RENDER_RECORD (declared in utilities/ or structs/) resolve.
//
// Resolution (resolveExpr/resolveIdentifier/annotateExpr, generator-agnostic
// - see ../common/expr-resolve.js) happens here, at parse time, into to-ir.js's
// {resolved, source} pairs - source already carries any identifier's own
// value baked in as "IDENT (value)" via annotateExpr(). Remaining display
// formatting (short-mode, grey-ones, the "= total" suffix for a genuine
// multi-factor product) lives in build-puml's node-label.js, working only
// off that pair - which is what lets parse-dxil's IR (its own constants.js
// builds an equivalent table from dxc's embedded source debug info, not a
// filesystem scan) feed the exact same build-puml formatting code.
// ---------------------------------------------------------------------------

const fs = require('fs');
const { listHlslFiles } = require('./discovery');
const { stripComments } = require('./comments');
const { resolveExpr, resolveIdentifier, annotateExpr } = require('../common/expr-resolve');

function collectConstants(rootDir) {
    const table = new Map();
    for (const file of listHlslFiles(rootDir)) {
        const stripped = stripComments(fs.readFileSync(file, 'utf8')).text;

        const defineRe = /^[ \t]*#define[ \t]+([A-Za-z_]\w*)[ \t]+(.+?)[ \t]*$/gm;
        let m;
        while ((m = defineRe.exec(stripped)) !== null) {
            table.set(m[1], m[2].trim());
        }

        const constRe = /static\s+const\s+[\w:<>]+\s+([A-Za-z_]\w*)\s*=\s*([^;]+);/g;
        while ((m = constRe.exec(stripped)) !== null) {
            table.set(m[1], m[2].trim());
        }
    }
    return table;
}

module.exports = { collectConstants, resolveExpr, resolveIdentifier, annotateExpr };
