// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// File discovery
// ---------------------------------------------------------------------------

const fs = require('fs');
const path = require('path');

function listHlslFiles(dir) {
    const out = [];
    if (!fs.existsSync(dir)) return out;
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            out.push(...listHlslFiles(full));
        } else if (/\.hlsli?$/i.test(entry.name)) {
            out.push(full);
        }
    }
    return out;
}

// Recursively finds every directory under `root` whose name matches
// "nodes-*" (e.g. nodes-compute, nodes-mesh), at any depth.
function findNodeDirs(root) {
    const found = [];
    function walk(dir) {
        let entries;
        try {
            entries = fs.readdirSync(dir, { withFileTypes: true });
        } catch {
            return;
        }
        for (const entry of entries) {
            if (!entry.isDirectory()) continue;
            const full = path.join(dir, entry.name);
            if (/^nodes-/i.test(entry.name)) found.push(full);
            walk(full);
        }
    }
    walk(root);
    return found;
}

module.exports = { listHlslFiles, findNodeDirs };
