// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// Global resource index: every HLSL resource bound via ": register(tN)" (SRV/
// UAV/CBV/sampler root descriptors and descriptor-table entries alike) -
// StructuredBuffer<T> name : register(t3);, ConstantBuffer<T> name :
// register(b0);, etc. Scanned across the *whole* tree, same as
// collectConstants(), since these live in structs/*.hlsl, not nodes-*.
// ---------------------------------------------------------------------------

const fs = require('fs');
const path = require('path');
const { listHlslFiles } = require('./discovery');
const { stripComments } = require('./comments');
const { escapeRegExp } = require('../common/text-utils');

const GLOBAL_DECL_RE =
    /^[ \t]*(RW)?([A-Za-z_]\w*)\s*(?:<\s*([^<>]+?)\s*>)?\s+([A-Za-z_]\w*)\s*(?:\[[^\]]*\])?\s*:\s*register\(\s*([A-Za-z])(\d+)\s*(?:,\s*space(\d+)\s*)?\)\s*;/gm;

function collectGlobals(rootDir) {
    const globals = new Map();
    for (const file of listHlslFiles(rootDir)) {
        const stripped = stripComments(fs.readFileSync(file, 'utf8')).text;
        const relPath = path.relative(rootDir, file).replace(/\\/g, '/');
        const re = new RegExp(GLOBAL_DECL_RE.source, 'gm');
        let m;
        while ((m = re.exec(stripped)) !== null) {
            const [, rw, kind, valueType, name, regType, regSlot, space] = m;
            if (globals.has(name)) continue; // first declaration wins
            globals.set(name, {
                name,
                rw: !!rw,
                kind,
                valueType: valueType || null,
                regType: regType.toLowerCase(),
                regSlot: parseInt(regSlot, 10),
                space: space ? parseInt(space, 10) : 0,
                file: relPath,
            });
        }
    }
    return globals;
}

// Whether `name` (a global identifier) is used by this node body: true if
// its first appearance is a plain reference (e.g. `glmMetaData[i]`), false
// if the body shadows it with a same-named local before ever referencing the
// global (e.g. `BuildingMetaData glmMetaData = ...;`) - detected by checking
// whether that first occurrence looks like a declaration (preceded by a
// type-like token, followed by `=`/`;`/`[`/`,`/`)`). Only the first
// occurrence is checked, matching normal top-to-bottom C-like scoping in
// these flat (non-nested-shadowing) node function bodies.
function isGlobalUsedInBody(body, name) {
    const re = new RegExp(`\\b${escapeRegExp(name)}\\b`);
    const m = re.exec(body);
    if (!m) return false;
    const before = body.slice(0, m.index);
    const after = body.slice(m.index + name.length);
    const looksLikeDeclType = /[A-Za-z_]\w*(?:\s*<[^<>]*>)?\s+$/.test(before);
    const looksLikeDeclTail = /^\s*[=;[,)]/.test(after);
    return !(looksLikeDeclType && looksLikeDeclTail);
}

module.exports = { GLOBAL_DECL_RE, collectGlobals, isGlobalUsedInBody };
