// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// `hlsl-workgraph-diagram parse-source [rootSourceDir] [outJsonFile]`
//
// The v1 regex/paren-balance scanner - no real HLSL/C preprocessor, just
// enough text scanning to handle real-world work-graph shader trees (see
// the root README's Limitations). Recursively finds "nodes-*" directories
// under rootSourceDir, scans every [Shader("node")] function in them, and
// writes the shared IR (see ../common/ir.js) to outJsonFile for build-puml
// to consume - this command does no rendering itself.
// ---------------------------------------------------------------------------

const fs = require('fs');
const path = require('path');

const { parseArgs } = require('../common/cli-args');
const { writeIrFile } = require('../common/ir');
const { findNodeDirs, listHlslFiles } = require('./discovery');
const { stripComments } = require('./comments');
const { extractNodes } = require('./nodes');
const { collectConstants } = require('./constants');
const { collectGlobals, isGlobalUsedInBody } = require('./globals');
const { buildIr } = require('./to-ir');

function printHelp() {
    console.log(`Usage: hlsl-workgraph-diagram parse-source [rootSourceDir] [outJsonFile]

Recursively searches rootSourceDir for "nodes-*" directories, scans the HLSL
files inside for work-graph node functions ([Shader("node")]), and writes
the shared work-graph IR (see docs/ir-format.md) as JSON to outJsonFile -
input for "hlsl-workgraph-diagram build-puml".

Arguments:
  rootSourceDir   Directory to search for nodes-* dirs in.
                  Default: current working directory.
  outJsonFile     Path to write the IR JSON to. ".json" is appended
                  automatically if not already present.
                  Default: work-graph.ir.json, in the current working
                  directory.

Options:
  --help, -h, -?   Show this help text and exit.
`);
}

function run(argv) {
    const { positionals, help } = parseArgs(argv, []);
    if (help) {
        printHelp();
        return;
    }

    const rootDir = path.resolve(positionals[0] || process.cwd());
    const outArg = positionals[1] || 'work-graph.ir.json';
    const outFile = path.resolve(/\.json$/i.test(outArg) ? outArg : `${outArg}.json`);

    console.error(`Searching for nodes-* directories under: ${rootDir}`);
    const nodeDirs = findNodeDirs(rootDir);
    if (nodeDirs.length === 0) {
        console.error(`No "nodes-*" directories found under ${rootDir}`);
        process.exitCode = 1;
        return;
    }
    console.error(
        `Found ${nodeDirs.length} nodes-* director${nodeDirs.length === 1 ? 'y' : 'ies'}: ` +
            nodeDirs.map((d) => path.relative(rootDir, d) || '.').join(', ')
    );

    const table = collectConstants(rootDir);

    const files = [];
    for (const nodesDir of nodeDirs) {
        const group = path.basename(nodesDir);
        for (const f of listHlslFiles(nodesDir)) files.push({ file: f, group });
    }
    files.sort((a, b) => a.file.localeCompare(b.file));

    const allNodes = [];
    for (const { file, group } of files) {
        const raw = fs.readFileSync(file, 'utf8');
        const { text: stripped, rawIndex } = stripComments(raw);
        const relPath = path.relative(rootDir, file).replace(/\\/g, '/');
        // needsBody is always true here (unlike the pre-split tool, which
        // gated this on --global-boxes/--global-list): parse-source's job
        // is to extract everything it can into the IR, not to decide what
        // build-puml will later choose to display.
        const nodes = extractNodes(stripped, relPath, raw, rawIndex, group, true);
        allNodes.push(...nodes);
    }

    const nodesById = new Map();
    for (const n of allNodes) {
        if (nodesById.has(n.id)) {
            console.error(`Warning: duplicate node id "${n.id}" (${nodesById.get(n.id).file} and ${n.file})`);
        }
        nodesById.set(n.id, n);
    }

    const globalsIndex = collectGlobals(rootDir);
    if (globalsIndex.size > 0) {
        // Pre-sorted once by (regType, regSlot) - "t3 before t5" - so every
        // node's filtered globalsUsed list inherits that order for free.
        const globalsBySlot = [...globalsIndex.values()].sort(
            (a, b) => a.regType.localeCompare(b.regType) || a.regSlot - b.regSlot
        );
        for (const n of allNodes) {
            n.globalsUsed = n.bodyText
                ? globalsBySlot.filter((g) => isGlobalUsedInBody(n.bodyText, g.name)).map((g) => g.name)
                : [];
        }
    } else {
        for (const n of allNodes) n.globalsUsed = [];
    }

    const edgeCount = allNodes.reduce((sum, n) => sum + n.outputs.length, 0);
    console.error(
        `Scanned ${files.length} file(s), found ${allNodes.length} node function(s), ${edgeCount} edge(s), ${globalsIndex.size} global resource(s).`
    );

    const ir = buildIr(allNodes, globalsIndex, table, {
        rootDir,
        nodeDirs: nodeDirs.map((d) => path.relative(rootDir, d) || '.'),
        filesScanned: files.length,
    });
    writeIrFile(outFile, ir);
    console.error(`Wrote ${outFile}`);
}

module.exports = { run, printHelp };
