// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// Parameter classification
// ---------------------------------------------------------------------------

const { parseLeadingAttributes, parseAttributesAt, findAttr } = require('./attributes');
const { unquote, splitTopLevel, findMatchingParen, findMatchingBrace } = require('../common/text-utils');
const { extractPrecedingComment } = require('./comments');

const INPUT_TYPES = [
    'RWDispatchNodeInputRecord',
    'DispatchNodeInputRecord',
    'RWGroupNodeInputRecords',
    'GroupNodeInputRecords',
    'ThreadNodeInputRecord',
    'EmptyNodeInput',
];

const OUTPUT_TYPES = [
    'NodeOutputArray',
    'NodeOutput',
    'EmptyNodeOutputArray',
    'EmptyNodeOutput',
];

function classifyParam(rawParam) {
    const { attrs, rest } = parseLeadingAttributes(rawParam);

    for (const t of INPUT_TYPES) {
        const re = new RegExp('^' + t + '\\s*(<\\s*([\\w:]+)\\s*>)?\\s*(\\w+)?');
        const m = rest.match(re);
        if (m) {
            const maxRecordsAttr = findAttr(attrs, 'MaxRecords');
            return {
                category: 'input',
                recordKind: t,
                recordType: m[2] || null,
                varName: m[3] || null,
                maxRecords: maxRecordsAttr ? maxRecordsAttr.args : null,
                attrs,
            };
        }
    }

    for (const t of OUTPUT_TYPES) {
        const re = new RegExp('^' + t + '\\s*(<\\s*([\\w:]+)\\s*>)?\\s*(\\w+)?');
        const m = rest.match(re);
        if (m) {
            const nodeIdAttr = findAttr(attrs, 'NodeID') || findAttr(attrs, 'NodeId');
            const maxRecordsAttr = findAttr(attrs, 'MaxRecords');
            const maxRecordsSharedWithAttr = findAttr(attrs, 'MaxRecordsSharedWith');
            const varName = m[3] || null;
            return {
                category: 'output',
                recordKind: t,
                recordType: m[2] || null,
                varName,
                targetId: nodeIdAttr ? unquote(nodeIdAttr.args) : varName,
                maxRecords: maxRecordsAttr ? maxRecordsAttr.args : null,
                maxRecordsSharedWith: maxRecordsSharedWithAttr ? maxRecordsSharedWithAttr.args : null,
                attrs,
            };
        }
    }

    if (/^out\s+indices\b/.test(rest) || /^out\s+vertices\b/.test(rest) || /^out\s+primitives\b/.test(rest)) {
        // Mesh-shader output arrays (rasterizer-bound), not a work-graph edge.
        const m = rest.match(/^out\s+(indices|vertices|primitives)\s+(\S+)\s+(\w+)/);
        return {
            category: 'meshOutput',
            kind: m ? m[1] : 'unknown',
            type: m ? m[2] : null,
            varName: m ? m[3] : null,
        };
    }

    // Anything else (SV_* system values, plain scalars, etc.)
    return { category: 'other', raw: rest };
}

// ---------------------------------------------------------------------------
// Node-function extraction
// ---------------------------------------------------------------------------

function extractNodes(src, relPath, raw, rawIndex, group, needsBody) {
    const nodes = [];
    const shaderNodeRe = /\[\s*Shader\s*\(\s*"node"\s*\)\s*\]/g;
    let match;

    while ((match = shaderNodeRe.exec(src)) !== null) {
        // Walk backwards from the [Shader("node")] match to pick up any
        // attributes written *before* it too (defensive; in this codebase
        // Shader("node") is always first, but don't assume).
        let attrs = [];

        // Parse the attribute run starting exactly at this match, since
        // [Shader("node")] is itself the first attribute of the run.
        const { attrs: forwardAttrs, nextPos } = parseAttributesAt(src, match.index);
        attrs = forwardAttrs;

        // After the attribute run we expect: void FunctionName(
        const sigMatch = src.slice(nextPos).match(/^\s*void\s+([A-Za-z_]\w*)\s*\(/);
        if (!sigMatch) {
            continue; // not a node function signature we can parse; skip
        }
        const functionName = sigMatch[1];
        const openParenPos = nextPos + sigMatch.index + sigMatch[0].length - 1;
        const closeParenPos = findMatchingParen(src, openParenPos);
        if (closeParenPos === -1) continue;

        const paramListRaw = src.slice(openParenPos + 1, closeParenPos);
        const paramStrings = splitTopLevel(paramListRaw).map((p) => p.trim()).filter(Boolean);
        const params = paramStrings.map(classifyParam);

        const launchAttr = findAttr(attrs, 'NodeLaunch');
        const nodeIdAttr = findAttr(attrs, 'NodeID') || findAttr(attrs, 'NodeId');
        const numThreadsAttr = findAttr(attrs, 'NumThreads');
        const outputTopologyAttr = findAttr(attrs, 'OutputTopology');
        const maxRecursionAttr = findAttr(attrs, 'NodeMaxRecursionDepth');
        const dispatchGridAttr = findAttr(attrs, 'NodeDispatchGrid');
        const maxDispatchGridAttr = findAttr(attrs, 'NodeMaxDispatchGrid');
        const rawPos = rawIndex[match.index];
        const comment = extractPrecedingComment(raw, rawPos);
        // 1-based line of the [Shader("node")] attribute in the original
        // (unstripped) source - cheap to compute since rawIndex[] already
        // maps back to the exact raw offset, so may as well carry it
        // through for the IR's sourceLine (parse-dxil has this from debug
        // info; this closes the same gap here for free).
        const sourceLine = raw.slice(0, rawPos).split('\n').length;

        let bodyText = '';
        if (needsBody) {
            const openBraceIdx = src.indexOf('{', closeParenPos + 1);
            const closeBraceIdx = openBraceIdx === -1 ? -1 : findMatchingBrace(src, openBraceIdx);
            if (closeBraceIdx !== -1) bodyText = src.slice(openBraceIdx + 1, closeBraceIdx);
        }

        nodes.push({
            id: nodeIdAttr ? unquote(nodeIdAttr.args) : functionName,
            functionName,
            file: relPath,
            sourceLine,
            group,
            comment,
            bodyText,
            launchMode: launchAttr ? unquote(launchAttr.args) : null,
            isEntry: !!findAttr(attrs, 'NodeIsProgramEntry'),
            numThreads: numThreadsAttr ? numThreadsAttr.args : null,
            outputTopology: outputTopologyAttr ? unquote(outputTopologyAttr.args) : null,
            maxRecursionDepth: maxRecursionAttr ? maxRecursionAttr.args : null,
            dispatchGrid: dispatchGridAttr ? dispatchGridAttr.args : null,
            maxDispatchGrid: maxDispatchGridAttr ? maxDispatchGridAttr.args : null,
            inputs: params.filter((p) => p.category === 'input'),
            outputs: params.filter((p) => p.category === 'output'),
            meshOutputs: params.filter((p) => p.category === 'meshOutput'),
        });
    }

    return nodes;
}

module.exports = { INPUT_TYPES, OUTPUT_TYPES, classifyParam, extractNodes };
