// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// Assembles the raw regex-scanned nodes/globals into the shared IR (see
// ../common/ir.js). The one substantive change from the pre-split tool:
// #define/static-const resolution now happens *here*, at parse time, into
// { resolved, source } pairs - not deferred to render time via a constants
// table threaded through the whole render/ tree. That's what lets
// build-puml read parse-source's and parse-dxil's output identically:
// parse-dxil's numbers arrive pre-resolved from dxc with no table of its
// own, so a shared "resolved value + optional original text" shape is the
// only thing both can produce.
// ---------------------------------------------------------------------------

const { resolveExpr, annotateExpr } = require('./constants');

// A single un-evaluated expression -> { resolved, source }. `source` is
// dropped (set null) whenever it would just repeat the resolved literal -
// nothing more to show than the number already in `resolved` - and
// otherwise has each of its own identifiers (if any) annotated with their
// individual resolved values (e.g. "VERT_SEG * HOR_SEG" -> "VERT_SEG (6) *
// HOR_SEG (8)"), so a multi-factor expression's display doesn't conflate
// one factor's value with the whole product - see build-puml/node-label.js.
function toScalarField(rawExpr, table) {
    if (rawExpr == null) return null;
    const trimmed = rawExpr.trim();
    const resolved = resolveExpr(trimmed, table);
    const sameAsResolved = resolved !== null && trimmed.replace(/\s+/g, '') === String(resolved);
    return { resolved, source: sameAsResolved ? null : annotateExpr(trimmed, table) };
}

// A comma-separated triple (NumThreads/NodeDispatchGrid/NodeMaxDispatchGrid
// args) -> per-axis resolved numbers + per-axis original text, so e.g.
// "COLLECT_THREADS, 1, 1" resolves axis 0 while leaving axes 1/2 as plain
// literals with no source text to show.
function toTripleField(rawExpr, table) {
    if (rawExpr == null) return null;
    const parts = rawExpr.split(',').map((p) => p.trim());
    const resolved = parts.map((p) => resolveExpr(p, table));
    const source = parts.map((p, i) => {
        const same = resolved[i] !== null && p.replace(/\s+/g, '') === String(resolved[i]);
        return same ? null : p;
    });
    return { resolved, source };
}

function nodeToIr(n, table) {
    return {
        id: n.id,
        nodeIdIndex: null, // v1 doesn't parse a [NodeID("X", index)] array-index argument - see docs/ir-format.md
        functionName: n.functionName,
        group: n.group || null,
        sourceFile: n.file,
        sourceLine: n.sourceLine != null ? n.sourceLine : null,
        comment: n.comment || null,
        isEntry: !!n.isEntry,
        launchMode: n.launchMode ? n.launchMode.toLowerCase() : null,
        numThreads: toTripleField(n.numThreads, table),
        dispatchGrid: toTripleField(n.dispatchGrid, table),
        maxDispatchGrid: toTripleField(n.maxDispatchGrid, table),
        maxRecursionDepth: toScalarField(n.maxRecursionDepth, table),
        outputTopology: n.outputTopology || null,
        inputs: n.inputs.map((inp) => ({
            recordKind: inp.recordKind,
            recordType: inp.recordType,
            varName: inp.varName,
            maxRecords: toScalarField(inp.maxRecords, table),
            recordFields: null, // v1 doesn't resolve struct field lists - see docs/ir-format.md
        })),
        outputs: n.outputs.map((out) => ({
            recordKind: out.recordKind,
            recordType: out.recordType,
            varName: out.varName,
            linkedNodeID: { name: out.targetId, index: 0 },
            maxRecords: toScalarField(out.maxRecords, table),
            maxRecordsSharedWith: toScalarField(out.maxRecordsSharedWith, table),
            recordFields: null,
        })),
        meshOutputs: n.meshOutputs.map((mo) => ({ kind: mo.kind, type: mo.type, varName: mo.varName })),
        globalsUsed: n.globalsUsed || [],
    };
}

const REG_TYPE_TO_RESOURCE_CLASS = { t: 'SRV', u: 'UAV', b: 'CBV', s: 'Sampler' };

function globalToIr(g) {
    return {
        name: g.name,
        resourceClass: REG_TYPE_TO_RESOURCE_CLASS[g.regType] || null,
        rw: !!g.rw,
        kind: g.kind,
        valueType: g.valueType || null,
        regType: g.regType,
        regSlot: g.regSlot,
        space: g.space || 0,
        file: g.file,
    };
}

// nodes: raw extractNodes() output (globalsUsed already attached by the
// caller). globalsIndex: the Map from collectGlobals(). table: the Map from
// collectConstants().
function buildIr(nodes, globalsIndex, table, generatorDetail) {
    return {
        generator: 'parse-source',
        generatorDetail,
        nodes: nodes.map((n) => nodeToIr(n, table)),
        globals: [...globalsIndex.values()].map(globalToIr),
    };
}

module.exports = { toScalarField, toTripleField, nodeToIr, globalToIr, buildIr };
