// ---------------------------------------------------------------------------
// AUTO-GENERATED CONTENT: everything below was generated by Claude Sonnet 5
// (Anthropic), an LLM coding assistant, under end-to-end development
// supervision - it was generated as prompted, code was not adjusted or
// written. Review before relying on it.
// ---------------------------------------------------------------------------
// Single compile unit for "hlsl-workgraph-diagram parse-dxil" - dxc needs
// one entry file that #includes everything the graph needs, unlike
// "parse-source", which scans nodes-*/ directories itself. Not used by
// parse-source at all (it never reads this file).
// ---------------------------------------------------------------------------
#include "nodes-compute/EntryNode.hlsl"
#include "nodes-compute/GenerateNode.hlsl"
#include "nodes-compute/CollectNode.hlsl"
