// ---------------------------------------------------------------------------
// AUTO-GENERATED CONTENT: everything below was generated by Claude Sonnet 5
// (Anthropic), an LLM coding assistant, under end-to-end development
// supervision - it was generated as prompted, code was not adjusted or
// written. Review before relying on it.
// ---------------------------------------------------------------------------
#ifndef MESH_CULLING_STRUCTS_GLOBALS_HLSL
#define MESH_CULLING_STRUCTS_GLOBALS_HLSL

struct ObjectData
{
    float3 position;
    float radius;
};

StructuredBuffer<ObjectData> objects : register(t0);

#endif
