// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM generated by iteratively
// prompt-review cycling the result. None of the code or any of the
// documentation was written by hand. REVIEW THE CODE AND ITS BEHAVIOR BEFORE
// RELYING ON IT.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// `hlsl-workgraph-diagram build-records <ir.json> <out.puml> [options]`
//
// Renders the IR's `recordTypes` (record struct layouts, parse-dxil only) as a
// PlantUML class diagram or YAML diagram. Fields with a special function are
// highlighted: SV_DispatchGrid (from the DXIL node metadata, so it is the
// field the runtime really reads), implicit padding, and whatever an optional
// annotations file marks (e.g. "this uint indexes quadBuffer").
// ---------------------------------------------------------------------------

const fs = require('fs');
const path = require('path');

const { parseArgs } = require('../common/cli-args');
const { readIrFile } = require('../common/ir');
const { pumlEscape } = require('../common/text-utils');

const ROLE_ORDER = ['cpu-entry-record', 'node-record', 'buffer-element', 'nested'];
const ROLE_TITLES = {
    'cpu-entry-record': 'Entry records (written by the CPU, NodeCPUInput)',
    'node-record': 'Node records (graph edges)',
    'buffer-element': 'Buffer element types (StructuredBuffer, RWStructuredBuffer)',
    nested: 'Nested structs',
};
// Highlight classes: one colour per kind of special function, shared by both styles.
const KINDS = {
    semantic: { colour: '#C0392B', back: '#FADBD8', label: 'system value (SV_DispatchGrid): sizes the consumer\'s dispatch grid' },
    index: { colour: '#1F618D', back: '#D6EAF8', label: 'index into a buffer' },
    control: { colour: '#9A6700', back: '#FCF3CF', label: 'control value (pass identity, flags)' },
    padding: { colour: '#7F8C8D', back: '#EAEDED', label: 'implicit padding (no field)' },
};

function printHelp() {
    console.log(`Usage: hlsl-workgraph-diagram build-records [inJsonFile] [outPUml] [options]

Renders the record struct layouts of a parse-dxil IR (its "recordTypes") as a
PlantUML diagram: every field with its byte offset, type and array size.
Highlighted: SV_DispatchGrid fields (from the DXIL node metadata), implicit
padding, and fields marked in an --annotations file.

Options:
  --style <class|yaml>       class diagram (default) or YAML diagram.
  --roles <list>             comma-separated subset of: ${ROLE_ORDER.join(', ')}.
                             Default: all.
  --annotations <file.json>  { "Type.field": { "kind": "index"|"control",
                             "note": "...", "target": "<buffer>",
                             "evidence": "file:line" } }
  --comments / --no-comments Show each field's source comment. Default: on.
  --help, -h, -?             Show this help text and exit.
`);
}

function run(argv) {
    const { values, positionals, help } = parseArgs(argv, [
        { name: 'style', flag: '--style', type: 'string', default: 'class' },
        { name: 'roles', flag: '--roles', type: 'string', default: null },
        { name: 'annotations', flag: '--annotations', type: 'string', default: null },
        { name: 'comments', flag: '--comments', negFlag: '--no-comments', type: 'boolean', default: true },
    ]);
    if (help) {
        printHelp();
        return;
    }
    const ir = readIrFile(path.resolve(positionals[0] || 'work-graph.ir.json'));
    if (!ir.recordTypes) throw new Error('IR has no recordTypes - regenerate it with parse-dxil (needs -Zi debug info)');
    const outArg = positionals[1] || 'records.puml';
    const outFile = path.resolve(/\.puml$/i.test(outArg) ? outArg : `${outArg}.puml`);
    const roles = values.roles ? values.roles.split(',').map((s) => s.trim()) : ROLE_ORDER;
    const annotations = values.annotations ? JSON.parse(fs.readFileSync(path.resolve(values.annotations), 'utf8')) : {};

    const types = Object.entries(ir.recordTypes)
        .map(([name, t]) => ({ name, ...t, role: ROLE_ORDER.find((r) => t.roles.includes(r)), rows: rowsOf(name, t, annotations) }))
        .filter((t) => roles.includes(t.role));
    const opts = { comments: values.comments };
    const puml = values.style === 'yaml' ? renderYaml(types, opts) : renderClass(types, opts);
    fs.writeFileSync(outFile, puml, 'utf8');
    console.log(`Wrote ${outFile} (${types.length} record type(s), style ${values.style}).`);
}

// Fields plus explicit padding rows, each with its highlight kind (or null).
function rowsOf(typeName, t, annotations) {
    const rows = [];
    let cursor = 0;
    const pad = (at, bytes) => rows.push({ padding: true, offsetBytes: at, sizeBytes: bytes, kind: 'padding' });
    for (const f of t.fields) {
        if (f.offsetBytes > cursor) pad(cursor, f.offsetBytes - cursor);
        const a = annotations[`${typeName}.${f.name}`] || null;
        const kind = f.semantic ? 'semantic' : a ? a.kind || 'control' : null;
        rows.push({ ...f, annotation: a, kind });
        cursor = Math.max(cursor, f.offsetBytes + f.sizeBytes);
    }
    if (t.sizeBytes > cursor) pad(cursor, t.sizeBytes - cursor);
    return rows;
}

const typeText = (f) => `${f.type}${(f.arrayDims || []).map((d) => `[${d}]`).join('')}`;
const hex = (n) => `+${n}`.padEnd(5, ' ');
const clip = (s, n) => (s && s.length > n ? `${s.slice(0, n - 1)}…` : s);

function flagsOf(t) {
    const out = [];
    const flags = Object.values((t.dxil && t.dxil.flagsByNode) || {});
    if (flags.some((f) => f.readWrite)) out.push('RW input');
    if (flags.some((f) => f.trackRWInputSharing)) out.push('NodeTrackRWInputSharing');
    if (flags.some((f) => f.globallyCoherent)) out.push('globallycoherent');
    return out;
}

function usageLines(t) {
    const u = t.usage || {};
    const lines = [];
    if (u.producers && u.producers.length) lines.push(`produced by ${u.producers.join(', ')}`);
    if (t.roles.includes('cpu-entry-record')) lines.push('produced by the CPU (DispatchGraph NodeCPUInput)');
    if (u.consumers && u.consumers.length) lines.push(`consumed by ${u.consumers.join(', ')}`);
    if (u.buffers && u.buffers.length) lines.push(`element of ${u.buffers.join(', ')}`);
    return lines;
}

function annotationText(r) {
    if (r.semantic) return r.semantic === 'SV_DispatchGrid' ? 'SV_DispatchGrid (verified in DXIL metadata)' : `${r.semantic} (source)`;
    if (!r.annotation) return null;
    return [r.annotation.target ? `→ ${r.annotation.target}[]` : null, r.annotation.note].filter(Boolean).join(' ');
}

// ---- class diagram ----------------------------------------------------------

function renderClass(types, opts) {
    const L = ['@startuml RecordLayouts', 'hide empty methods', 'hide circle', 'skinparam classAttributeIconSize 0',
        'skinparam classFontStyle bold', 'skinparam classAttributeFontName monospaced', 'skinparam classAttributeFontSize 11',
        'skinparam class {', '  BackgroundColor #FFFFFF', '  BorderColor #5D6D7E',
        '  BackgroundColor<<cpu-entry-record>> #E8F8F5', '  BackgroundColor<<node-record>> #EBF5FB',
        '  BackgroundColor<<buffer-element>> #FEF9E7', '  BackgroundColor<<nested>> #F4F6F6', '}',
        'skinparam packageStyle rectangle', 'left to right direction', ''];
    for (const role of ROLE_ORDER) {
        const group = types.filter((t) => t.role === role);
        if (!group.length) continue;
        L.push(`package "${ROLE_TITLES[role]}" {`);
        for (const t of group) {
            const extra = [`${t.sizeBytes} B`, ...flagsOf(t)];
            if (t.dxil && t.dxil.recordSizeBytes != null && t.dxil.recordSizeBytes !== t.sizeBytes) extra.push(`DXIL says ${t.dxil.recordSizeBytes} B!`);
            L.push(`  class ${t.name} <<${t.role}>> {`);
            L.push(`    {field} <size:10><color:#5D6D7E>${pumlEscape(extra.join(' · '))}</color></size>`);
            L.push('    ==');
            for (const r of t.rows) L.push(`    {field} ${classRow(r, opts)}`);
            const usage = usageLines(t);
            if (usage.length) {
                L.push('    ..');
                for (const u of usage) L.push(`    {field} <size:10><i>${pumlEscape(u)}</i></size>`);
            }
            L.push('  }');
        }
        L.push('}');
    }
    // Composition: a struct field whose type is another struct.
    for (const t of types) {
        for (const r of t.rows) {
            if (r.structType && types.some((x) => x.name === r.structType)) L.push(`${t.name} *-- "${(r.arrayDims || []).length ? r.arrayDims.join('x') : '1'}" ${r.structType} : ${r.name}`);
        }
    }
    L.push('', 'legend right');
    for (const [, k] of Object.entries(KINDS)) L.push(`  <back:${k.back}><color:${k.colour}><b>  field  </b></color></back> ${pumlEscape(k.label)}`);
    L.push('  offsets in bytes; layout from DXIL debug info (-Zi), SV_DispatchGrid from DXIL node metadata', 'endlegend', '@enduml');
    return L.join('\n');
}

function classRow(r, opts) {
    if (r.padding) return `<back:${KINDS.padding.back}><color:${KINDS.padding.colour}><i>${hex(r.offsetBytes)}  (${r.sizeBytes} B padding)</i></color></back>`;
    let body = `${hex(r.offsetBytes)}  ${pumlEscape(typeText(r)).padEnd(14, ' ')} ${pumlEscape(r.name)}`;
    const note = annotationText(r);
    if (r.kind) {
        const k = KINDS[r.kind];
        body = `<back:${k.back}><color:${k.colour}><b>${body}</b></color></back>`;
        if (note) body += `  <color:${k.colour}><size:10>${pumlEscape(note)}</size></color>`;
    }
    if (opts.comments && r.comment) body += `  <color:#95A5A6><size:9>// ${pumlEscape(clip(r.comment, 70))}</size></color>`;
    return body;
}

// ---- YAML diagram -----------------------------------------------------------

// PlantUML's YAML reader is a small subset: plain scalars and nesting by
// indentation. Keys are kept free of ':' and quotes so they parse as-is.
// '/' is also the #highlight path separator, so it cannot appear in a key.
function yamlKey(s) {
    return s.replace(/[:"#/]/g, ' ').replace(/\s+/g, ' ').trim();
}

function renderYaml(types, opts) {
    const L = ['@startyaml RecordLayouts', '<style>', 'yamlDiagram {', '  node { FontSize 11 }', '  highlight { FontStyle bold }'];
    for (const [name, k] of Object.entries(KINDS)) L.push(`  .${name} { BackGroundColor ${k.back} ; FontColor ${k.colour} }`);
    L.push('}', '</style>');
    const body = [];
    const highlights = [];
    for (const role of ROLE_ORDER) {
        const group = types.filter((t) => t.role === role);
        if (!group.length) continue;
        const roleKey = yamlKey(ROLE_TITLES[role]);
        body.push(`${roleKey}:`);
        for (const t of group) {
            const typeKey = yamlKey(`${t.name} (${[`${t.sizeBytes} B`, ...flagsOf(t)].join(', ')})`);
            body.push(`  ${typeKey}:`);
            for (const r of t.rows) {
                const key = r.padding ? yamlKey(`+${r.offsetBytes} padding`) : yamlKey(`+${r.offsetBytes} ${r.name}`);
                let value = r.padding ? `${r.sizeBytes} B` : typeText(r);
                const note = annotationText(r);
                if (note) value += `  ${note}`;
                if (opts.comments && r.comment && !r.padding) value += `  // ${clip(r.comment, 60)}`;
                body.push(`    ${key}: ${yamlKey(value)}`);
                if (r.kind) highlights.push(`#highlight "${roleKey}" / "${typeKey}" / "${key}" <<${r.kind}>>`);
            }
            for (const u of usageLines(t)) body.push(`    ${yamlKey(u.split(' ')[0] + ' ' + u.split(' ')[1])}: ${yamlKey(u.split(' ').slice(2).join(' '))}`);
        }
    }
    L.push(...highlights, ...body, '@endyaml');
    return L.join('\n');
}

module.exports = { run, printHelp, rowsOf };
