// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM generated by iteratively
// prompt-review cycling the result. None of the code or any of the
// documentation was written by hand. REVIEW THE CODE AND ITS BEHAVIOR BEFORE
// RELYING ON IT.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// `hlsl-workgraph-diagram build-records <ir.json> <out.puml> [options]`
//
// Renders the IR's `recordTypes` (record struct layouts, parse-dxil only) as a
// PlantUML class diagram or YAML diagram. Fields with a special function are
// highlighted: SV_DispatchGrid (from the DXIL node metadata, so it is the
// field the runtime really reads), implicit padding, and whatever an optional
// annotations file marks (e.g. "this uint indexes quadBuffer").
// ---------------------------------------------------------------------------

const fs = require('fs');
const path = require('path');

const { parseArgs } = require('../common/cli-args');
const { readIrFile } = require('../common/ir');
const { pumlEscape } = require('../common/text-utils');

const ROLE_ORDER = ['cpu-entry-record', 'node-record', 'buffer-element', 'nested'];
const ROLE_TITLES = {
    'cpu-entry-record': 'Entry records (written by the CPU, NodeCPUInput)',
    'node-record': 'Node records (graph edges)',
    'buffer-element': 'Buffer element types (StructuredBuffer, RWStructuredBuffer)',
    nested: 'Nested structs',
};
// Highlight classes: one colour per kind of special function, shared by both styles.
const KINDS = {
    semantic: { colour: '#C0392B', back: '#FADBD8', label: 'system value (SV_DispatchGrid): sizes the consumer\'s dispatch grid' },
    index: { colour: '#1F618D', back: '#D6EAF8', label: 'indexes a buffer (DXIL dataflow)' },
    sizing: { colour: '#6C3483', back: '#EBDEF0', label: 'affects an output allocation count (DXIL dataflow)' },
    control: { colour: '#9A6700', back: '#FCF3CF', label: 'decides control flow in a node (DXIL dataflow)' },
    annotation: { colour: '#117A65', back: '#D1F2EB', label: 'role supplied only by --annotations' },
    unread: { colour: '#95A5A6', back: '#FFFFFF', label: 'written but never read by any node (DXIL dataflow)' },
    padding: { colour: '#7F8C8D', back: '#EAEDED', label: 'implicit padding (no field)' },
};

function printHelp() {
    console.log(`Usage: hlsl-workgraph-diagram build-records [inJsonFile] [outPUml] [options]

Renders the record struct layouts of a parse-dxil IR (its "recordTypes") as a
PlantUML diagram: every field with its byte offset, type and array size.
Highlighted: SV_DispatchGrid fields (from the DXIL node metadata), implicit
padding, and fields marked in an --annotations file.

Options:
  --style <class|yaml>       class diagram (default) or YAML diagram.
  --roles <list>             comma-separated subset of: ${ROLE_ORDER.join(', ')}.
                             Default: all.
  --annotations <file.json>  { "Type.field": { "kind": "index"|"control",
                             "note": "...", "target": "<buffer>",
                             "evidence": "file:line" } }
  --comments / --no-comments Show each field's source comment. Default: on.
  --line-type <spline|ortho|polyline>
                             Class style edge routing. Default: spline.
  --columns <n>              Class style: boxes per row within a group. Default: 4.
  --help, -h, -?             Show this help text and exit.
`);
}

function run(argv) {
    const { values, positionals, help } = parseArgs(argv, [
        { name: 'style', flag: '--style', type: 'string', default: 'class' },
        { name: 'roles', flag: '--roles', type: 'string', default: null },
        { name: 'annotations', flag: '--annotations', type: 'string', default: null },
        { name: 'comments', flag: '--comments', negFlag: '--no-comments', type: 'boolean', default: true },
        { name: 'columns', flag: '--columns', type: 'string', default: '4' },
        { name: 'lineType', flag: '--line-type', type: 'string', default: 'spline' },
    ]);
    if (help) {
        printHelp();
        return;
    }
    const ir = readIrFile(path.resolve(positionals[0] || 'work-graph.ir.json'));
    if (!ir.recordTypes) throw new Error('IR has no recordTypes - regenerate it with parse-dxil (needs -Zi debug info)');
    const outArg = positionals[1] || 'records.puml';
    const outFile = path.resolve(/\.puml$/i.test(outArg) ? outArg : `${outArg}.puml`);
    const roles = values.roles ? values.roles.split(',').map((s) => s.trim()) : ROLE_ORDER;
    const annotations = values.annotations ? JSON.parse(fs.readFileSync(path.resolve(values.annotations), 'utf8')) : {};

    const types = Object.entries(ir.recordTypes)
        .map(([name, t]) => ({ name, ...t, role: ROLE_ORDER.find((r) => t.roles.includes(r)), rows: rowsOf(name, t, annotations) }))
        .filter((t) => roles.includes(t.role));
    const opts = { comments: values.comments, columns: Math.max(1, Number(values.columns) || 4), lineType: values.lineType };
    const puml = values.style === 'yaml' ? renderYaml(types, opts) : renderClass(types, opts);
    fs.writeFileSync(outFile, puml, 'utf8');
    console.log(`Wrote ${outFile} (${types.length} record type(s), style ${values.style}).`);
}

// Fields plus explicit padding rows, each with its highlight kind (or null).
function rowsOf(typeName, t, annotations) {
    const rows = [];
    let cursor = 0;
    const pad = (at, bytes) => rows.push({ padding: true, offsetBytes: at, sizeBytes: bytes, kind: 'padding' });
    for (const f of t.fields) {
        if (f.offsetBytes > cursor) pad(cursor, f.offsetBytes - cursor);
        const a = annotations[`${typeName}.${f.name}`] || null;
        const d = f.dataflow || null;
        const inferredIndex = d ? [...new Set(d.indexes.map((i) => i.resource))] : [];
        const sizes = d ? [...new Set(d.sizesOutputs.map((x) => x.output))] : [];
        const controls = d ? d.controls || [] : [];
        let kind = null;
        if (f.semantic) kind = 'semantic';
        else if (inferredIndex.length) kind = 'index';
        else if (sizes.length) kind = 'sizing';
        else if (controls.length) kind = 'control';
        else if (a) kind = a.kind === 'index' ? 'index' : 'annotation';
        else if (d && d.writtenBy.length && !d.readBy.length) kind = 'unread';
        rows.push({ ...f, annotation: a, kind, inferredIndex, sizes, controls });
        cursor = Math.max(cursor, f.offsetBytes + f.sizeBytes);
    }
    if (t.sizeBytes > cursor) pad(cursor, t.sizeBytes - cursor);
    return rows;
}

const typeText = (f) => `${f.type}${(f.arrayDims || []).map((d) => `[${d}]`).join('')}`;
// Row prefix: size then offset, both plain byte counts, right-aligned (monospaced font).
const COL = { size: 5, offset: 7, type: 14 };
// Padding uses NO-BREAK SPACE: PlantUML strips leading ASCII spaces from a member line, which would
// left-align the numbers of every row not wrapped in a <back> highlight.
const NBSP = '\u00A0';
const sizeOffset = (size, offset) => `${String(size).padStart(COL.size, NBSP)}${String(offset).padStart(COL.offset, NBSP)}${NBSP}${NBSP}`;
const clip = (s, n) => (s && s.length > n ? `${s.slice(0, n - 1)}…` : s);

function flagsOf(t) {
    const out = [];
    const flags = Object.values((t.dxil && t.dxil.flagsByNode) || {});
    if (flags.some((f) => f.readWrite)) out.push('RW input');
    if (flags.some((f) => f.trackRWInputSharing)) out.push('NodeTrackRWInputSharing');
    if (flags.some((f) => f.globallyCoherent)) out.push('globallycoherent');
    return out;
}

function usageLines(t) {
    const u = t.usage || {};
    const lines = [];
    if (u.producers && u.producers.length) lines.push(`produced by ${u.producers.join(', ')}`);
    if (t.roles.includes('cpu-entry-record')) lines.push('produced by the CPU (DispatchGraph NodeCPUInput)');
    if (u.consumers && u.consumers.length) lines.push(`consumed by ${u.consumers.join(', ')}`);
    if (u.buffers && u.buffers.length) lines.push(`element of ${u.buffers.join(', ')}`);
    return lines;
}

// What is known about a field, each part tagged with where it came from.
function annotationText(r) {
    const parts = [];
    if (r.semantic) parts.push(r.semantic === 'SV_DispatchGrid' ? 'SV_DispatchGrid (DXIL metadata)' : `${r.semantic} (source)`);
    if (r.inferredIndex && r.inferredIndex.length) parts.push(`→ ${r.inferredIndex.map((x) => `${x}[]`).join(', ')} (DXIL)`);
    if (r.sizes && r.sizes.length) parts.push(`count of → ${capList(r.sizes)} (DXIL)`);
    if (r.controls && r.controls.length && !r.inferredIndex.length && !r.sizes.length) parts.push(`branches in ${capList(r.controls)} (DXIL)`);
    if (r.dataflow && r.semantic && r.dataflow.sources.length) parts.push(`← ${capList(foldSources(r.dataflow.sources))}`);
    if (r.kind === 'unread') parts.push('never read by a node');
    if (r.annotation) {
        const a = r.annotation;
        const confirmed = a.kind === 'index' && a.target && (r.inferredIndex || []).includes(a.target);
        if (!confirmed) parts.push(`${[a.target ? `→ ${a.target}[]` : null, a.note].filter(Boolean).join(' ')} (annotation)`);
        else if (a.note) parts.push(`${a.note} (annotation)`);
    }
    return parts.length ? parts.join('; ') : null;
}

// Sources folded to field level (vector components and array elements merged), constants dropped
// when anything else is known, capped so one field cannot widen the whole diagram.
function foldSources(sources) {
    const folded = sources.map((s) => s.replace(/\[[^\]]*\](?=\.|$)/g, (m) => (/^\[\d+\]$/.test(m) && s.startsWith('buf:') && !/\w\[/.test(s) ? m : '')).replace(/\.[xyzw]$/, ''));
    const nonConst = folded.filter((s) => !s.startsWith('const:'));
    return [...new Set(nonConst.length ? nonConst : folded)].map((s) => s.replace(/^buf:/, '').replace(/^in:/, 'in ').replace(/^sv:/, '').replace(/^const:/, ''));
}
const capList = (xs, n = 3) => (xs.length > n ? `${xs.slice(0, n).join(', ')} +${xs.length - n}` : xs.join(', '));

// ---- class diagram ----------------------------------------------------------

function renderClass(types, opts) {
    const L = ['@startuml RecordLayouts', 'hide empty methods', 'hide circle', 'skinparam classAttributeIconSize 0',
        'skinparam classFontStyle bold', 'skinparam classAttributeFontName monospaced', 'skinparam classAttributeFontSize 11',
        'skinparam class {', '  BackgroundColor #FFFFFF', '  BorderColor #5D6D7E',
        '  BackgroundColor<<cpu-entry-record>> #E8F8F5', '  BackgroundColor<<node-record>> #EBF5FB',
        '  BackgroundColor<<buffer-element>> #FEF9E7', '  BackgroundColor<<nested>> #F4F6F6', '}',
        'skinparam packageStyle rectangle'];
    if (opts.lineType && opts.lineType !== 'spline') L.push(`skinparam linetype ${opts.lineType}`);
    L.push('');
    for (const role of ROLE_ORDER) {
        const group = types.filter((t) => t.role === role);
        if (!group.length) continue;
        L.push(`package "${ROLE_TITLES[role]}" {`);
        for (const t of group) {
            const extra = [`${t.sizeBytes} B`, ...flagsOf(t)];
            if (t.dxil && t.dxil.recordSizeBytes != null && t.dxil.recordSizeBytes !== t.sizeBytes) extra.push(`DXIL says ${t.dxil.recordSizeBytes} B!`);
            L.push(`  class ${t.name} <<${t.role}>> {`);
            L.push(`    {field} <size:10><color:#5D6D7E>${pumlEscape(extra.join(' · '))}</color></size>`);
            L.push('    ==');
            L.push(`    {field} <color:#7F8C8D>${'size'.padStart(COL.size, NBSP)}${'offset'.padStart(COL.offset, NBSP)}${NBSP}${NBSP}${'type'.padEnd(COL.type, NBSP)}${NBSP}name</color>`);
            for (const r of t.rows) for (const line of classRow(r, opts)) L.push(`    {field} ${line}`);
            const usage = usageLines(t);
            if (usage.length) {
                L.push('    ..');
                for (const u of usage) L.push(`    {field} <size:10><i>${pumlEscape(u)}</i></size>`);
            }
            L.push('  }');
        }
        L.push('}');
    }
    // Grid layout: Graphviz would otherwise put every box of a group in one row. Hidden links from
    // each box to the one `columns` places later stack the rows; the last row of a group points at
    // the next group's first box so groups stack too.
    const ordered = ROLE_ORDER.flatMap((role) => types.filter((t) => t.role === role));
    for (const role of ROLE_ORDER) {
        const group = types.filter((t) => t.role === role);
        for (let i = 0; i + opts.columns < group.length; i++) L.push(`${group[i].name} -[hidden]down- ${group[i + opts.columns].name}`);
    }
    for (let r = 0; r + 1 < ROLE_ORDER.length; r++) {
        const a = types.filter((t) => t.role === ROLE_ORDER[r]);
        const b = ordered.find((t) => ROLE_ORDER.indexOf(t.role) > r);
        if (a.length && b) L.push(`${a[a.length - 1].name} -[hidden]down- ${b.name}`);
    }
    // Composition: a struct field whose type is another struct.
    for (const t of types) {
        for (const r of t.rows) {
            if (r.structType && types.some((x) => x.name === r.structType)) L.push(`${t.name} *-- "${(r.arrayDims || []).length ? r.arrayDims.join('x') : '1'}" ${r.structType} : ${r.name}`);
        }
    }
    L.push('', 'legend right');
    const used = new Set(types.flatMap((t) => t.rows.map((r) => r.kind)));
    for (const [, k] of Object.entries(KINDS).filter(([name]) => used.has(name))) L.push(`  <back:${k.back}><color:${k.colour}><b>  field  </b></color></back> ${pumlEscape(k.label)}`);
    L.push('  columns: size and offset in bytes, type, name; layout from DXIL debug info (-Zi), SV_DispatchGrid from DXIL node metadata;');
    L.push(types.some((t) => t.rows.some((r) => r.annotation))
        ? '  (DXIL) = inferred from the compiled shaders, (annotation) = supplied by an --annotations file'
        : '  (DXIL) = inferred from the compiled shaders');
    L.push('endlegend', '@enduml');
    return L.join('\n');
}

// One line for the field itself, then one indented line each for what is known about it and its
// source comment, so a long note makes a box taller rather than the whole diagram wider.
function classRow(r, opts) {
    if (r.padding) return [`<back:${KINDS.padding.back}><color:${KINDS.padding.colour}><i>${sizeOffset(r.sizeBytes, r.offsetBytes)}(padding)</i></color></back>`];
    let body = `${sizeOffset(r.sizeBytes, r.offsetBytes)}${pumlEscape(typeText(r)).padEnd(COL.type, NBSP)}${NBSP}${pumlEscape(r.name)}`;
    const k = r.kind ? KINDS[r.kind] : null;
    if (k) body = `<back:${k.back}><color:${k.colour}><b>${body}</b></color></back>`;
    const lines = [body];
    const note = annotationText(r);
    const indent = NBSP.repeat(COL.size + COL.offset + 2);
    if (note) lines.push(`${indent}<size:9><color:${k ? k.colour : '#5D6D7E'}>${pumlEscape(note)}</color></size>`);
    if (opts.comments && r.comment) lines.push(`${indent}<color:#95A5A6><size:9>// ${pumlEscape(clip(r.comment, 80))}</size></color>`);
    return lines;
}

// ---- YAML diagram -----------------------------------------------------------

// PlantUML's YAML reader is a small subset: plain scalars and nesting by
// indentation. Keys are kept free of ':' and quotes so they parse as-is.
// '/' is also the #highlight path separator, so it cannot appear in a key.
function yamlKey(s) {
    return s.replace(/[:"#/]/g, ' ').replace(/\s+/g, ' ').trim();
}

function renderYaml(types, opts) {
    const L = ['@startyaml RecordLayouts', '<style>', 'yamlDiagram {', '  node { FontSize 11 }', '  highlight { FontStyle bold }'];
    for (const [name, k] of Object.entries(KINDS)) L.push(`  .${name} { BackGroundColor ${k.back} ; FontColor ${k.colour} }`);
    L.push('}', '</style>');
    const body = [];
    const highlights = [];
    for (const role of ROLE_ORDER) {
        const group = types.filter((t) => t.role === role);
        if (!group.length) continue;
        const roleKey = yamlKey(ROLE_TITLES[role]);
        body.push(`${roleKey}:`);
        for (const t of group) {
            const typeKey = yamlKey(`${t.name} (${[`${t.sizeBytes} B`, ...flagsOf(t)].join(', ')})`);
            body.push(`  ${typeKey}:`);
            for (const r of t.rows) {
                const key = r.padding ? yamlKey(`padding at ${r.offsetBytes}`) : yamlKey(r.name);
                let value = r.padding ? `size ${r.sizeBytes} B` : `size ${r.sizeBytes} B, offset ${r.offsetBytes}, ${typeText(r)}`;
                const note = annotationText(r);
                if (note) value += `  ${note}`;
                if (opts.comments && r.comment && !r.padding) value += `  // ${clip(r.comment, 60)}`;
                body.push(`    ${key}: ${yamlKey(value)}`);
                if (r.kind) highlights.push(`#highlight "${roleKey}" / "${typeKey}" / "${key}" <<${r.kind}>>`);
            }
            for (const u of usageLines(t)) body.push(`    ${yamlKey(u.split(' ')[0] + ' ' + u.split(' ')[1])}: ${yamlKey(u.split(' ').slice(2).join(' '))}`);
        }
    }
    L.push(...highlights, ...body, '@endyaml');
    return L.join('\n');
}

module.exports = { run, printHelp, rowsOf };
