// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// Downloads a Microsoft.Direct3D.DXC build from nuget.org and extracts
// win-x64 dxc.exe + dxcompiler.dll (+ dxil.dll, when the package ships one)
// into the standard version-keyed cache location (see ./paths.js). Ported
// from the experimental spike's tools/fetch-dxc.sh, using Node's own https
// module instead of curl, per the "Node builtins only" promise.
//
// Version selection (see resolveVariant()): "mesh" pins to the one dxc
// build known able to compile a NodeLaunch("mesh") node so far (mesh-launch
// nodes were still preview-only as of every version published - see
// experimental/README.md); "stable" resolves to the latest published
// version with no prerelease tag; "experimental" resolves to the latest
// published version *with* a prerelease tag (whatever that currently is -
// historically the same mesh-nodes-preview build "mesh" pins to, but not
// necessarily always); anything else is treated as an exact version string.
// ---------------------------------------------------------------------------

const fs = require('fs');
const path = require('path');
const https = require('https');

const { openNupkg } = require('./nupkg-zip');
const { versionDir, dxcPathForVersion } = require('./paths');

const PACKAGE_ID = 'Microsoft.Direct3D.DXC';
const PACKAGE_ID_LOWER = 'microsoft.direct3d.dxc';
const MESH_PREVIEW_VERSION = '1.8.2404.55-mesh-nodes-preview';
const NAMED_VARIANTS = ['mesh', 'stable', 'experimental'];

function httpsGetBuffer(url, redirectsLeft = 5) {
    return new Promise((resolve, reject) => {
        https
            .get(url, (res) => {
                if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location && redirectsLeft > 0) {
                    res.resume();
                    resolve(httpsGetBuffer(new URL(res.headers.location, url).toString(), redirectsLeft - 1));
                    return;
                }
                if (res.statusCode !== 200) {
                    res.resume();
                    reject(new Error(`HTTP ${res.statusCode} for ${url}`));
                    return;
                }
                const chunks = [];
                res.on('data', (d) => chunks.push(d));
                res.on('end', () => resolve(Buffer.concat(chunks)));
            })
            .on('error', reject);
    });
}

function isPrerelease(version) {
    return version.includes('-');
}

// Splits "1.8.2404.55-mesh-nodes-preview" into its numeric core
// ([1,8,2404,55]) and prerelease tag ("mesh-nodes-preview", or null).
function parseVersion(version) {
    const dashIdx = version.indexOf('-');
    const numeric = dashIdx === -1 ? version : version.slice(0, dashIdx);
    const prerelease = dashIdx === -1 ? null : version.slice(dashIdx + 1);
    return { parts: numeric.split('.').map((n) => parseInt(n, 10) || 0), prerelease };
}

// Ascending comparator (for Array.prototype.sort): numeric core first
// (component by component), then a release outranks a prerelease with the
// same numeric core, then prerelease tags compare lexicographically.
function compareVersions(a, b) {
    const pa = parseVersion(a);
    const pb = parseVersion(b);
    const len = Math.max(pa.parts.length, pb.parts.length);
    for (let i = 0; i < len; i++) {
        const diff = (pa.parts[i] || 0) - (pb.parts[i] || 0);
        if (diff !== 0) return diff;
    }
    if (pa.prerelease == null && pb.prerelease != null) return 1;
    if (pa.prerelease != null && pb.prerelease == null) return -1;
    if (pa.prerelease === pb.prerelease) return 0;
    return pa.prerelease < pb.prerelease ? -1 : 1;
}

// Every version NuGet has ever published for this package (stable and
// prerelease alike, *including* delisted/unlisted ones - see below),
// ascending. NuGet's flat-container index lists the full history, unlike
// the search API (which only surfaces currently-listed versions) - this is
// what makes "list" (enumerate everything) and "experimental" (latest
// prerelease, whichever that currently is) possible at all.
async function listAllVersions() {
    const url = `https://api.nuget.org/v3-flatcontainer/${PACKAGE_ID_LOWER}/index.json`;
    const body = await httpsGetBuffer(url);
    const data = JSON.parse(body.toString('utf8'));
    if (!Array.isArray(data.versions)) throw new Error(`unexpected NuGet index response shape from ${url}`);
    return [...data.versions].sort(compareVersions);
}

// The latest *listed* stable (non-prerelease) version, via NuGet's search
// API rather than the flat-container index above - deliberately, since the
// flat-container index includes delisted/withdrawn versions too (observed:
// a "101.7.2207.25" entry sorts numerically highest but is delisted -
// almost certainly a publishing mistake - and the search API correctly
// excludes it). "stable" should mean "what NuGet itself currently
// considers the latest release", not "the numerically largest version
// string that ever existed".
async function resolveLatestStableVersion() {
    const url = `https://azuresearch-usnc.nuget.org/query?q=packageid:${PACKAGE_ID}&prerelease=false`;
    const body = await httpsGetBuffer(url);
    const data = JSON.parse(body.toString('utf8'));
    if (!data.data || !data.data[0] || !data.data[0].version) {
        throw new Error(`unexpected NuGet search response shape from ${url}`);
    }
    return data.data[0].version;
}

// nameOrVersion: "mesh" | "stable" | "experimental" | an exact version
// string. Returns the concrete version to install. Async throughout so
// "stable" can use the listed-only search API (see
// resolveLatestStableVersion() above) instead of the full history.
async function resolveVariant(nameOrVersion) {
    if (nameOrVersion === 'mesh') return MESH_PREVIEW_VERSION;
    if (nameOrVersion === 'stable') return resolveLatestStableVersion();
    if (nameOrVersion === 'experimental') {
        const pre = (await listAllVersions()).filter(isPrerelease);
        if (pre.length === 0) throw new Error(`no prerelease version found for ${PACKAGE_ID} on NuGet`);
        return pre[pre.length - 1];
    }
    return nameOrVersion; // explicit version string - existence is checked by the download itself
}

async function downloadNupkg(version, log) {
    const url = `https://api.nuget.org/v3-flatcontainer/${PACKAGE_ID_LOWER}/${version}/${PACKAGE_ID_LOWER}.${version}.nupkg`;
    if (log) log.verbose(`GET ${url}`);
    return httpsGetBuffer(url);
}

// Installs an exact version (already resolved via resolveVariant()) at the
// standard version-keyed cache location. Idempotent - skips the network
// entirely if dxc.exe already exists there. `logger`: see ../common/logger.js.
async function ensureDxcInstalled(version, logger) {
    const log = logger || require('../common/logger').createLogger(false);
    const x64Dir = path.join(versionDir(version), 'x64');
    const dxcExe = dxcPathForVersion(version);
    if (fs.existsSync(dxcExe)) {
        log.info(`already installed: ${x64Dir}`);
        return x64Dir;
    }

    log.info(`installing dxc ${version} to ${x64Dir}`);
    const nupkg = await downloadNupkg(version, log);
    const zip = openNupkg(nupkg);

    fs.mkdirSync(x64Dir, { recursive: true });

    for (const entryPath of ['build/native/bin/x64/dxc.exe', 'build/native/bin/x64/dxcompiler.dll']) {
        const data = zip.read(entryPath);
        if (!data) throw new Error(`"${entryPath}" not found in the ${PACKAGE_ID} ${version} package`);
        const outPath = path.join(x64Dir, path.basename(entryPath));
        fs.writeFileSync(outPath, data);
        log.verbose(`extracted ${entryPath} -> ${outPath} (${data.length} bytes)`);
    }

    // dxil.dll (the DXIL validator/signer) isn't shipped by every version -
    // e.g. the mesh-nodes-preview package has none at all. It's only needed
    // to run the container validator; run-dxc.js passes -Vd (skip
    // validation) when it's absent, so treat this as best-effort.
    const dxilData = zip.read('build/native/bin/x64/dxil.dll');
    if (dxilData) {
        fs.writeFileSync(path.join(x64Dir, 'dxil.dll'), dxilData);
        log.verbose('extracted dxil.dll (validator available)');
    } else {
        log.verbose('no dxil.dll in this package (fine - compiles will pass -Vd to skip validation)');
    }

    fs.writeFileSync(path.join(versionDir(version), 'meta.json'), JSON.stringify({ version, fetchedAt: new Date().toISOString() }, null, 2));

    return x64Dir;
}

module.exports = {
    PACKAGE_ID,
    MESH_PREVIEW_VERSION,
    NAMED_VARIANTS,
    isPrerelease,
    compareVersions,
    listAllVersions,
    resolveLatestStableVersion,
    resolveVariant,
    downloadNupkg,
    ensureDxcInstalled,
};
