// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// `hlsl-workgraph-diagram setup-dxil [mesh | stable | experimental | <version> | list]`
//
// Downloads and caches a dxc build from nuget.org at the standard,
// version-keyed location `hlsl-workgraph-diagram parse-dxil` auto-discovers
// (see ./paths.js) - no dxc install of your own required.
// ---------------------------------------------------------------------------

const { parseArgs, VERBOSE_SPEC } = require('../common/cli-args');
const { createLogger } = require('../common/logger');
const { ensureDxcInstalled, resolveVariant, listAllVersions, isPrerelease, NAMED_VARIANTS } = require('./fetch');
const { dxcPathForVersion, writeAlias, readAliases } = require('./paths');
const fs = require('fs');

function printHelp() {
    console.log(`Usage: hlsl-workgraph-diagram setup-dxil [mesh | stable | experimental | <version> | list]

Downloads and caches a dxc build from nuget.org, keyed by exact version, at
the standard location "parse-dxil" auto-discovers.

Arguments:
  mesh           The one dxc build currently known able to compile a
                 [NodeLaunch("mesh")] node (a pinned, known-good version -
                 see docs/ir-format.md).
  stable         The latest published version with no prerelease tag.
                 Default when no argument is given.
  experimental   The latest published version *with* a prerelease tag -
                 whatever that currently is (historically the same build
                 "mesh" pins to, but not guaranteed to stay that way).
  <version>      An exact version string (e.g. 1.9.2607.13) - use "list"
                 (below) to see what's available.
  list           Print every version NuGet has published for this package,
                 without downloading anything - annotates which are already
                 cached locally and which version "mesh"/"stable"/
                 "experimental" currently resolve to.

Options:
  --verbose, -v    Print the exact HTTP requests made and each extracted
                    file, instead of just the install summary.
  --help, -h, -?   Show this help text and exit.
`);
}

async function run(argv) {
    const { values, positionals, help } = parseArgs(argv, [VERBOSE_SPEC]);
    if (help) {
        printHelp();
        return;
    }
    const log = createLogger(values.verbose);

    const arg = positionals[0] || 'stable';

    if (arg === 'list') {
        log.verbose('GET https://api.nuget.org/v3-flatcontainer/microsoft.direct3d.dxc/index.json');
        const allVersions = await listAllVersions();
        const currentAliases = {};
        for (const name of NAMED_VARIANTS) currentAliases[name] = await resolveVariant(name);
        const cachedAliases = readAliases();

        console.log(`${allVersions.length} version(s) published for Microsoft.Direct3D.DXC:\n`);
        for (const v of allVersions) {
            const tags = [];
            for (const name of NAMED_VARIANTS) if (currentAliases[name] === v) tags.push(name);
            const cachedTag = fs.existsSync(dxcPathForVersion(v)) ? 'cached' : null;
            if (cachedTag) tags.push(cachedTag);
            console.log(`  ${v}${isPrerelease(v) ? ' (prerelease)' : ''}${tags.length ? `  [${tags.join(', ')}]` : ''}`);
        }
        console.log(
            `\nLast installed via setup-dxil: ${
                NAMED_VARIANTS.map((n) => `${n}=${cachedAliases[n] || '(not installed)'}`).join(', ')
            }`
        );
        console.log('\nRun "hlsl-workgraph-diagram setup-dxil <version>" to install a specific one.');
        return;
    }

    if (NAMED_VARIANTS.includes(arg)) log.verbose(`Resolving "${arg}"...`);
    const version = await resolveVariant(arg);
    const dir = await ensureDxcInstalled(version, log);

    if (NAMED_VARIANTS.includes(arg)) {
        writeAlias(arg, version);
        log.info(`"${arg}" -> ${version}`);
    }
    log.info(`dxc ready at: ${dir}`);
    log.info(`(parse-dxil will find it via --dxc-version ${NAMED_VARIANTS.includes(arg) ? arg : version}, or auto-detected if it's mesh/stable)`);
}

module.exports = { run, printHelp };
