// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// Extracts named entries out of a .nupkg (a regular, non-zip64 ZIP archive)
// using only Node builtins (fs, zlib) - no `unzip` binary or npm dependency,
// keeping the "Node builtins only" promise. Reads the central directory
// from the end of the archive (authoritative compressed/uncompressed sizes
// even for the streamed/data-descriptor case) rather than trusting local
// file headers. Ported from the experimental spike's
// tools/extract-nupkg-entries.js.
// ---------------------------------------------------------------------------

const zlib = require('zlib');

const EOCD_SIG = 0x06054b50;
const CDH_SIG = 0x02014b50;
const LFH_SIG = 0x04034b50;

function findEndOfCentralDirectory(buf) {
    // EOCD is at least 22 bytes, and can be followed by up to 65535 bytes of
    // comment, so scan backwards from the end.
    const maxCommentLen = 65535;
    const minPos = Math.max(0, buf.length - 22 - maxCommentLen);
    for (let i = buf.length - 22; i >= minPos; i--) {
        if (buf.readUInt32LE(i) === EOCD_SIG) return i;
    }
    throw new Error('not a valid zip file (no End Of Central Directory record found)');
}

function readCentralDirectory(buf) {
    const eocdPos = findEndOfCentralDirectory(buf);
    const entryCount = buf.readUInt16LE(eocdPos + 10);
    const cdOffset = buf.readUInt32LE(eocdPos + 16);

    const entries = [];
    let pos = cdOffset;
    for (let i = 0; i < entryCount; i++) {
        if (buf.readUInt32LE(pos) !== CDH_SIG) {
            throw new Error(`central directory entry ${i} has a bad signature at offset ${pos}`);
        }
        const method = buf.readUInt16LE(pos + 10);
        const compSize = buf.readUInt32LE(pos + 20);
        const nameLen = buf.readUInt16LE(pos + 28);
        const extraLen = buf.readUInt16LE(pos + 30);
        const commentLen = buf.readUInt16LE(pos + 32);
        const localHeaderOffset = buf.readUInt32LE(pos + 42);
        const name = buf.toString('utf8', pos + 46, pos + 46 + nameLen);

        entries.push({ name, method, compSize, localHeaderOffset });
        pos += 46 + nameLen + extraLen + commentLen;
    }
    return entries;
}

function extractEntry(buf, entry) {
    const pos = entry.localHeaderOffset;
    if (buf.readUInt32LE(pos) !== LFH_SIG) {
        throw new Error(`local file header for "${entry.name}" has a bad signature at offset ${pos}`);
    }
    const nameLen = buf.readUInt16LE(pos + 26);
    const extraLen = buf.readUInt16LE(pos + 28);
    const dataStart = pos + 30 + nameLen + extraLen;
    const compressed = buf.subarray(dataStart, dataStart + entry.compSize);

    if (entry.method === 0) return compressed; // stored, no compression
    if (entry.method === 8) return zlib.inflateRawSync(compressed); // deflate
    throw new Error(`entry "${entry.name}" uses unsupported ZIP compression method ${entry.method}`);
}

// Returns a Map<entryName, () => Buffer> - lazy, since a caller typically
// only wants a handful of entries out of a package with hundreds.
function openNupkg(buf) {
    const entries = readCentralDirectory(buf);
    const byName = new Map(entries.map((e) => [e.name, e]));
    return {
        names: entries.map((e) => e.name),
        has: (name) => byName.has(name),
        read: (name) => {
            const entry = byName.get(name);
            if (!entry) return null;
            return extractEntry(buf, entry);
        },
    };
}

module.exports = { openNupkg };
