// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// The standard cache location setup-dxil installs dxc into, and parse-dxil
// auto-discovers from - keyed by exact nuget version string, so any number
// of versions can be cached side by side:
//
//   ~/.hlsl-workgraph-diagram/dxc/<version>/x64/dxc.exe
//
// The three named variants ("mesh"/"stable"/"experimental" - see fetch.js's
// resolveVariant()) aren't separate cache slots of their own; each resolves
// to a concrete version, which is what actually gets installed/looked up.
// `aliases.json` remembers the last resolution for each name
// (setup-dxil writes it after a successful install), so parse-dxil's
// auto-detection (mesh vs. stable, see ../parse-dxil/run-dxc.js) can find
// "the mesh build" or "the stable build" without re-resolving against
// nuget on every single parse-dxil run.
// ---------------------------------------------------------------------------

const fs = require('fs');
const os = require('os');
const path = require('path');

const CACHE_ROOT = path.join(os.homedir(), '.hlsl-workgraph-diagram', 'dxc');
const ALIASES_FILE = path.join(CACHE_ROOT, 'aliases.json');
const NAMED_VARIANTS = ['mesh', 'stable', 'experimental'];

function versionDir(version) {
    return path.join(CACHE_ROOT, version);
}

function dxcPathForVersion(version) {
    return path.join(versionDir(version), 'x64', 'dxc.exe');
}

function readAliases() {
    try {
        return JSON.parse(fs.readFileSync(ALIASES_FILE, 'utf8'));
    } catch {
        return {};
    }
}

function writeAlias(name, version) {
    const aliases = readAliases();
    aliases[name] = version;
    fs.mkdirSync(CACHE_ROOT, { recursive: true });
    fs.writeFileSync(ALIASES_FILE, JSON.stringify(aliases, null, 2) + '\n', 'utf8');
}

// Resolves a named variant ("mesh"/"stable"/"experimental") to the version
// setup-dxil last installed for it, or null if that variant has never been
// installed. Not meaningful for an explicit version string - callers should
// only use this for the three named variants.
function resolvedAliasVersion(name) {
    return readAliases()[name] || null;
}

module.exports = {
    CACHE_ROOT,
    ALIASES_FILE,
    NAMED_VARIANTS,
    versionDir,
    dxcPathForVersion,
    readAliases,
    writeAlias,
    resolvedAliasVersion,
};
