// ---------------------------------------------------------------------------
// AUTO-GENERATED CONTENT: everything below was generated by Claude Sonnet 5
// (Anthropic), an LLM coding assistant, under end-to-end development
// supervision - it was generated as prompted, code was not adjusted or
// written. Review before relying on it.
// ---------------------------------------------------------------------------
#ifndef SIMPLE_PIPELINE_NODES_COMPUTE_COLLECTNODE_HLSL
#define SIMPLE_PIPELINE_NODES_COMPUTE_COLLECTNODE_HLSL
#include "../structs/Records.hlsl"

#define COLLECT_THREADS 32

// Gathers up to 64 ResultRecords per invocation. Terminal node - no output.
[Shader("node")]
[NodeLaunch("coalescing")]
[NumThreads(COLLECT_THREADS, 1, 1)]
void CollectNode(
    uint gtid : SV_GroupThreadID,

    [MaxRecords(64)]
    GroupNodeInputRecords<ResultRecord> results
)
{
}

#endif
