// ---------------------------------------------------------------------------
// AUTO-GENERATED CONTENT: everything below was generated by Claude Sonnet 5
// (Anthropic), an LLM coding assistant, under end-to-end development
// supervision - it was generated as prompted, code was not adjusted or
// written. Review before relying on it.
// ---------------------------------------------------------------------------
// Fixture developed for/used to verify parse-dxil - see docs/ir-format.md.
// Mirrors examples/mesh-culling/structs/Globals.hlsl:
// one global resource, read by exactly one node, to validate that per-node
// global-resource-usage extraction actually works against a real dxc
// compile (not just in theory).
// ---------------------------------------------------------------------------
#ifndef EXPERIMENTAL_STRUCTS_GLOBALS_HLSL
#define EXPERIMENTAL_STRUCTS_GLOBALS_HLSL

struct ItemMeta
{
    uint tag;
};

StructuredBuffer<ItemMeta> itemMeta : register(t0);

#endif
