// ---------------------------------------------------------------------------
// AUTO-GENERATED CONTENT: everything below was generated by Claude Sonnet 5
// (Anthropic), an LLM coding assistant, under end-to-end development
// supervision - it was generated as prompted, code was not adjusted or
// written. Review before relying on it.
// ---------------------------------------------------------------------------
// Fixture developed for/used to verify parse-dxil - see docs/ir-format.md.
// ---------------------------------------------------------------------------
// Include guard, not #pragma once — see structs/Records.hlsl for why.
#ifndef EXPERIMENTAL_STRUCTS_VERTEXTYPES_HLSL
#define EXPERIMENTAL_STRUCTS_VERTEXTYPES_HLSL

// Consumed by RenderMeshNode (only compiled when ENABLE_MESH_PATH is set,
// see WorkGraph.hlsl) — one record per broadcasting dispatch grid cell.
// SV_DispatchGrid is required on a [NodeMaxDispatchGrid(...)] node's input
// record — it's how the runtime dispatch grid size is actually supplied;
// another real finding from running dxc, see experimental/README.md.
struct MeshInputRecord
{
    uint3 dispatchGrid : SV_DispatchGrid;
};

struct Vertex
{
    float4 position : SV_Position;
    float3 normal : NORMAL;
};

#endif
