#!/usr/bin/env node
// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// Top-level subcommand dispatcher. `hlsl-workgraph-diagram <command> [args]`
// - five independent pipeline stages (see docs/architecture.md), each its
// own module under src/:
//
//   setup-dxil    fetch a dxc build, for parse-dxil to use
//   parse-source  HLSL source (regex scan)  -> IR JSON
//   parse-dxil    HLSL source (dxc compile) -> IR JSON
//   build-puml    IR JSON -> .puml
//   puml-render   .puml -> .png + .svg
//
// This is a breaking change from v1's single all-in-one CLI invocation
// (`hlsl-workgraph-diagram rootDir outFile [options]`) - see the root
// README's Migrating from v1 section.
// ---------------------------------------------------------------------------

const COMMANDS = {
    'setup-dxil': () => require('./setup-dxil'),
    'parse-source': () => require('./parse-source'),
    'parse-dxil': () => require('./parse-dxil'),
    'build-puml': () => require('./build-puml'),
    'puml-render': () => require('./puml-render'),
};

const COMMAND_ORDER = ['setup-dxil', 'parse-source', 'parse-dxil', 'build-puml', 'puml-render'];

const SUMMARIES = {
    'setup-dxil': 'Download and cache a dxc build for parse-dxil to use.',
    'parse-source': 'Scan HLSL source (regex/paren-balance) into the shared IR JSON.',
    'parse-dxil': 'Compile HLSL with dxc and read the shared IR JSON back out of the DXIL metadata.',
    'build-puml': 'Render the IR JSON as a PlantUML (.puml) diagram.',
    'puml-render': 'Render a .puml file to .png/.svg via a PlantUML server.',
};

function printTopHelp() {
    console.log(`Usage: hlsl-workgraph-diagram <command> [args...]

Commands:
${COMMAND_ORDER.map((c) => `  ${c.padEnd(14)} ${SUMMARIES[c]}`).join('\n')}

Run "hlsl-workgraph-diagram <command> --help" for a command's own arguments
and options.

A typical pipeline:
  hlsl-workgraph-diagram parse-source ./shaders work-graph.ir.json
  hlsl-workgraph-diagram build-puml work-graph.ir.json work-graph.puml
  hlsl-workgraph-diagram puml-render work-graph.puml

Or, using the dxc-based parser instead of the regex scanner:
  hlsl-workgraph-diagram setup-dxil
  hlsl-workgraph-diagram parse-dxil ./shaders/WorkGraph.hlsl work-graph.ir.json
  hlsl-workgraph-diagram build-puml work-graph.ir.json work-graph.puml
  hlsl-workgraph-diagram puml-render work-graph.puml
`);
}

async function main(argv) {
    const [cmd, ...rest] = argv;
    if (!cmd || cmd === '--help' || cmd === '-h' || cmd === '-?') {
        printTopHelp();
        process.exitCode = cmd ? 0 : 1;
        return;
    }
    if (!COMMANDS[cmd]) {
        console.error(`Unknown command: ${cmd}\n`);
        printTopHelp();
        process.exitCode = 1;
        return;
    }
    await COMMANDS[cmd]().run(rest);
}

module.exports = { main, printTopHelp };

if (require.main === module) {
    main(process.argv.slice(2)).catch((err) => {
        console.error(err.stack || err.message || err);
        process.exit(1);
    });
}
