// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

function parseArgs(argv) {
    const positionals = [];
    let render = true;
    let scale = 2;
    let server = 'https://www.plantuml.com/plantuml';
    let dark = false;
    let help = false;
    let shortRecordOutCount = false;
    let shortRecordInCount = false;
    let shortGridThreadsCount = false;
    let shortMeta = false;
    let short = false;
    let edgeLabel = true;
    let globalBoxes = false;
    let globalList = true;
    let recordInNames = false;
    let recordOutNames = false;
    for (let i = 0; i < argv.length; i++) {
        const a = argv[i];
        if (a === '--render') render = true;
        else if (a === '--no-render') render = false;
        else if (a === '--scale') scale = parseFloat(argv[++i]);
        else if (a.startsWith('--scale=')) scale = parseFloat(a.slice('--scale='.length));
        else if (a === '--server') server = argv[++i];
        else if (a.startsWith('--server=')) server = a.slice('--server='.length);
        else if (a === '--dark') dark = true;
        else if (a === '--light') dark = false;
        else if (a === '--short-record-out-count') shortRecordOutCount = true;
        else if (a === '--short-record-in-count') shortRecordInCount = true;
        else if (a === '--short-grid-threads-count') shortGridThreadsCount = true;
        else if (a === '--short-meta') shortMeta = true;
        else if (a === '--short') short = true;
        else if (a === '--edge-label') edgeLabel = true;
        else if (a === '--no-edge-label') edgeLabel = false;
        else if (a === '--global-boxes') globalBoxes = true;
        else if (a === '--no-global-boxes') globalBoxes = false;
        else if (a === '--global-list') globalList = true;
        else if (a === '--no-global-list') globalList = false;
        else if (a === '--record-in-names') recordInNames = true;
        else if (a === '--no-record-in-names') recordInNames = false;
        else if (a === '--record-out-names') recordOutNames = true;
        else if (a === '--no-record-out-names') recordOutNames = false;
        else if (a === '--help' || a === '-h' || a === '-?') help = true;
        else positionals.push(a);
    }
    return {
        positionals,
        render,
        scale,
        server,
        dark,
        help,
        shortRecordOutCount,
        shortRecordInCount,
        shortGridThreadsCount,
        shortMeta,
        short,
        edgeLabel,
        globalBoxes,
        globalList,
        recordInNames,
        recordOutNames,
    };
}

function printHelp() {
    console.log(`Usage: node generate-workgraph-diagram.js [rootDir] [outFile] [options]

Recursively searches rootDir for "nodes-*" directories, scans the HLSL files
inside for work-graph node functions ([Shader("node")]), and emits a
PlantUML dependency diagram of their NodeInput/NodeOutput records.

Arguments:
  rootDir   Directory to search for nodes-* dirs in.
            Default: current working directory.
  outFile   Path to write the .puml file to - relative (resolved against
            the current working directory) or absolute. ".puml" is appended
            automatically if not already present.
            Default: work-graph.puml, in the current working directory.

Options:
  --render / --no-render          Render .png + .svg via a PlantUML server
                                   next to outFile. Default: --render (on).
  --scale <multiplier>            Render scale multiplier, embedded in the
                                   .puml as PlantUML's own "scale <n>"
                                   directive (e.g. 2 = double resolution).
                                   Raises the rendered .png's pixel
                                   resolution proportionally (higher-DPI
                                   output); .svg is vector so this mainly
                                   affects its declared width/height.
                                   Default: 2.
  --server <url>                  PlantUML server base URL.
                                   Default: https://www.plantuml.com/plantuml
  --dark / --light                Diagram color theme. Default: --light.
  --short-record-out-count        Show only the calculated record count in
                                   a node's "Record out:" list (e.g. "(192)")
                                   instead of the full formula with "= 192".
                                   Falls back to the full formula when the
                                   count can't be fully resolved.
  --short-record-in-count         Same as --short-record-out-count, but for
                                   the "Record in:" line.
  --short-grid-threads-count      Show only the calculated per-axis values
                                   in Grid:/Threads: (e.g. "(32, 1, 1)")
                                   instead of "(QMSN_THREADS (32), 1, 1)".
  --short-meta                    Implies --short-grid-threads-count, and
                                   collapses Depth:/Grid:/Threads: into one
                                   smaller-font line. Drops Grid: entirely
                                   for launch modes that can't configure it
                                   (coalescing, thread), and Threads: for
                                   thread-launch nodes (always exactly 1).
  --short                         Shorthand for all four --short-* flags
                                   above at once.
  --edge-label / --no-edge-label  Show the record type/variable/count note
                                   on each edge. Default: --edge-label (on).
  --global-boxes / --no-global-boxes
                                   Show a box per global resource (root
                                   descriptor / StructuredBuffer / etc,
                                   anything declared with ": register(tN)")
                                   plus dashed edges from each global into
                                   the node(s) that read it, replicated once
                                   per node-group to avoid long cross-diagram
                                   edges. Default: --no-global-boxes (off) -
                                   the global resource table in the legend
                                   already lists every global either way.
  --global-list / --no-global-list
                                   Show the "Globals used:" list in a node's
                                   body for globals referenced in its HLSL
                                   function body. Default: on. Independent of
                                   --global-boxes - either can be off alone.
  --record-in-names / --no-record-in-names
                                   Show the input record's variable name
                                   alongside its type in a node's "Record
                                   in:" line (e.g. "quadsInput <<QuadRecord>>"
                                   instead of just "<<QuadRecord>>"), the
                                   same idea as identifiers in "Globals
                                   used:". Default: off.
  --record-out-names / --no-record-out-names
                                   Same as --record-in-names, but for each
                                   line of a node's "Record out:" list.
                                   Default: off.
  --help, -h, -?                   Show this help text and exit.
`);
}

module.exports = { parseArgs, printHelp };
