// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// Constant resolution: #define / static const scanned across the *whole*
// shaders tree (not just nodes-*), so identifiers like CUBOID_FACES or
// MAX_GLYPHS_PER_RENDER_RECORD (declared in utilities/ or structs/) resolve.
// ---------------------------------------------------------------------------

const fs = require('fs');
const { listHlslFiles } = require('./discovery');
const { stripComments } = require('./comments');
const { SHORT_GRID_THREADS_COUNT } = require('./options');

function collectConstants(rootDir) {
    const table = new Map();
    for (const file of listHlslFiles(rootDir)) {
        const stripped = stripComments(fs.readFileSync(file, 'utf8')).text;

        const defineRe = /^[ \t]*#define[ \t]+([A-Za-z_]\w*)[ \t]+(.+?)[ \t]*$/gm;
        let m;
        while ((m = defineRe.exec(stripped)) !== null) {
            table.set(m[1], m[2].trim());
        }

        const constRe = /static\s+const\s+[\w:<>]+\s+([A-Za-z_]\w*)\s*=\s*([^;]+);/g;
        while ((m = constRe.exec(stripped)) !== null) {
            table.set(m[1], m[2].trim());
        }
    }
    return table;
}

// Resolves an arithmetic expression to a number by iteratively substituting
// known identifiers, then safely evaluating the fully-numeric result.
// Returns null if any identifier stays unresolved or the result isn't a
// finite number.
function resolveExpr(expr, table) {
    let current = expr;
    for (let i = 0; i < 8; i++) {
        let changed = false;
        const next = current.replace(/\b[A-Za-z_]\w*\b/g, (id) => {
            if (table.has(id)) {
                changed = true;
                return `(${table.get(id)})`;
            }
            return id;
        });
        current = next;
        if (!changed) break;
    }

    const withoutHexLiterals = current.replace(/0[xX][0-9a-fA-F]+/g, '0');
    if (/[A-Za-z_]/.test(withoutHexLiterals)) return null; // still unresolved identifiers
    if (!/[0-9]/.test(current)) return null;
    if (!/^[\s0-9+\-*/().xXa-fA-F]+$/.test(current)) return null; // safety whitelist

    try {
        // eslint-disable-next-line no-new-func
        const val = Function(`"use strict"; return (${current});`)();
        return typeof val === 'number' && Number.isFinite(val) ? val : null;
    } catch {
        return null;
    }
}

// Replaces every identifier token inside `text` with "IDENT (value)" or
// "IDENT (?)" when it can't be resolved. Leaves pure numeric text alone.
function annotateIdentifiers(text, table) {
    return text.replace(/\b[A-Za-z_]\w*\b/g, (id) => {
        const resolved = table.has(id) ? resolveExpr(id, table) : null;
        return resolved !== null ? `${id} (${resolved})` : `${id} (?)`;
    });
}

function annotateExpr(exprStr, table) {
    if (!exprStr) return exprStr;
    return /[A-Za-z_]/.test(exprStr) ? annotateIdentifiers(exprStr, table) : exprStr;
}

// For comma-separated triples (NumThreads/NodeDispatchGrid/NodeMaxDispatchGrid
// args): annotate identifiers component-by-component so e.g. "QMSN_THREADS, 1, 1"
// becomes "QMSN_THREADS (32), 1, 1" instead of evaluating the triple as one
// (meaningless) expression.
function annotateTriple(argsStr, table) {
    return argsStr
        .split(',')
        .map((t) => annotateExpr(t.trim(), table))
        .join(', ');
}

// --short-grid-threads-count variant: each axis shows only its resolved
// number (e.g. "32" instead of "QMSN_THREADS (32)"), falling back to the
// annotated identifier form for an axis that doesn't resolve.
function annotateTripleShort(argsStr, table) {
    return argsStr
        .split(',')
        .map((t) => {
            const trimmed = t.trim();
            const resolved = resolveExpr(trimmed, table);
            return resolved !== null ? String(resolved) : annotateExpr(trimmed, table);
        })
        .join(', ');
}

function annotateTripleForDisplay(argsStr, table) {
    return SHORT_GRID_THREADS_COUNT ? annotateTripleShort(argsStr, table) : annotateTriple(argsStr, table);
}

// Appends " = <value>" for a triple whose axes fully resolve to numbers,
// i.e. the actual dispatch/thread-group count once multiplied out - skipped
// whenever at least two of the three axes are literally "1", since the
// product then trivially equals the one remaining axis (already visible)
// and adds nothing; also skipped when the triple doesn't fully resolve.
function tripleTotalSuffix(argsStr, table) {
    const parts = argsStr.split(',').map((p) => p.trim());
    if (parts.length !== 3) return '';
    const literalOnes = parts.filter((p) => p === '1').length;
    if (literalOnes >= 2) return '';
    let product = 1;
    for (const p of parts) {
        const val = resolveExpr(p, table);
        if (val === null) return '';
        product *= val;
    }
    return ` = ${product}`;
}

// Same idea for a single arithmetic expression (MaxRecords/MaxRecordsSharedWith):
// skipped for a bare integer literal (nothing to simplify) or when it doesn't
// fully resolve.
function exprTotalSuffix(exprStr, table) {
    if (!exprStr || /^\s*\d+\s*$/.test(exprStr)) return '';
    const resolved = resolveExpr(exprStr, table);
    return resolved !== null ? ` = ${resolved}` : '';
}

// Greys out standalone "1" digits (not part of a larger number or identifier)
// to signal an unused/default axis, e.g. in "(64, 1, 1)".
function greyOnes(text, greyColor) {
    return text.replace(/\b1\b/g, `<color:${greyColor}>1</color>`);
}

module.exports = {
    collectConstants,
    resolveExpr,
    annotateIdentifiers,
    annotateExpr,
    annotateTriple,
    annotateTripleShort,
    annotateTripleForDisplay,
    tripleTotalSuffix,
    exprTotalSuffix,
    greyOnes,
};
