// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// Graph depth: longest-path distance (in edges) from any entry node
// (NodeIsProgramEntry), taken over *all* paths that reach a node - what
// actually matters against the D3D12 work-graph's hard 32-depth limit, since
// a node's real depth is bounded by its worst-case (deepest) producer chain,
// not merely its shortest one. Computed via bounded relaxation (Bellman-Ford
// style: relax every edge, repeat up to nodeCount times, stop early once
// nothing changes) rather than a topological sort, since it's small and this
// also tolerates self-recursion edges without extra bookkeeping - those are
// simply excluded from relaxation so a node recursing into itself doesn't
// inflate its own depth every pass.
// ---------------------------------------------------------------------------

function computeDepths(nodes, edges) {
    const depths = new Map();
    for (const n of nodes) {
        if (n.isEntry) depths.set(n.id, 0);
    }

    const forwardEdges = edges.filter((e) => e.from !== e.to);
    for (let pass = 0; pass < nodes.length + 1; pass++) {
        let changed = false;
        for (const e of forwardEdges) {
            if (!depths.has(e.from)) continue;
            const candidate = depths.get(e.from) + 1;
            if (!depths.has(e.to) || candidate > depths.get(e.to)) {
                depths.set(e.to, candidate);
                changed = true;
            }
        }
        if (!changed) break;
    }
    return depths;
}

module.exports = { computeDepths };
