// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

const fs = require('fs');
const path = require('path');

const {
    ROOT_DIR,
    OUT_FILE,
    RENDER_ENABLED,
    PLANTUML_SERVER,
    DARK_MODE,
    GLOBALS_NEEDED,
} = require('./options');
const { findNodeDirs, listHlslFiles } = require('./discovery');
const { stripComments } = require('./comments');
const { extractNodes } = require('./nodes');
const { collectConstants } = require('./constants');
const { collectGlobals, isGlobalUsedInBody } = require('./globals');
const { computeDepths } = require('./graph');
const { renderPlantUml } = require('./render/plantuml-document');
const { renderWithPlantumlServer } = require('./plantuml-server');

async function main() {
    console.error(`Searching for nodes-* directories under: ${ROOT_DIR}`);
    const nodeDirs = findNodeDirs(ROOT_DIR);
    if (nodeDirs.length === 0) {
        console.error(`No "nodes-*" directories found under ${ROOT_DIR}`);
        process.exit(1);
    }
    console.error(
        `Found ${nodeDirs.length} nodes-* director${nodeDirs.length === 1 ? 'y' : 'ies'}: ` +
            nodeDirs.map((d) => path.relative(ROOT_DIR, d) || '.').join(', ')
    );

    const constants = collectConstants(ROOT_DIR);

    const files = [];
    for (const nodesDir of nodeDirs) {
        const group = path.basename(nodesDir);
        for (const f of listHlslFiles(nodesDir)) files.push({ file: f, group });
    }
    files.sort((a, b) => a.file.localeCompare(b.file));

    const allNodes = [];
    for (const { file, group } of files) {
        const raw = fs.readFileSync(file, 'utf8');
        const { text: stripped, rawIndex } = stripComments(raw);
        const relPath = path.relative(ROOT_DIR, file).replace(/\\/g, '/');
        const nodes = extractNodes(stripped, relPath, raw, rawIndex, group, GLOBALS_NEEDED);
        allNodes.push(...nodes);
    }

    const nodesById = new Map();
    for (const n of allNodes) {
        if (nodesById.has(n.id)) {
            console.error(`Warning: duplicate node id "${n.id}" (${nodesById.get(n.id).file} and ${n.file})`);
        }
        nodesById.set(n.id, n);
    }

    // Edges: one per output parameter.
    const edges = [];
    for (const n of allNodes) {
        for (const out of n.outputs) {
            edges.push({
                from: n.id,
                to: out.targetId,
                varName: out.varName,
                recordType: out.recordType,
                recordKind: out.recordKind,
                maxRecords: out.maxRecords,
                maxRecordsSharedWith: out.maxRecordsSharedWith,
            });
        }
    }

    // Any edge target that isn't a scanned node function becomes an
    // "external" placeholder node so the diagram still renders it.
    const externalIds = new Set();
    for (const e of edges) {
        if (!nodesById.has(e.to)) externalIds.add(e.to);
    }

    const depths = computeDepths(allNodes, edges);
    for (const n of allNodes) n.depth = depths.has(n.id) ? depths.get(n.id) : null;

    const globalsIndex = GLOBALS_NEEDED ? collectGlobals(ROOT_DIR) : new Map();
    if (GLOBALS_NEEDED && globalsIndex.size > 0) {
        // Pre-sorted once by (regType, regSlot) - "t3 before t5" - so every
        // node's filtered globalsUsed list inherits that order for free.
        const globalsBySlot = [...globalsIndex.values()].sort(
            (a, b) => a.regType.localeCompare(b.regType) || a.regSlot - b.regSlot
        );
        for (const n of allNodes) {
            n.globalsUsed = n.bodyText
                ? globalsBySlot.filter((g) => isGlobalUsedInBody(n.bodyText, g.name)).map((g) => g.name)
                : [];
        }
    } else {
        for (const n of allNodes) n.globalsUsed = [];
    }

    console.error(
        `Scanned ${files.length} file(s), found ${allNodes.length} node function(s), ${edges.length} edge(s), ${externalIds.size} external reference(s), ${globalsIndex.size} global resource(s).`
    );

    const puml = renderPlantUml(allNodes, edges, externalIds, constants, DARK_MODE, globalsIndex);
    fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
    fs.writeFileSync(OUT_FILE, puml, 'utf8');
    console.error(`Wrote ${OUT_FILE}`);

    if (RENDER_ENABLED) {
        const outBase = OUT_FILE.replace(/\.puml$/i, '');
        try {
            await renderWithPlantumlServer(puml, outBase, PLANTUML_SERVER);
            console.error(`Rendered ${outBase}.png and ${outBase}.svg via ${PLANTUML_SERVER}`);
        } catch (err) {
            console.error(
                `Warning: PlantUML server rendering failed (${err.message}). ` +
                    'The .puml file was still written and is valid - this is a rendering-service limitation, ' +
                    'not a syntax error. For a large/detailed diagram, the public PlantUML server has been ' +
                    'observed to fail past a certain accumulated complexity (see Known limitations in ' +
                    'generate-workgraph-diagram.md); try re-running with --short and/or --no-edge-label to ' +
                    'reduce it, or render the .puml manually via a local PlantUML install (e.g. plantuml.jar, ' +
                    "the VS Code PlantUML extension), or re-run with --no-render to skip this step."
            );
        }
    }
}

module.exports = main;

// Self-executing on require, matching the original single-file script's
// unconditional `main().catch(...)` at the bottom - this module is only
// ever required once, by the thin CLI entry script.
main().catch((err) => {
    console.error(err.stack || err.message || err);
    process.exit(1);
});
