// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// Single source of truth for CLI-derived flags. Every other module that
// needs one of these `require('./options')` instead of relying on
// same-file globals (the original monolith's approach) - the read call
// sites stay exactly as they were, just moved behind a require().

const path = require('path');
const { parseArgs, printHelp } = require('./cli');

const CLI = parseArgs(process.argv.slice(2));

if (CLI.help) {
    printHelp();
    process.exit(0);
}

const ROOT_DIR = path.resolve(CLI.positionals[0] || process.cwd());
// Output location: outFile defaults to work-graph.puml, and is resolved
// against the current working directory when relative - path.resolve()
// does exactly this already (an absolute input passes through unchanged,
// a relative one is joined onto process.cwd()). ".puml" is appended if not
// already present, so a bare name like "wow/test" becomes "wow/test.puml"
// (and the wow/ subdirectory is created later in index.js if needed).
const outFileArg = CLI.positionals[1] || 'work-graph.puml';
const outFileWithExt = /\.puml$/i.test(outFileArg) ? outFileArg : `${outFileArg}.puml`;
const OUT_FILE = path.resolve(outFileWithExt);
const RENDER_ENABLED = CLI.render;
// Falls back to the default of 2 (rather than silently using NaN/0, which
// PlantUML would reject) if --scale was given something non-numeric or
// non-positive.
const SCALE_MULTIPLIER = Number.isFinite(CLI.scale) && CLI.scale > 0 ? CLI.scale : 2;
if (CLI.scale !== SCALE_MULTIPLIER) {
    console.error(`Warning: ignoring invalid --scale value (${CLI.scale}); using ${SCALE_MULTIPLIER} instead.`);
}
const PLANTUML_SERVER = CLI.server.replace(/\/+$/, '');
const DARK_MODE = CLI.dark;
// --short enables all four --short-* flags; --short-meta additionally
// implies --short-grid-threads-count (its combined line is meaningless
// without the short per-axis numbers).
const SHORT_META = CLI.shortMeta || CLI.short;
const SHORT_RECORD_OUT_COUNT = CLI.shortRecordOutCount || CLI.short;
const SHORT_RECORD_IN_COUNT = CLI.shortRecordInCount || CLI.short;
const SHORT_GRID_THREADS_COUNT = CLI.shortGridThreadsCount || SHORT_META;
const EDGE_LABELS_ENABLED = CLI.edgeLabel;
const GLOBAL_BOXES_ENABLED = CLI.globalBoxes;
const GLOBAL_LIST_ENABLED = CLI.globalList;
// When neither display is on, skip building the global index and scanning
// node bodies for usage entirely - there'd be nothing to do with the result.
const GLOBALS_NEEDED = GLOBAL_BOXES_ENABLED || GLOBAL_LIST_ENABLED;
const RECORD_IN_NAMES_ENABLED = CLI.recordInNames;
const RECORD_OUT_NAMES_ENABLED = CLI.recordOutNames;

module.exports = {
    CLI,
    ROOT_DIR,
    OUT_FILE,
    RENDER_ENABLED,
    SCALE_MULTIPLIER,
    PLANTUML_SERVER,
    DARK_MODE,
    SHORT_META,
    SHORT_RECORD_OUT_COUNT,
    SHORT_RECORD_IN_COUNT,
    SHORT_GRID_THREADS_COUNT,
    EDGE_LABELS_ENABLED,
    GLOBAL_BOXES_ENABLED,
    GLOBAL_LIST_ENABLED,
    GLOBALS_NEEDED,
    RECORD_IN_NAMES_ENABLED,
    RECORD_OUT_NAMES_ENABLED,
};
