// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// Color themes
// ---------------------------------------------------------------------------

const THEMES = {
    light: {
        canvasBg: null,
        packageBg: null,
        legendBg: null,
        fontColor: '#1A1A1A',
        arrowColor: '#555555',
        arrowFontColor: '#333333',
        rectBorder: '#555555',
        packageBorder: '#555555',
        legendBorder: '#555555',
        broadcasting: '#CFE8FF',
        coalescing: '#FFF3B0',
        thread: '#D9F2D9',
        mesh: '#F5CFEA',
        unknown: '#EEEEEE',
        external: '#F2F2F2',
        entryBorder: '#C0392B',
        greyOne: '#8A8A8A',
        recordHighlight: '#8E44AD',
        nodeNameHighlight: '#1A5276',
        globalBg: '#F5EBD8',
        globalBorder: '#9C7A3C',
        globalHighlight: '#8A6D3B',
        noteBg: '#FBFBFB',
        noteBorder: '#999999',
    },
    dark: {
        canvasBg: '#1E1E1E',
        packageBg: '#242424',
        legendBg: '#242424',
        fontColor: '#E4E4E4',
        arrowColor: '#AAAAAA',
        arrowFontColor: '#CCCCCC',
        rectBorder: '#999999',
        packageBorder: '#999999',
        legendBorder: '#999999',
        broadcasting: '#28486B',
        coalescing: '#6B5A17',
        thread: '#2E5138',
        mesh: '#5A2E52',
        unknown: '#3A3A3A',
        external: '#2A2A2A',
        entryBorder: '#FF6B5B',
        greyOne: '#8F8F8F',
        recordHighlight: '#C39BD3',
        nodeNameHighlight: '#7FB3D5',
        globalBg: '#3A2F1E',
        globalBorder: '#B79B6B',
        globalHighlight: '#D4B483',
        noteBg: '#2A2A2A',
        noteBorder: '#777777',
    },
};

module.exports = { THEMES };
