// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// Tiny declarative flag parser shared by every subcommand's own CLI module -
// not a general-purpose CLI framework (no deps, per the root README's "Node
// builtins only" promise), just the `--flag value` / `--flag=value` /
// `--no-flag` / bare-positional pattern every subcommand already needed,
// pulled out once instead of five near-identical copies of the same loop.
//
// specs: array of { name, flag, negFlag?, type: 'boolean'|'string'|'number', default }.
// `--help`/`-h`/`-?` is always recognized and reported back as `help`, same
// as every subcommand already did individually.
function parseArgs(argv, specs) {
    const values = {};
    for (const spec of specs) values[spec.name] = spec.default;
    const positionals = [];
    let help = false;

    for (let i = 0; i < argv.length; i++) {
        const a = argv[i];
        if (a === '--help' || a === '-h' || a === '-?') {
            help = true;
            continue;
        }

        let matched = false;
        for (const spec of specs) {
            if (a === spec.flag) {
                if (spec.type === 'boolean') values[spec.name] = true;
                else values[spec.name] = spec.type === 'number' ? parseFloat(argv[++i]) : argv[++i];
                matched = true;
                break;
            }
            if (spec.negFlag && a === spec.negFlag) {
                values[spec.name] = false;
                matched = true;
                break;
            }
            if (spec.flag && a.startsWith(spec.flag + '=')) {
                const raw = a.slice(spec.flag.length + 1);
                values[spec.name] = spec.type === 'number' ? parseFloat(raw) : raw;
                matched = true;
                break;
            }
        }
        if (!matched) positionals.push(a);
    }

    return { values, positionals, help };
}

module.exports = { parseArgs };
