// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM generated by iteratively
// prompt-review cycling the result. None of the code or any of the
// documentation was written by hand. REVIEW THE CODE AND ITS BEHAVIOR BEFORE
// RELYING ON IT.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// A dispatch plan describes what HLSL cannot: the host-side sequence of
// DispatchGraph calls in one frame - which entrypoint each starts at, under
// which program - see docs/dispatch-plan.md. This module holds the analysis
// shared by build-puml (--dispatches) and validate: per-dispatch reachable
// subgraphs, statically dead edges, and per-dispatch resource access.
// Parser-agnostic: it only reads IR fields, and treats the optional ones
// (globalAccess, output allocation) as absent rather than failing.
// ---------------------------------------------------------------------------

const fs = require('fs');
const path = require('path');
const { readIrFile } = require('./ir');

// "auto": a plan inferred from the graph alone - one dispatch per [NodeIsProgramEntry] node. The
// dispatch ORDER is host code, so it is unknown here and order-dependent checks are skipped.
function autoPlan(nodes) {
    const entries = nodes.filter((n) => n.isEntry).map((n) => n.id).sort();
    return {
        auto: true,
        title: 'One dispatch per program entry (inferred; order unknown)',
        dispatches: entries.map((id, i) => ({ id: String.fromCharCode(65 + i), label: id, entry: id })),
    };
}

function loadPlan(file, nodes) {
    if (file === 'auto') return autoPlan(nodes || []);
    const plan = JSON.parse(fs.readFileSync(file, 'utf8'));
    if (!Array.isArray(plan.dispatches) || plan.dispatches.length === 0) {
        throw new Error(`${file}: "dispatches" must be a non-empty array`);
    }
    for (const d of plan.dispatches) {
        if (!d.id || !d.entry) throw new Error(`${file}: every dispatch needs "id" and "entry"`);
        // A dispatch compiled with its own #defines brings its own IR (relative to the plan file).
        if (d.ir) d.irData = readIrFile(path.resolve(path.dirname(file), d.ir));
    }
    return plan;
}

function buildEdges(nodes) {
    const edges = [];
    for (const n of nodes) {
        n.outputs.forEach((out, outputIndex) => {
            if (!out.linkedNodeID) return;
            const alloc = out.allocation;
            // Every allocation site is the literal 0: the edge is declared but never carries a record.
            const dead = !!alloc && alloc.dynamicCount === 0 && alloc.constCounts.length > 0 && alloc.constCounts.every((c) => c === 0);
            edges.push({
                from: n.id,
                to: out.linkedNodeID.name,
                outputIndex,
                varName: out.varName,
                recordType: out.recordType,
                recordKind: out.recordKind,
                recordSizeBytes: out.recordSizeBytes ?? null,
                maxRecords: out.maxRecords,
                maxRecordsSharedWith: out.maxRecordsSharedWith,
                allocation: alloc || null,
                dead,
            });
        });
    }
    return edges;
}

// Nodes reachable from `entry`, longest-path depth from it, and which of
// them are reachable only through dead edges (declared, but never launched).
function analyseDispatch(entry, nodesById, edges) {
    const reach = (useDead) => {
        const seen = new Set([entry]);
        const queue = [entry];
        while (queue.length) {
            const id = queue.shift();
            for (const e of edges) {
                if (e.from !== id || (!useDead && e.dead) || seen.has(e.to)) continue;
                seen.add(e.to);
                queue.push(e.to);
            }
        }
        return seen;
    };
    const all = reach(true);
    const live = reach(false);
    const depth = new Map([[entry, 0]]);
    const inScope = edges.filter((e) => all.has(e.from) && e.from !== e.to);
    for (let pass = 0; pass <= all.size; pass++) {
        let changed = false;
        for (const e of inScope) {
            if (!depth.has(e.from)) continue;
            const d = depth.get(e.from) + 1;
            if (!depth.has(e.to) || d > depth.get(e.to)) {
                depth.set(e.to, d);
                changed = true;
            }
        }
        if (!changed) break;
    }
    return {
        nodeIds: [...all].filter((id) => nodesById.has(id)),
        liveIds: live,
        deadIds: new Set([...all].filter((id) => !live.has(id))),
        edges: inScope,
        depth,
    };
}

// { resourceName: { readers: [nodeId], writers: [...], atomics: [...], queries: [...] } }
// over the LIVE nodes of one dispatch.
function dispatchAccess(analysis, nodesById) {
    const acc = {};
    for (const id of analysis.liveIds) {
        const n = nodesById.get(id);
        if (!n || !n.globalAccess) continue;
        for (const [res, label] of Object.entries(n.globalAccess)) {
            const a = (acc[res] = acc[res] || { readers: [], writers: [], atomics: [], queries: [] });
            const parts = label.split('+');
            if (parts.includes('read')) a.readers.push(id);
            if (parts.includes('write')) a.writers.push(id);
            if (parts.includes('atomic')) a.atomics.push(id);
            if (parts.includes('query')) a.queries.push(id);
        }
    }
    return acc;
}

function analysePlan(plan, nodes, recordTypes) {
    const nodesById = new Map(nodes.map((n) => [n.id, n]));
    const dispatches = plan.dispatches.map((d) => {
        const dNodes = d.irData ? d.irData.nodes : nodes;
        const dById = new Map(dNodes.map((n) => [n.id, n]));
        for (const n of dNodes) if (!nodesById.has(n.id)) nodesById.set(n.id, n);
        const dEdges = buildEdges(dNodes);
        const analysis = analyseDispatch(d.entry, dById, dEdges);
        const types = (d.irData && d.irData.recordTypes) || recordTypes || {};
        return { ...d, nodesById: dById, edges: dEdges, analysis, access: dispatchAccess(analysis, dById), entryRecordImpact: entryRecordImpact(d, dById, types) };
    });
    return { nodesById, edges: buildEdges(nodes), dispatches };
}

// For every pinned entry-record field: what it influences inside the dispatch, following its value
// through the record fields it is copied into (DXIL dataflow; no constant folding of the value).
function entryRecordImpact(d, nodesById, types) {
    if (!d.entryRecord || typeof d.entryRecord !== 'object') return null;
    const entry = nodesById.get(d.entry);
    const typeName = entry && entry.inputs[0] && entry.inputs[0].recordType;
    const out = {};
    for (const field of Object.keys(d.entryRecord)) {
        const impact = { controls: new Set(), counts: new Set(), indexes: new Set(), copiedTo: new Set() };
        const seen = new Set();
        const queue = [`${typeName}.${field}`];
        while (queue.length) {
            const key = queue.shift();
            if (seen.has(key)) continue;
            seen.add(key);
            const [t, f] = key.split('.');
            const x = types[t] && types[t].fields.find((y) => y.name === f);
            const df = x && x.dataflow;
            if (!df) continue;
            for (const n of df.controls || []) impact.controls.add(n);
            for (const s of df.sizesOutputs || []) impact.counts.add(`${s.node}->${s.output}`);
            for (const i of df.indexes || []) impact.indexes.add(i.resource);
            for (const to of df.flowsTo || []) { impact.copiedTo.add(to); queue.push(to); }
        }
        // Only what lies inside this dispatch's node set.
        const inside = (n) => nodesById.has(n.split('->')[0]);
        out[field] = {
            controls: [...impact.controls].filter(inside).sort(),
            counts: [...impact.counts].filter(inside).sort(),
            indexes: [...impact.indexes].sort(),
            copiedTo: [...impact.copiedTo].sort(),
        };
    }
    return { recordType: typeName, fields: out };
}

module.exports = { entryRecordImpact, autoPlan, loadPlan, buildEdges, analyseDispatch, dispatchAccess, analysePlan };
