// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// Arithmetic-expression resolution against a name -> raw-definition-text
// table. Generator-agnostic - works the same whether the table came from
// parse-source's constants.js (scanning files on disk) or parse-dxil's
// constants.js (scanning dxc's embedded dx.source.contents debug info).
// ---------------------------------------------------------------------------

// Resolves an arithmetic expression to a number by iteratively substituting
// known identifiers, then safely evaluating the fully-numeric result.
// Returns null if any identifier stays unresolved or the result isn't a
// finite number.
function resolveExpr(expr, table) {
    let current = expr;
    for (let i = 0; i < 8; i++) {
        let changed = false;
        const next = current.replace(/\b[A-Za-z_]\w*\b/g, (id) => {
            if (table.has(id)) {
                changed = true;
                return `(${table.get(id)})`;
            }
            return id;
        });
        current = next;
        if (!changed) break;
    }

    const withoutHexLiterals = current.replace(/0[xX][0-9a-fA-F]+/g, '0');
    if (/[A-Za-z_]/.test(withoutHexLiterals)) return null; // still unresolved identifiers
    if (!/[0-9]/.test(current)) return null;
    if (!/^[\s0-9+\-*/().xXa-fA-F]+$/.test(current)) return null; // safety whitelist

    try {
        // eslint-disable-next-line no-new-func
        const val = Function(`"use strict"; return (${current});`)();
        return typeof val === 'number' && Number.isFinite(val) ? val : null;
    } catch {
        return null;
    }
}

// A named constant's own fully-resolved value: its definition text (itself
// possibly referencing other constants) run back through resolveExpr.
function resolveIdentifier(id, table) {
    if (!table.has(id)) return null;
    return resolveExpr(table.get(id), table);
}

// Annotates every identifier occurrence in `expr` with its own resolved
// value in parens (e.g. "VERT_SEG * HOR_SEG" -> "VERT_SEG (6) * HOR_SEG
// (8)"), leaving literals/operators untouched and unresolved identifiers
// as-is. Deliberately per-identifier rather than resolving the expression
// as a whole - a compound expression's *total* (the product of every
// factor) is a different number from any one factor's own value, and
// conflating the two (annotating the whole expression with its total,
// right after whichever identifier happened to be last) was exactly the
// display bug this exists to avoid - see build-puml/node-label.js's
// scalarTotalSuffix for the other half of that fix.
function annotateExpr(expr, table) {
    return expr.replace(/\b[A-Za-z_]\w*\b/g, (id) => {
        const val = resolveIdentifier(id, table);
        return val != null ? `${id} (${val})` : id;
    });
}

module.exports = { resolveExpr, resolveIdentifier, annotateExpr };
