// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM generated by iteratively
// prompt-review cycling the result. None of the code or any of the
// documentation was written by hand. REVIEW THE CODE AND ITS BEHAVIOR BEFORE
// RELYING ON IT.
// ---------------------------------------------------------------------------
'use strict';

// The part of an IR one dispatch uses: nodes reachable from its entry (dead
// edges included, so never-launched nodes stay visible), the globals those
// nodes use, and the record types they produce/consume or read from buffers
// (plus nested structs). Per-field node lists are cut to the kept nodes.

const { buildEdges } = require('./dispatch-plan');

function subsetIr(ir, entry) {
    const edges = buildEdges(ir.nodes);
    const keep = new Set([entry]);
    const queue = [entry];
    while (queue.length) {
        const id = queue.shift();
        for (const e of edges) if (e.from === id && !keep.has(e.to)) { keep.add(e.to); queue.push(e.to); }
    }
    const nodes = ir.nodes.filter((n) => keep.has(n.id));
    const usedGlobals = new Set(nodes.flatMap((n) => [...(n.globalsUsed || []), ...Object.keys(n.globalAccess || {})]));
    const globals = (ir.globals || []).filter((g) => usedGlobals.has(g.name));

    let recordTypes;
    if (ir.recordTypes) {
        const names = new Set();
        for (const [name, t] of Object.entries(ir.recordTypes)) {
            const u = t.usage || {};
            if ((u.producers || []).some((n) => keep.has(n)) || (u.consumers || []).some((n) => keep.has(n)) || (u.buffers || []).some((g) => usedGlobals.has(g))) names.add(name);
        }
        const queueT = [...names];
        while (queueT.length) {
            const t = ir.recordTypes[queueT.shift()];
            for (const f of (t && t.fields) || []) if (f.structType && !names.has(f.structType)) { names.add(f.structType); queueT.push(f.structType); }
        }
        const cut = (arr) => (arr || []).filter((x) => (typeof x === 'string' ? keep.has(x.split('->')[0]) : !x.node || keep.has(x.node)));
        recordTypes = {};
        for (const name of names) {
            const t = JSON.parse(JSON.stringify(ir.recordTypes[name]));
            if (t.usage) {
                t.usage.producers = cut(t.usage.producers);
                t.usage.consumers = cut(t.usage.consumers);
                t.usage.buffers = (t.usage.buffers || []).filter((g) => usedGlobals.has(g));
            }
            for (const f of t.fields) {
                if (!f.dataflow) continue;
                for (const k of ['readBy', 'writtenBy', 'controls', 'indexes', 'sizesOutputs']) f.dataflow[k] = cut(f.dataflow[k]);
            }
            recordTypes[name] = t;
        }
    }
    return { ...ir, nodes, globals, ...(recordTypes ? { recordTypes } : {}) };
}

module.exports = { subsetIr };
