// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// ---------------------------------------------------------------------------
// The intermediate work-graph IR: the JSON shape both parse-source and
// parse-dxil emit, and the only thing build-puml reads - it never talks to
// either parser's own internals. See docs/ir-format.md for the full field
// reference; this file is just the version tag plus the two read/write
// helpers every command shares.
//
// A "value" field that carries both a resolved number and (optionally) the
// original un-evaluated source text - e.g. numThreads, maxRecords - always
// takes one of two shapes:
//   scalar: { resolved: number|null, source: string|null } | null
//   triple: { resolved: [number|null, number|null, number|null],
//              source:   [string|null, string|null, string|null] } | null
// `source` is null (per-field or whole) whenever it would just repeat the
// resolved literal - i.e. there's nothing more to show than the number
// already in `resolved`. `resolved` is null when the expression could not
// be evaluated (parse-source only - parse-dxil's numbers always come
// pre-resolved from dxc). The field itself is null when the attribute
// wasn't present on the node at all.
// ---------------------------------------------------------------------------

const fs = require('fs');
const path = require('path');

const IR_VERSION = 1;

function writeIrFile(filePath, ir) {
    const withVersion = { irVersion: IR_VERSION, ...ir };
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, JSON.stringify(withVersion, null, 2) + '\n', 'utf8');
    return withVersion;
}

function readIrFile(filePath) {
    const parsed = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    if (parsed.irVersion !== IR_VERSION) {
        console.error(
            `Warning: ${filePath} has irVersion ${parsed.irVersion}, this tool expects ${IR_VERSION} - reading it anyway, but field shapes may have changed.`
        );
    }
    return parsed;
}

module.exports = { IR_VERSION, writeIrFile, readIrFile };
