// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// Every command's own --verbose flag creates one of these and threads it
// through instead of calling console.error directly, so the same call site
// can be a terse default summary or (under --verbose) a full step-by-step
// trace - every found file/node/global, every issued system command (dxc
// invocations, HTTP requests, PNG/SVG writes) - without two copies of the
// message. Everything still goes to stderr (console.error), matching every
// other status line this tool prints - stdout stays reserved for
// machine-readable output (currently just `setup-dxil list`'s table).
function createLogger(verboseEnabled) {
    return {
        isVerbose: !!verboseEnabled,
        // Always printed: the terse default summary (counts, output paths,
        // warnings). Use for the one line per pipeline stage a non-verbose
        // run should still see.
        info(msg) {
            console.error(msg);
        },
        // Only printed under --verbose: per-item detail (each file scanned,
        // each node/global found) and the exact system commands issued.
        verbose(msg) {
            if (verboseEnabled) console.error(msg);
        },
    };
}

module.exports = { createLogger };
