// ---------------------------------------------------------------------------
// LLM-GENERATED CONTENT: This whole project was LLM (Claude Sonnet 5)
// generated by iteratively prompt-review cycling the result. None of the code
// or any of the documentation was written by hand. REVIEW THE CODE AND ITS
// BEHAVIOR BEFORE RELYING ON IT. This tool is just shared so you can easily
// reuse it without burning the tokens yourself.
// ---------------------------------------------------------------------------
'use strict';

// Low-level string/paren helpers with no other dependencies, shared by
// attributes.js, nodes.js, globals.js, and the render/ tree.

function unquote(s) {
    if (s == null) return null;
    const m = s.match(/^"(.*)"$/s);
    return m ? m[1] : s.trim();
}

// ---------------------------------------------------------------------------
// Parameter-list splitting (top-level commas only)
// ---------------------------------------------------------------------------

function splitTopLevel(s) {
    const parts = [];
    let parenDepth = 0;
    let bracketDepth = 0;
    let angleDepth = 0;
    let cur = '';
    for (let i = 0; i < s.length; i++) {
        const c = s[i];
        if (c === '(') parenDepth++;
        else if (c === ')') parenDepth--;
        else if (c === '[') bracketDepth++;
        else if (c === ']') bracketDepth--;
        else if (c === '<') angleDepth++;
        else if (c === '>') angleDepth--;

        if (c === ',' && parenDepth === 0 && bracketDepth === 0 && angleDepth === 0) {
            parts.push(cur);
            cur = '';
        } else {
            cur += c;
        }
    }
    if (cur.trim().length) parts.push(cur);
    return parts;
}

function findMatchingParen(src, openPos) {
    let depth = 0;
    for (let i = openPos; i < src.length; i++) {
        if (src[i] === '(') depth++;
        else if (src[i] === ')') {
            depth--;
            if (depth === 0) return i;
        }
    }
    return -1;
}

function findMatchingBrace(src, openPos) {
    let depth = 0;
    for (let i = openPos; i < src.length; i++) {
        if (src[i] === '{') depth++;
        else if (src[i] === '}') {
            depth--;
            if (depth === 0) return i;
        }
    }
    return -1;
}

function escapeRegExp(s) {
    return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// PlantUML label-string escaping - shared by every render/ file that builds
// a quoted PlantUML string.
function pumlEscape(s) {
    return String(s).replace(/"/g, '\\"');
}

module.exports = {
    unquote,
    splitTopLevel,
    findMatchingParen,
    findMatchingBrace,
    escapeRegExp,
    pumlEscape,
};
