// ---------------------------------------------------------------------------
// AUTO-GENERATED CONTENT: everything below was generated by Claude Sonnet 5
// (Anthropic), an LLM coding assistant, under end-to-end development
// supervision - it was generated as prompted, code was not adjusted or
// written. Review before relying on it.
// ---------------------------------------------------------------------------
#pragma once

// EntryNode -> CullNode
struct DispatchRecord
{
    uint objectCount;
};

// CullNode -> RenderMeshNode. DispatchGrid is picked at runtime, up to the
// ceiling declared by RenderMeshNode's [NodeMaxDispatchGrid].
struct MeshInputRecord
{
    uint3 DispatchGrid : SV_DispatchGrid;
    uint objectIndex;
};
