// ---------------------------------------------------------------------------
// AUTO-GENERATED CONTENT: everything below was generated by Claude Sonnet 5
// (Anthropic), an LLM coding assistant, under end-to-end development
// supervision - it was generated as prompted, code was not adjusted or
// written. Review before relying on it.
// ---------------------------------------------------------------------------
#ifndef MESH_CULLING_STRUCTS_VERTEXTYPES_HLSL
#define MESH_CULLING_STRUCTS_VERTEXTYPES_HLSL

struct Vertex
{
    float4 position : SV_Position;
    float3 normal : NORMAL;
};

#endif
